### ISSUE TITLE
Add ScrollView

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#1]
layouts the child with unknown height (or width) and only draw a subset of it.

**Comment by Gyscos** [comment]
A generic scroll view looks to complicated for now.
TextView and ListView (not yet implemented) are probably the main use cases.
(And a long multiline EditText?)

**Comment by Gyscos** [comment]
TextView now scroll vertically if the given height is too small.

**Comment by Gyscos** [comment]
Let's add FormView or something to the list: long forms are not really lists, but still may need to be scrollable. (Might just be a more general ListView...)

**Comment by gyscos** [comment]
First (simple) proposal: a list of (label, view). Delimiters and/or blanks can also be present. In the first versions, views will be given a single row.

Possible future improvements:
* Accept full-widths elements (headers, ...)
* Accept any view in the first column
* Accept a different number of columns
* Accept views spanning multiple rows (will need an update to `ScrollBase`)
* Include "groups" of items
* Allow to collapse groups

**Comment by gyscos** [comment]
An initial `ListView` implementation is now available in a22c92a1a18aed6302720bf2ec32bdc81510fced The listed improvements may come later; they'll take their own tickets.
