### ISSUE TITLE
Make chan-signal crate a dependency for Termion backend only

### ISSUE THREAD

**Issue by hyst329** [gyscos/Cursive#103]
As far as i understand, the `chan-signal` crate is used for Termion backend only. However, it's listed in Cargo.toml as a _required_ dependency for the whole `cursive` crate, which prevents it to compile under Windows (because `chan-signal` is Unix only). So I've made a patch which makes `chan-signal` an optional dependency and creates a new `termion-backend` feature, which must be used by Cursive application instead of `termion` (I'm not sure that it's possible to "reuse" the name).
```diff
--- Cargo.toml	2017-01-24 09:53:59.000000000 +0300
+++ Cargo.toml	2017-01-30 13:20:32.774967600 +0300
@@ -22,12 +22,15 @@
 [dependencies]
 chan = "0.1.18"
 num = "0.1"
-chan-signal = "0.1"
 odds = "0.2"
 toml = "0.2"
 unicode-segmentation = "1.0"
 unicode-width = "0.1"
 
+[dependencies.chan-signal]
+optional = true
+version = "0.1"
+
 [dependencies.bear-lib-terminal]
 optional = true
 version = "1.3.1"
@@ -52,6 +55,7 @@
 
 [features]
 default = ["ncurses"]
+termion-backend = ["termion", "chan-signal"]
 
 [lib]
 name = "cursive"
```

**Comment by hyst329** [comment]
Now it's a pull request (#104).

**Comment by gyscos** [comment]
Doh, I must have forgotten `chan-signal` was unix-only <_<...
I'd like to avoid having `*-backend` features if possible, but it may not be possible much longer. :(
