### ISSUE TITLE
Support <tab> key for focus navigation

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#11]

**Comment by Gyscos** [comment]
The idea is :
* Lists ignore tab
* Dialog switch from content to buttons (button to button?)
* Forms switch to next field

**Comment by Gyscos** [comment]
Dialog now switch between buttons and content on tab and shift-tab.
(Dialog are expected to be the only active view, so giving the focus to another one is not really supported.)

**Comment by gyscos** [comment]
Next in line is the LinearLayout I suppose, but the (future) FornView will be the true user of this feature.

**Comment by gyscos** [comment]
LinearLayout is now done. FormView will use his own issue for its input, when he gets there.
