### ISSUE TITLE
Panel does not provide space for an EditView

### ISSUE THREAD

**Issue by pathompson1** [gyscos/Cursive#119]
The following example will panic with an error about sizing being incorrect.

```rust
extern crate cursive;
use cursive::Cursive;

use cursive::views::{EditView,Panel};

pub fn main() {
    let mut siv = Cursive::new();
    siv.add_layer(Panel::new(EditView::new()));
    siv.run();
}

```

When running, it panics with the following

```
thread 'main' panicked at 'Was promised 3, received 1', <cargo directory>/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/views/edit_view.rs:270
```

### Version information

* cargo 0.16.0-nightly
* rustc 1.15.1

**Comment by gyscos** [comment]
Indeed, i completely forgot to wrap `layout` in the `Panel` view... >_<
Fix underway. Thanks for the report!
