### ISSUE TITLE
How do you change focus to a specific view

### ISSUE THREAD

**Issue by dvarum12** [gyscos/Cursive#123]
I have to enter some information and then I hit enter I want to set the focus to one of the empty view (in this case TextView) if there are any, but the only way can find that you are able to change the focus form one view to another are by physically hitting the arrow keys on the keyboard.

Am I missing something is this just not possible? I will to be able to do something like this
```
s.find_id::<EditView>("some_id").unwrap().set_focus();
```
but if that is not possible, the ability to send arrow up,down,left and right as events, to trigger the focus change will be a usable workaround too.

**Comment by gyscos** [comment]
Hi!
Cursive indeed lacks a global focus system (currently, each "view group" manages its focus internally).
What this means is that it's not currently possible to select a specific view in a generic view.
Such a focus system is planned, but in the meantime, you can either:
* If you know the parent of the desired view, you may be able to call a method on this parent to select the desired view. If you don't find the proper method, it might be missing! Just ask and I'll add it.
* You can also send Left/Right arrow events directly: you can access the active screen with `Cursive::screen_mut`, on which you can call `View::on_event` with an `Event::Key(Key::Left)`:
  ```rust
  s.screen_mut().on_event(event::Event::Key(event::Key::Left));
  ```
  I probably should add a method to `Cursive` itself to send an event to the current screen to make this a bit easier.

**Comment by gyscos** [comment]
017bb217109c5b0dfc38dcac3e9d6ae456cf6fb5 adds `Cursive::focus_id`, please have a look and see if it fits your use case!

**Comment by dvarum12** [comment]
It works perfectly, thx you :D
