### ISSUE TITLE
SelectView focus can become out-of-bounds on clear()

### ISSUE THREAD

**Issue by simmons** [gyscos/Cursive#125]
The `focus` field of `SelectView` represents the integer index of the currently selected item in the `items` vector.  This value is not reset on `clear()`.  If the user cursors down the list, and the program replaces the contents of `SelectView` via `clear()` followed by one or more `add_item()` calls, the `focus` may become out-of-bounds with respect to the `items` vector.  A call to `selection()` will result in a panic.

I noticed this after implementing a feature in my program where `SelectView` items may be filtered based on a substring provided by the user.  The following change to Cursive seems to fix the problem for me:
```
diff --git a/src/views/select_view.rs b/src/views/select_view.rs
index b0301cd..a5dabcf 100644
--- a/src/views/select_view.rs
+++ b/src/views/select_view.rs
@@ -198,6 +198,7 @@ impl<T: 'static> SelectView<T> {
     /// Removes all items from this view.
     pub fn clear(&mut self) {
         self.items.clear();
+        self.focus.set(0);
     }

     /// Adds a item to the list, with given label and value.
```

Obviously `0` is still out-of-bounds after a `Vec.clear()`, but the documentation does warn that `selection()` "panics if the list is empty."

I suppose a workaround might be to repeatedly call `remove_item()`, which does update `focus` if needed.  There does not appear to be an API for programmatically setting the selection, which some programs might want to do after updating the items.

**Comment by gyscos** [comment]
Whoops, thanks for the report!
Indeed, focus should be reset in `SelectView::clear`.
This should be fixed in 09202f55c80d6a181912e0b84254bc81be01bc5f.
In addition, 7c95114955153b94b7c345620f100ec66aef00a8 adds `SelectView::set_selection`, to move the focus manually.
