### ISSUE TITLE
Weird characters when displaying SelectView

### ISSUE THREAD

**Issue by Matt8898** [gyscos/Cursive#130]
I'm trying to make a simple menu using a selectview, but for some reason 
this happens:
(https://cloud.githubusercontent.com/assets/9578391/24831417/a282f3f4-1c88-11e7-85ee-5fb6c53aa335.png)
Here is my code:

```
    extern crate cursive;
    
    use cursive::Cursive;
    use cursive::views::{SelectView, Dialog};
    use cursive::align::HAlign;
    
    fn main() {
        let mut time_select = SelectView::new().h_align(HAlign::Center);
        time_select.add_item("Short", 1);
        time_select.add_item("Medium", 5);
        time_select.add_item("Long", 10);
    
        let mut siv = Cursive::new();
        siv.add_layer(Dialog::around(time_select).title("How long is your wait?"));
        siv.run();
    }
```
I've tried this with different terminal emulators.

**Comment by gyscos** [comment]
Thanks for the report!
A few questions:
* What OS are you running this on?
* Do you have ncursesw installed?
* What is your locale? (Just run `locale` in a terminal)

**Comment by Matt8898** [comment]
OS: Fedora 25
Locale: en_GB.UTF-8
ncursesw is installed.

**Comment by Matt8898** [comment]
Looks like the problem only happens when using the ncurses and pancurses backends.

**Comment by gyscos** [comment]
Can you show what libraries the binary you're running is linked to?
```
ldd target/...
```

**Comment by Matt8898** [comment]
With ncurses-backend:
linux-vdso.so.1 (0x00007ffe5c910000)
```
   libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007f934fc84000)
   libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f934fa58000)
   libdl.so.2 => /lib64/libdl.so.2 (0x00007f934f854000)
   librt.so.1 => /lib64/librt.so.1 (0x00007f934f64c000)
   libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f934f42e000)
   libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f934f215000)
   libc.so.6 => /lib64/libc.so.6 (0x00007f934ee4f000)
   /lib64/ld-linux-x86-64.so.2 (0x0000559e1e03b000)
   libm.so.6 => /lib64/libm.so.6 (0x00007f934eb46000)

```

**Comment by gyscos** [comment]
I just tried setting up a fedora 25 docker image:
* Installed `git`, `cargo`, `ncurses-devel`
* Ran the example in this issue. Bad borders are observed.
* `locale` indicates `LANG=POSIX`
* Ran `export LANG=en_GB.UTF-8`
* Ran the example again. Borders are fine.

So I really suspect some locale shenanigan. Can you run `locale -a`?

**Comment by Matt8898** [comment]
Apparently it was an issue with the tmux window i was running the program in, because after closing it and then reopening it started working, I'm still not sure what the problem was and I can't reproduce it (the locales were the same).

**Comment by gyscos** [comment]
Well, glad to hear it's better now! :)
