### ISSUE TITLE
Improve backend support

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#132]
The current backend system has a few sore points:
* Right now, when writing a crate to provide new Views, one needs to forward the various backend features so users can decide which backend they use (see #131).
* Providing a new backend in a crate is simply impossible.

It would be nice to improve the situation.

I see two main solutions:
* Make everything generic on the backend used. This means `View<B: Backend>`, `Printer<B: Backend>`, `Cursive<B: Backend>` and so on.
  * Pro: Performance
  * Con: Everything needs to be generic. This means that, for instance, the `&mut Cursive` in callbacks needs to become `&mut Cursive<B>` for the chosen backend - quite a bit of boilerplate for the user.
    * Could be slightly helped with a `type Cursive = Cursive<Backend>;`
    * Maybe type inference can help in callbacks and view creation.
      * Not so sure! A function like `add_view<V: View<B>>(view: V)` may not trigger the type inference for the given `TextView<_>`...
* Use a trait object in the `Printer` and have dynamic dispatch.
  * Pro: easy to set up, easy for the user
  * Con: performance?
    * It also means the `Backend` trait cannot have generic methods. The generic methods were used for closures, which would then have to be boxed - basically, just another performance point. Doh, but `Box<FnOnce()>` are a major pain to deal with... :(
      * The boxed closure issue could be fixed by pushing the colorstyle stack management from the backend to the printer; the backend would only have "enable this style" methods.

I don't really like the idea of dynamic dispatch at the backend level, but I've heard that premature optimization kills baby dolphins, so I'll at least try this and see if the performance drop is even noticeable.

**Comment by lilianmoraru** [comment]
There is the issue of dynamic dispatch, but also the compiler doesn't have the info it currently has to optimize things out.

**Comment by gyscos** [comment]
The backend is now a dynamically-dispatched trait object, so it is possible to implement a backend as a third-party library.
