### ISSUE TITLE
Is mouse supported ?

### ISSUE THREAD

**Issue by ManuCart** [gyscos/Cursive#135]
Hello,

I try to use cursive, but the mouse not working.
How to use the mouse?

**Comment by gyscos** [comment]
Mouse is indeed not supported yet.
It shouldn't be too hard to add that. I'll see how well this is supported by the various backends.

**Comment by ManuCart** [comment]
OK thanks for your help
I will be wait for that

**Comment by sunjay** [comment]
Would like this as well! I left a :+1: on the original post so you know :smile:

**Comment by gyscos** [comment]
I see this is a desired feature! :) 
I started initial work in the [mouse](https://github.com/gyscos/Cursive/tree/mouse) branch. I'm in vacation this week, but things should move forward after that.

**Comment by gyscos** [comment]
Well, things are never as easy as they appear... :(

I started a [design page on the wiki](https://github.com/gyscos/Cursive/wiki/Design:-mouse-support) to compare a few solutions - I'm welcoming any comment or point of view on the subject!

**Comment by lilianmoraru** [comment]
What do you mean by mouse support?
I use the `termion` backend and while I can't click on items, I can scroll through lists.

**Comment by gyscos** [comment]
Interesting, mouse wheels are translated into Up/Down events. Even better, the number of Up events per wheel step depends on the size of the terminal.
I suppose this is some form of compatibility trick, and enabling proper mouse support (with a `MouseTerminal` in termion) would return more specific events.

Mouse support in this issue means 2 things:
* Add specific mouse events to the `Event` enum, and update backends to send those events when appropriate.
* Update current views to deal with those mouse events. This means:
  * For view groups (like LinearLayout), dispatch the event to the correct child depending on the event position.
  * For leaf views (like Buttons), react to mouse events.

**Comment by jD91mZM2** [comment]
What would happen to focused fields? I'm don't know if there is a way to change focus using keys currently, but if there isn't, would mouse be able to bypass that? Could that change be used to click on fields that normally couldn't be clicked?

**Comment by gyscos** [comment]
* Most view groups (LinearLayout, Dialog, ...) offer ways to move focus using keys, and in most situations it lets the user select any field (I'm not sure you can build a layout that has some "unselectable" fields).
* Ideally, there should be a way to move this focus programatically, so people can override it.
* To come back to the mouse, yes, it will be a new way to focus an element. It's conveivable that a `View` lets users select an element with the mouse but not with any key (that'd be pretty weird behaviour, and probably won't happen in the official views here, but the framework allows it).

**Comment by jD91mZM2** [comment]
Ah, so nothing to worry about compatibility-wise, then. I see the mouse very useful for moving focus from an EditText, as I haven't really found a way to move focus out of that.

*On a side note/question: Is the focus documented anywhere?*

**Comment by gyscos** [comment]
I think focus isn't really documented for now. I guess each view group should document how it handle focus.

For now, in an `EditView`, you can leave the focus with Up/Down, Tab/Shift+Tab, or Left/Right if you're at the edge of the text. Should be the same of `TextArea`.

**Comment by gyscos** [comment]
The `mouse.2` branch has made some progress lately, and should now have a rather complete mouse support on the default ncurses backend.

More backend will soon follow ; in the meantime, you're invited to have a look and see if it looks like what you expected.

**Comment by gyscos** [comment]
It's now merged into master. A bit more testing, and the 0.7.0 release will follow.
