### ISSUE TITLE
Iterate oved children of ListView

### ISSUE THREAD

**Issue by zgoda** [gyscos/Cursive#138]
The only attribute that resembles iterable containing ListView children is private, is this operation supported at all? I'm after multiple selection list widget so I'm trying to do this with CheckBoxes.

**Comment by gyscos** [comment]
Thanks for the report!

Indeed, it seems that there's no way to access the views from a `ListView`.
I'm not a huge fan of exposing the `Child` enum, but there may be no other clean way...

**Comment by gyscos** [comment]
d031d3784a8c04917ddf78818a6334f42760ff42 should include methods to access / iterate of a `ListView`'s children - do they fit your use-case?
