### ISSUE TITLE
Allow late binding of callbacks for views

### ISSUE THREAD

**Issue by zgoda** [gyscos/Cursive#141]
It would be nice to be able to create View (eg Button) without specifying callback at initialization time and bind callback later. For example, I wold create the whole screen structure in `::new()` of my `struct` and then bind specific callbacks later when the `self` is ready.

**Comment by gyscos** [comment]
Thanks for the report!

Indeed, `Button` (and probably a few others) are missing `set_callback` to re-define a callback function.
You'll still need to give a callback when creating it, but it can be a dummy closure that does nothing.

**Comment by gyscos** [comment]
f608073bf5c58ef22cc37aa4dd5c6353e55d333f includes `Button::set_callback` to define a new callback after the button was created.
