### ISSUE TITLE
Support default terminal colors

### ISSUE THREAD

**Issue by hcpl** [gyscos/Cursive#145]
All supported backends have capabilities to utilize whatever colors the terminal was using for foreground and background before entering the Cursive program.

### ncurses with `use_default_colors` or `assume_default_colors`
http://invisible-island.net/ncurses/man/default_colors.3x.html
https://docs.rs/ncurses/5.86.0/ncurses/fn.use_default_colors.html
https://docs.rs/ncurses/5.86.0/ncurses/fn.assume_default_colors.html

### pancurses with `use_default_colors`
https://docs.rs/pancurses/0.8.0/pancurses/fn.use_default_colors.html

### termion with `color::Reset`
https://docs.rs/termion/1.4.0/termion/color/struct.Reset.html

### bear-lib-terminal
https://docs.rs/bear-lib-terminal/1.3.3/bear_lib_terminal/terminal/state/fn.foreground.html
https://docs.rs/bear-lib-terminal/1.3.3/bear_lib_terminal/terminal/state/fn.background.html

UPD: bear-lib-terminal solution

**Comment by gyscos** [comment]
Good idea.
One solution is to add `ColorStyle::Default` as a possible color pair, which would use the default color for each backend.

An alternative would be to add `Color::Default`, which could then be used in `ColorStyle::Custom`. Compared to `ColorStyle::Default`, it adds some complexity when using the default style, but allows to use foreground and background independently, which may be an important feature.

**Comment by hcpl** [comment]
Implemented both ideas in https://github.com/hcpl/Cursive/tree/28d0db1bb63833cc0926d257d801ac575b8aeefb.

On stylistic note, I would rename them to `ColorStyle::TerminalDefault` and `Color::TerminalDefault` because `Default` can be interpreted as either "terminal default" or "library default".

**Comment by hcpl** [comment]
Also added a new example that uses default color feature: https://github.com/hcpl/Cursive/tree/9edc6ffc15097c777bea622d4b7731fd01509218.

**Comment by gyscos** [comment]
Wow, thank you so much for this work! I'll have a look at it soon.

**Comment by gyscos** [comment]
Regarding the unused variable in the blt backend, it looks like a leftover from a refactor - I guess I don't check warnings in travis often enough.

**Comment by gyscos** [comment]
I renamed the enum variant to `TerminalDefault` and merged your branch.

**Comment by hcpl** [comment]
Thank you!
