### ISSUE TITLE
Last line of TextArea sometimes hidden

### ISSUE THREAD

**Issue by simmons** [gyscos/Cursive#146]
Under certain circumstances, the last line of text in a TextArea may be hidden from view.  The user can still edit the text with the keyboard, but without visual feedback.  As far as I can tell, the circumstances seem to be:
1. The TextArea is contained within a BoxView with a width SizeConstraint::AtLeast(...) set.
2. A long line of text earlier in the text buffer caused word wrapping.

This code demonstrates the issue: 
```
extern crate cursive;

use cursive::Cursive;                                                                                                                   
use cursive::view::*;
use cursive::views::*;

static ROWS: usize = 3;
static COLUMNS: usize = 15;
static MESSAGE: &'static str = "This line will word wrap.
Line two
Line three
Not visible."; // <-- this line will not be seen even when cursoring down.

fn main() {
    let mut cursive = Cursive::new();
    cursive.add_layer(LinearLayout::vertical().child(BoxView::new(
        SizeConstraint::AtLeast(COLUMNS),
        SizeConstraint::Fixed(ROWS),
        TextArea::new().content(MESSAGE),
    )));
    cursive.run();
}
```
This is on Linux with the default ncurses backend and cursive 0.6.0.

**Comment by gyscos** [comment]
Ah indeed, thank you for the report! A bug in the TextArea was causing this.
It should be fixed in 20e6938bbb937d285b54f883336540705f387b9e.
