### ISSUE TITLE
Override events handling in views

### ISSUE THREAD

**Issue by netvl** [gyscos/Cursive#150]
It would be nice if it were possible to override event handling for specific views. For example, I would like j/k to move selection up and down in a `SelectView`, but right now it is hardcoded to do textual lookup.

**Comment by gyscos** [comment]
Ah indeed, this sounds like a missing feature.

I think this would easily be done using an [`OnEventView`](https://docs.rs/cursive/0.6.4/cursive/views/struct.OnEventView.html) but it would need 2 improvements to fit this need:
* Add a flag to have the `OnEventView` process the event *before* the wrapped view, and not the other way around.
* Allow to set a callback that takes the wrapped view as argument (the current callback takes the cursive root only).

**Comment by gyscos** [comment]
As of 415d0bba96bdd5ba2783ccfc5c79c4ae339c1a02, `OnEventView` has these features. The `select.rs` example has been updated with `j`/`k` navigation.

**Comment by netvl** [comment]
Thank you!
