### ISSUE TITLE
wrong code highlight for map with backquote

### ISSUE THREAD

**Issue by HaskellZhangSong** [gyscos/Cursive#154]
In interpreter of intelliJ

    {(keyword "@dd`-10`") 123}
    => {: @dd, `-10 `123}

which should be 

    {(keyword "@dd`-10`") 123}
    {:@dd`-10` 123}

**Comment by gyscos** [comment]
Hi!
It seems you're interested in the cursive ide for clojure? 

You can find it there:
https://github.com/cursive-ide/cursive
