### ISSUE TITLE
EditView panics on an obscure set of conditions

### ISSUE THREAD

**Issue by Epsylon42** [gyscos/Cursive#157]
The panic apparently happens in `edit_view.rs:441:8` and it says 
```thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `72`: Was promised 72, received 16'```

Here's a code example. It crashes when terminal is shrunk horizontally and is too narrow to contain the string in SelectView:

```rust
extern crate cursive;

use cursive::Cursive;

use cursive::views::{Dialog, SelectView, EditView, LinearLayout};

fn main() {
    let mut siv = Cursive::new();

    siv.add_layer(
        LinearLayout::horizontal().child(
            Dialog::around(
                LinearLayout::vertical()
                    .child(EditView::new())
                    .child(SelectView::new()
                           .item_str("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
            )
        )
    );

    siv.run();
}
```

If I remove either horizontal LinearLayout or Dialog, it works normally. If I replace SelectView with TextView containing the same string, everything works too.

Tested on Ubuntu 16.04 with both ncurses and termion backends. Cursive version 0.7.2

So, uh, this might be a problem.

**Comment by gyscos** [comment]
Indeed, looks like a bug!
Thanks for the report - I'll look into that.

**Comment by gyscos** [comment]
11ea8a592be2da27cd5ea8ec8b17e0977e575a2e should fix that.

**Comment by Epsylon42** [comment]
Kind of. The example code works, but it still panics if there's another child in the horizontal layout. Doesn't matter what it is, TextView, DummyView, another EditView etc.

```rust
siv.add_layer(
    LinearLayout::horizontal()
        .child(TextView::new("aaaaaaa"))
        .child(Dialog::around(
            LinearLayout::vertical()
                .child(EditView::new())
                .child(SelectView::new()
                        .item_str("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))
        )
);
```

**Comment by Epsylon42** [comment]
It works now. Thanks.
