### ISSUE TITLE
No documentation about running examples

### ISSUE THREAD

**Issue by non-descriptive** [gyscos/Cursive#158]
There's a bunch of examples but no any documentation how to build and run examples.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, the examples currently expect that the user is already familiar with cargo's way of running them ; for instance:

```
cargo run --example lorem
```

I was thinking of adding a Readme in the examples directory anyway, so I'll add directions there to help people unfamiliar with that.

**Comment by gyscos** [comment]
I added a basic Readme: you can see it at https://github.com/gyscos/Cursive/tree/master/examples

**Comment by non-descriptive** [comment]
Great, thanks.
