### ISSUE TITLE
Support word-wrapping for asian languages

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#16]
The main issue is resolved, the remaining point is word-wrapping for asian languages. More specifically, line break can happen between many characters, not just at whitespaces. This would avoid breaking lines at an early lonely whitespace, wasting space on the line.

Old issue:
Some CJK characters (and maybe others?) use 2 columns in the terminal.
Cursive currently assumes every codepoint is 1 column wide.
First step is to use grapheme instead of codepoint when computing width.
Until then asian languages will not work well.

**Comment by Gyscos** [comment]
May have a look at https://unicode-rs.github.io/

**Comment by gyscos** [comment]
Also https://msdn.microsoft.com/en-us/goglobal/bb688158.aspx

**Comment by gyscos** [comment]
Most views should now display wide characters a bit better. `EditText` in particular was completely broken before, and now handle them properly.
TextViews still needs work there, so let's jump into [UAX14](http://www.unicode.org/reports/tr14/)... <_<
I might even have a shot at hyphenation while I'm at it...

**Comment by gyscos** [comment]
So TextViews have been updated to at least not crash with wide chars. The word-wrap algorithm has not changed, which means it tries to break one whitespaces, or between any two graphemes if it can't find a whitespace.

**Comment by gyscos** [comment]
![screenshot from 2016-07-04 21-34-45](https://cloud.githubusercontent.com/assets/564903/16574025/61c94720-422f-11e6-888d-7cbfc44a6ccc.png)

**Comment by gyscos** [comment]
Will be solved by #61
