### ISSUE TITLE
Using Spacer in layout

### ISSUE THREAD

**Issue by punkkeks** [gyscos/Cursive#163]
Sometimes I just want to align a TextView on the left and a Editview on the right, for that I need some kind of [space](http://doc.qt.io/qt-4.8/qspaceritem.html)

I think with some more things, this will be a full grown gui library for terminals, which should be awesome.

Ps. Sorry for the amount of tickets I openeded, I think i will have some time at the weekend to implement 1-2 of them.

**Comment by gyscos** [comment]
Right now, a spacer can be simulated with a [`Boxable`](https://docs.rs/cursive/0.7.4/cursive/view/trait.Boxable.html) [`DummyView`](https://docs.rs/cursive/0.7.4/cursive/views/struct.DummyView.html):

```rust
use cursive::view::Boxable;
use cursive::views::DummyView;

linear_layout.add_child(DummyView.fixed_width(2));
```

**Comment by gyscos** [comment]
If you want something that takes all possible width, I think using `.full_width()` instead of `.fixed_width(2)` should work - I'll double check that.

**Comment by punkkeks** [comment]
Sweet. Somehow `full_width()` didn't work for me in the first place, but now it does. Really nice :) Maybe the doc can be updatded to describe this behavoir, because it wasn't clear for me. Let's see what I can do at the weekend.
