### ISSUE TITLE
Suggestion: StackView::pop() returns the popped layer

### ISSUE THREAD

**Issue by alekratz** [gyscos/Cursive#165]
My use case is that I have two separate logging windows that I want to flip back and forth between, in the same position on-screen. I figured I'd implement this by doing `StackView::pop()` twice, and push the popped values back in the same order they were popped. However, I can't (easily) do this since `StackView::pop()` doesn't return anything.

Since a `StackView` is just backed by a `Vec`, it would be a trivial change to have it return some `Option<Layer>`, right? What do you think about this?

**Comment by gyscos** [comment]
That's a good idea! Just a few points:
* This means `pop_layer` now returns something, so it may confuse closures that were only calling that. Though one solution is to only modify the `StackView` method and not the shortcut one defined on `Cursive` (which is what you did in the PR).
* The returned view is a `Box<View>`. It now *does* implement `View`, so it can be given as-is to `add_layer`, but it means it'll get a second layer of boxing. This may not be such a problem (especially if you don't do it too often). Possible solutions would be:
  * Use something like a `Into<Box<View>>` trait to accept both direct views and boxed views, so it's only boxed once.
  * Add a separate method `add_boxed_layer(&mut self, Box<View>)`

**Comment by alekratz** [comment]
>This means pop_layer now returns something, so it may confuse closures that were only calling that. 

Yeah, I had to fix something in `Dialog` as a result of this. It's probably going to be a breaking change for some people.

>Though one solution is to only modify the StackView method and not the shortcut one defined on Cursive (which is what you did in the PR).

Ah, I didn't see `pop_layer` was also being called in `Cursive` as well. Personally, I think it'd be more consistent if it returned the popped item - but that is up to you. Making that change cascades down into `MenuPopup`, so that's going to need brackets around it, too.

IMO, if you do accept the PR, you may want to hold off until the next minor version because of the breaking changes.

>The returned view is a Box<View>. It now does implement View, so it can be given as-is to add_layer, but it means it'll get a second layer of boxing. This may not be such a problem (especially if you don't do it too often).

That's a good point, I wasn't aware that `Box<View>` implemented `View`.

>Use something like a Into<Box<View>> trait to accept both direct views and boxed views, so it's only boxed once.

Were you thinking of adding that trait bound to `add_layer_at`? That's where the view actually ends up being boxed. I think I'll try that first.

>Add a separate method add_boxed_layer(&mut self, Box<View>)

I'm going to try to *try* to avoid doing something like this, I'd like to have the compiler figure it out for us.

**Comment by gyscos** [comment]
`StackView::pop_layer` now returns the pop'ed layer, and `StackView::add_layer` was updated to not re-wrap views that are already box'ed. This means you can keep pop'ing and adding it back, and it will still be in a single `Box`.
