### ISSUE TITLE
Titleposition in Dialogview

### ISSUE THREAD

**Issue by punkkeks** [gyscos/Cursive#167]
A cool feature would be to able to specify the position of the title in a dialogview. 
You can e.g. write 

    DialogView::new("Foo").title_pos(Align::top_left())...

which would result in 
![grafik](https://user-images.githubusercontent.com/921462/33841376-dadf0fcc-de97-11e7-914c-88aedf683c93.png)

of course center would be an illegal position and there is a question how to deal with it. I think the easiest solution would be a `panic!()`, but a compiletime error would be better. 

Just drop your thoughts about this here and I will try to implement this :)

**Comment by gyscos** [comment]
Good idea!

It could take a `HAlign` to only care about horizontal alignment. Having the title on the bottom doesn't sound a common use-case to warrant to possible panic.

**Comment by punkkeks** [comment]
Hmm, what about vertical dialog titles? So you could possibly "rotate" the text by 90° and have it on the vertical borders of the box? It would certainly a fun idea and we would cover all usecases (except) for the center one) 

Am 11. Dezember 2017 18:12:06 MEZ schrieb Alexandre Bury <notifications@github.com>:

**Comment by gyscos** [comment]
Hmm I'm not sure how to rotate text yet (it'd be a bit more complex since characters are not square, but twice as tall as they are wide).

I think for now, a `HAlign` would be the simplest option, and would match the way buttons are aligned. If/when different layouts for title and buttons are added, we'll think of a more general design.

**Comment by punkkeks** [comment]
Let me clarify the rotation part. Instead of writing

    text

You write 

    t
    e
    x
    t

But yes, I see the problems, which arise and I agree, that top halign would be the simplest method. Let's see, what I can do today



Am 11. Dezember 2017 18:31:10 MEZ schrieb Alexandre Bury <notifications@github.com>:

**Comment by punkkeks** [comment]
Another point to mention is, how big the distance between the border and the actual text should be? Do you have a policy for that, e.g. fixed vs percentage? 



Am 11. Dezember 2017 18:31:10 MEZ schrieb Alexandre Bury <notifications@github.com>:

**Comment by gyscos** [comment]
I would have put all the way to either direction:

```
┌┤ Title ├────┐
│             │
```

```
┌────┤ Title ├┐
│             │
```

As for vertical text, it could fit well for some japanese/chinese text, but paradoxically it'd be a pain for those, since each character would be 2-columns wide, and wouldn't fit well on the border.

**Comment by gyscos** [comment]
Thank you for the PR!
