### ISSUE TITLE
RFC/Announcement: cursive_hexview

### ISSUE THREAD

**Issue by hellow554** [gyscos/Cursive#175]
Hi everyone,

for my project in needed some kind of displaying hexdata so I created a hexview which is accessable via https://github.com/hellow554/cursive_hexview

Please, feel free to file any issues, pullrequests, doc changes, more cats pics, everything.
I would really like to get some feedback, because it's my first published rust project.

One particular thing I noticed is, that I can't use `with_id` or `*_height/width` methods on the view. What is necessary to be able to use them @gyscos ?

Anyhow, you are welcome to use is, commend it, fork it, change it with any ideas you might have.

**Comment by gyscos** [comment]
Those methods are part of extension traits implemented for all Views: you just need to `use` the trait.
https://docs.rs/cursive/0.7.5/cursive/traits/index.html

**Comment by hellow554** [comment]
Hm, it does not work though :( 

```
error[E0599]: no method named `with_id` found for type `cursive_hexview::HexView` in the current scope
   --> src/gui.rs:130:35
    |
130 |         .child("", HexView::new().with_id("reserved2_send"))
    |                                   ^^^^^^^
    |
    = note: the method `with_id` exists but the following trait bounds were not satisfied:
            `cursive_hexview::HexView : cursive::traits::Identifiable`
            `&cursive_hexview::HexView : cursive::traits::Identifiable`
            `&mut cursive_hexview::HexView : cursive::traits::Identifiable`
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use cursive::view::identifiable::Identifiable;`
```

which is private btw...

**Comment by gyscos** [comment]
So the error messages is unfortunately using the wrong (private) path, but the trait itself is present in the link I posted:
https://docs.rs/cursive/0.7.5/cursive/view/trait.Identifiable.html

**Comment by hellow554** [comment]
I included the use directive but still the error. Is it possible, that it does not automatically implement it for external structs and I have to implement them "manually"?

**Comment by gyscos** [comment]
Here is the default example from hexview using `with_id`, `fixed_width` and `call_on_id`:

```rust
extern crate cursive;
extern crate cursive_hexview;

use cursive_hexview::{DisplayState, HexView};
use cursive::Cursive;
use cursive::views::{Dialog, DummyView, LinearLayout, TextView};

use cursive::traits::{Boxable, Identifiable};

fn main() {
    let mut cur = Cursive::new();
    let explanation =
        TextView::new("Use the keys + - ↑ ↓ ← → 0-9 a-f for the HexView.\nUse q to exit.");
    let view = HexView::new().display_state(DisplayState::Editable);

    cur.add_layer(
        Dialog::around(
            LinearLayout::vertical()
                .child(explanation)
                .child(DummyView)
                .child(view.with_id("view").fixed_width(80)),
        ).title("HexView"),
    );

    cur.add_global_callback('q', |cur| cur.quit());
    cur.add_global_callback('o', |cur| {
        cur.call_on_id("view", |v: &mut HexView| ());
    });
    cur.run();
}
```

**Comment by hellow554** [comment]
I indeed can confirm that it works in the examples, strange though it does not work in my project :D I will investigate that. But thank you netherless

**Comment by gyscos** [comment]
Anyway - it looks really nice! Congratulations for the good work! :)
I'll add a mention in the Readme if you're ok with that?

**Comment by hellow554** [comment]
Sure, I would be pleased :)

**Comment by gyscos** [comment]
You may want to add a screenshot on the Readme to impress visitors ;)

**Comment by hellow554** [comment]
It looks like the trait thing might be a regression to 0.7.5. I build my project with your git linked to this repository and then it tells me about all the strange things (to use the private trait and that is it not possible to use with_id). You may want to test that and verify it with my experience?

Sure, I can include a picture of the default example :)

**Comment by gyscos** [comment]
The example I posted compiles fine with this in `Cargo.toml`:

```toml
[dependencies]
cursive = { git = "https://github.com/gyscos/cursive", default-features = false }
```

**Comment by hellow554** [comment]
Maybe a `cargo update`?! I can "verify" that it really is a problem with the git branch instead of the crates package.

**Comment by gyscos** [comment]
You can try the example and see that it compiles fine after any combination of `clean`/`update`/... The `Cargo.lock` contains:

```toml
[[package]]
name = "cursive"
version = "0.7.6-alpha.0"
source = "git+https://github.com/gyscos/cursive#ba0bc6dc564f714ce234e64595e9db70c7dc126d"
```

Maybe you're pulling two different versions of `Cursive`? Can you check your `Cargo.lock` if there's any duplicate entry?

**Comment by hellow554** [comment]
Yeah... that's the problem. One from the cursive_hexview itself (namely the stable version 0.7.5) and one from "my" cargo.toml namely the git version. Any method to get around this, e.g. just tell cursive_hexview to use the version the user wants?

**Comment by gyscos** [comment]
Not sure how to do that. I tried using [the `[patch]` section](http://doc.crates.io/specifying-dependencies.html#working-with-an-unpublished-minor-version), but it doesn't seem to work as intended. Somehow cargo still things 0.7.6-alpha and 0.7.5 aren't compatible.
