### ISSUE TITLE
Fullscreen dialog in pancurses on Windows

### ISSUE THREAD

**Issue by agavrilov** [gyscos/Cursive#182]
Bug report

# Problem description

I create a full screen dialog using add_fullscreen_layer on Cursive and full_screen method on Dialog. When I resize the window created by pancurses, the dialog is not resized with the window. It keeps its size unchanged.

Sample code where you can see an issue:
```rust
    let mut app = Cursive::new();
    app.add_fullscreen_layer(
        Dialog::text("Sample")
        .button("Cancel", move |s| {
            s.quit();
        })
        .full_screen()
    );
    app.run();
```

# Environment

* Operating system: windows
* Backend used: pancurses
* Current locale: English
* Cursive version: 0.7.5 from crates.io

**Comment by gyscos** [comment]
Blast! It seems we fail to detect window resizing. Apparently it's not reported the way it is on Linux... :S

Anyway, thanks for the report!

**Comment by gyscos** [comment]
I suppose this is fixed? Thanks for the PR! :D
