### ISSUE TITLE
Bug Report: When insert file content into TextArea programm crush

### ISSUE THREAD

**Issue by aprokurov** [gyscos/Cursive#186]
# Problem description
When you insert file content into TextArea by set_content programm just closes
Code here: https://github.com/aprokurov/cursiveredactor/blob/master/src/main.rs
# Environment

* Operating system: Linux Debian, NixOS, Void
* Backend used: ncurses 6.0
  
* Current locale: en_US-UTF8.
* Cursive version: 0.7.5

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, `TextArea::set_content` wasn't busting the cache properly, and it caused weird issues.
It should be fixed in latest commit (6bb0812a3995dcedd18612250c4be306f38c97c3).

**Comment by gyscos** [comment]
Fix should now be live.
