### ISSUE TITLE
[help] Composing view from existing views

### ISSUE THREAD

**Issue by xliiv** [gyscos/Cursive#187]
Any smart idea how to implement view which is composed from other views?
I've got two concepts but each fails, here's the code:

```rust
#[macro_use]
extern crate cursive;

use cursive::Cursive;
use cursive::Printer;
use cursive::traits::*;
use cursive::view::ViewWrapper;
use cursive::views::*;

struct Composed1 {
    view: LinearLayout,
}

impl Composed1 {
    fn new() -> Self {
        let mut layout = LinearLayout::vertical()
            .child(EditView::new())
            .child(EditView::new());

        Composed1 {
            view: layout,
        }
    }
}

impl ViewWrapper for Composed1 {
    wrap_impl!(self.view: LinearLayout);
}


struct Composed2 {
    left: EditView,
    right: EditView,
}

impl Composed2 {
    fn new() -> Self {
        Composed2 {
            left: EditView::new(),
            right: EditView::new(),
        }
    }
}
impl View for Composed2 {
    fn draw(&self, printer: &Printer) {
        self.left.draw(printer);
        self.right.draw(printer);
    }
}

fn main() {
    let mut siv = Cursive::new();

    let widget = Composed1::new();
    //let widget = Composed2::new();
    siv.add_layer(Dialog::around(widget).fixed_width(20));

    siv.run();
}

```

**Comment by gyscos** [comment]
Hi!

There is two main ways to compose views:
* Use existing view groups (like `LinearLayout`) and either use that directly, or wrap it (as you did).
* Implement the view group yourself

The first solution is usually straightforward, and it seems to work in the example you posted (isn't it?).

The second solution is a bit more tricky, as you need to implement most of the other methods from the `View` trait. In particular, you will need to layout the two (or more) child views, forward input and focus to them, etc. This is doable (this is how `LinearLayout` is done in the first place), but it may be a bit overkill if an existing view would do just as well.

**Comment by xliiv** [comment]
I wasn't precised :)
Obviously `Composed1` works like you're saying. The thing which bothers me is that I'm losing reference to those `EditView`s (or am I missing something?)
Like let's say I'd like to do some logic between those `EditView`s;
```rust
fn wrap_on_event(&mut self, event: Event) -> EventResult {
    Event::Key(Key::Enter) => {
        // use both edit somehow, like in for example writing content from first EditView to the second EditView
    }
}
I could add to them `id`s with `with_id` but this only allows you to access them if you have `Cursive` struct so this is not solution.
For me `Composed1` solution is more reasonable (then `Composed2`) and if only the reference thing were resolved I'd be satisified.
Do you have any idea for that?

**Comment by gyscos** [comment]
Reacting to events can be a 2-steps process:
* First, the body of the method `on_event` (or `wrap_on_event`) itself is run, where you have direct access to the current view and the event.
* Then, a `EventResult` is returned, which *itself* can carry a callback, that will this time have access to a `&mut Cursive`:

```rust
fn wrap_on_event(&mut self, event: Event) -> EventResult {
    // Here we can use `self` to prepare data for example
    let text = self.make_text(event);

    EventResult::with_cb(move |s: &mut Cursive| {
        // We can call methods on `s` here - like looking for other views!
        s.call_on_id("text_view_1", |view: &mut EditView| {
            view.set_content(text);
        }).unwrap();
    })
}
```

**Comment by gyscos** [comment]
I also added `LinearLayout::get_child_mut(&mut self, usize)` to directly access the children.
This way, you could do:

```rust
fn wrap_on_event(&mut self, event: Event) -> EventResult {
    let content = self.view.get_child(0).unwrap().get_content();
    self.view.get_child_mut(1).unwrap().set_content(&content);

    EventResult::Consumed(None)
}
```

**Comment by xliiv** [comment]
Perfect, [it](https://github.com/gyscos/Cursive/issues/187#issuecomment-358407301) looks promising. i'm gonna use it.
And the `self.view.get_child_mut(..)` is even better.
I'm gonna play a bit with it and I'll close this issue (or ask about doubts).
Thanks

**Comment by xliiv** [comment]
I've used [this](https://github.com/gyscos/Cursive/issues/187#issuecomment-358407301) and works perfect.
Thanks!

**Comment by xliiv** [comment]
There is an issue with [2nd solution](https://github.com/gyscos/Cursive/issues/187#issuecomment-358409599) or maybe I broke something?

```rust
#[macro_use]
extern crate cursive;
use std::any::Any;

use cursive::Cursive;
use cursive::Printer;
use cursive::traits::*;
use cursive::view::ViewWrapper;
use cursive::views::*;

struct Composed1 {
    view: LinearLayout,
}

impl Composed1 {
    fn new() -> Self {
        let mut layout = LinearLayout::vertical()
            .child(EditView::new())
            .child(EditView::new());

        Composed1 {
            view: layout,
        }
    }
}

impl ViewWrapper for Composed1 {
    wrap_impl!(self.view: LinearLayout);

    fn wrap_on_event(&mut self, event: Event) -> EventResult {
        eprintln!("xxx");
        let content = self.view.get_child(0).unwrap().downcast_ref::<EditView>().unwrap().get_content();
        self.view.get_child_mut(1).unwrap().downcast_mut::<EditView>().unwrap().set_content(&content);

        EventResult::Consumed(None)
    }
}


fn main() {
    let mut siv = Cursive::new();

    let widget = Composed1::new();
    siv.add_layer(Dialog::around(widget).fixed_width(20));

    siv.run();
}
```
gives

```
error[E0599]: no method named `downcast_ref` found for type `&cursive::traits::View` in the current scope
  --> examples/ref.rs:33:55
   |
33 |         let content = self.view.get_child(0).unwrap().downcast_ref::<EditView>().unwrap().get_content();
   |                                                       ^^^^^^^^^^^^

error[E0599]: no method named `downcast_mut` found for type `&mut cursive::traits::View + 'static` in the current scope
  --> examples/ref.rs:34:45
   |
34 |         self.view.get_child_mut(1).unwrap().downcast_mut::<EditView>().unwrap().set_content(&content);
   |                                             ^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by xliiv** [comment]
Your version definitely works

**Comment by gyscos** [comment]
I'm a bit disappointed by the need to implement those two methods everywhere though. The `view_any!()` macro helps a bit with that, but it's still something surprising and a bit annoying for people implementing `View` themselves. :(

**Comment by gyscos** [comment]
And found it: these `as_any` methods are now only defined for a `AnyView` trait.
* `View` can be implemented as usual without any difference
* View parents now store and return `Box<AnyView>`/`&AnyView` instead of just `View`, which brings these `as_any()` methods. (`AnyView` is automatically implemented for any `T: View`).

This removes the need for the `view_any!()` macro.
