### ISSUE TITLE
EditView no longer implements with_id

### ISSUE THREAD

**Issue by cauebs** [gyscos/Cursive#191]
The example for `EditView` uses `with_id` ([here](https://github.com/gyscos/Cursive/blob/master/src/views/edit_view.rs#L50)) but this method is not available anymore. How else am I supposed to get the id? 

I'm trying to create a callback that will edit the text (`set_on_edit`) but how will the callback find the `EditView`?

Sorry if I'm just mistaken.

**Comment by gyscos** [comment]
Hi!

The `with_id` method actually comes from the [`Identifiable`](https://docs.rs/cursive/0.7.5/cursive/view/trait.Identifiable.html) trait, which is implemented for all Views.
You just need to import it (`use cursive::view::Identifiable`) and it'll work as expected! :)

**Comment by cauebs** [comment]
It was indeed my mistake. Thanks a lot for the quick response! ;)
