### ISSUE TITLE
[question] 0.7.6 release prediction

### ISSUE THREAD

**Issue by xliiv** [gyscos/Cursive#202]
When the 0.7.6 version is planned to be released. More or less of course. :)

**Comment by gyscos** [comment]
Hi!

We'll be jumping to 0.8.0 directly (there were a few breaking changes).
I still need to fix `utils::lines::simple::LinesIterator` to use the new algorithm, and we should be ready to publish. I'm a bit busy this week, so this may come around the weekend.

**Comment by gyscos** [comment]
Alright, the simple `LinesIterator` now relies on the one from `utils::lines::spans`, which means `TextArea` not uses the correct line-splitting formula (and doesn't split before punctuation marks). So just a bit more testing, and `0.8.0` should follow shortly.

**Comment by xliiv** [comment]
I'd be happy if this stuff https://github.com/gyscos/Cursive/pull/211 were also merged.
Of course I'll fix comments before :)

**Comment by gyscos** [comment]
0.8.0 published today.
