### ISSUE TITLE
SelectView::with_selection?

### ISSUE THREAD

**Issue by scottlamb** [gyscos/Cursive#205]
Feature request (or help finding an existing feature if it exists):

# Problem description

I'd like to use a popup `SelectView` to represent a field of an existing data record. I'd like the initial focus to be on the current state of the field, so that if you open up the record and save it without touching this field it's unchanged.

As far as I can see, the only way to do that now is to have the current state of the record be the first item I add to the field. But I think that's both disorienting to the user (the possible values are not in a consistent/natural ordering) and awkward for the programmer.

Instead, I'd like `SelectView` to provide something like this:

```rust
impl SelectView {
    ...
    fn selected(self, i: usize) -> Self { ... }
    fn select(&mut self, i: usize) { ... }
    ...
}
```

that I can use like so:

```rust
let s = views::SelectView::new()
    .item("foo", "foo")
    .item("bar", "bar")
    .item("baz", "baz")
    .selected(2);   // set the focus to items[2], "baz".
```

to modify what `.selected_id` returns / what is shown.

[edit: I picked "focus" initially before to be consistent with internal stuff, but `.selected_id` is the external API, so that's more relevant.]

# Environment

* Operating system: n/a
* Backend used: n/a
* Current locale (run `locale` in a terminal): n/a
* Cursive version (from crates.io, from git, ...): 0.7.5

**Comment by gyscos** [comment]
Thanks for the input!

Indeed, you shouldn't have to re-order your items just to change the default selection. Being able to specify the default selection is indeed something we should support!

**Comment by gyscos** [comment]
847fd7d800ebee5dd00ca8389d979192254bc79e adds `SelectView::selected`. Note that there is already `SelectView::set_selection` for a non-chainable variant.

**Comment by scottlamb** [comment]
Thanks! Not sure how I missed `SelectView::set_selection`.
