### ISSUE TITLE
Numpad plus on windows

### ISSUE THREAD

**Issue by hellow554** [gyscos/Cursive#209]
I don't know whether this is a bug/feature in cursive or pancurses, sorry for the noise if this is not the scope of cursive.

I am working on windows with pancurses-backend and master branch.
For my hexview I normally use the <kbd>+</kbd>-Numpad to increase the array, but on windows it does not map to `Char('+')`, instead it is an Unknown with `[161, 0, 0, 0]` (the same goes for the minus, times and div key as well with 160, 159, 154 as the first value)

Is there a way to fix it here or should I open a request on pancurses repo?

**Comment by gyscos** [comment]
I'm not sure.

I think this should be handled in pancurses' `windows::to_special_keycode`.
In the meantime, it should be possible to parse it here anyway.

**Comment by IGBC** [comment]
turn numlock on.

**Comment by hellow554** [comment]
@IGBC doen't work for me ;)

**Comment by gyscos** [comment]
Can you run the [`getch_example`](https://github.com/ihalila/pancurses/blob/master/examples/getch_example.rs) example from pancurses, and report what you see when you press this key? Thanks!

**Comment by hellow554** [comment]
Both problems are now fixed. I can use `+` on Numpad and `ø`/`Ø`. I'm happy, thanks!
