### ISSUE TITLE
Panic: Missing UTF-8 byte while typing ø

### ISSUE THREAD

**Issue by hellow554** [gyscos/Cursive#210]
I am on Windows 10 with pancurses backend and git master branch.

When I am typing [this](http://www.fileformat.info/info/unicode/char/d8/index.htm) character into a editview the program will panic in line [#L241](https://github.com/gyscos/Cursive/blob/master/src/backend/curses/pan.rs#L241) because I don't know why :)
This also happens with the [lowercase](http://www.fileformat.info/info/unicode/char/f8/index.htm) version. I suspect that other chars in that area will trigger this as well.

This is absolutly reproduceable.

**Comment by hellow554** [comment]
I suspect that this will happen, because you cast a char as u32, which will convert the `ø` into `248` (don't ask me why!) and thus will trigger the `(c as u32) <= 255` condition which is wrong. 
I don't understand the intention of the code, which is my problem I guess ;)

**Comment by hellow554** [comment]
Okay, after 5 minutes of thinking (maybe a bit more) I know why 248 :) It's the 248th character (in utf16/utf32). Utf-8 uses some bit magic to calculate the actual length of a character (you propably know this better than me), but while converting it to a u32, it will become the 248th character again and so this condition triggers.
Now my question, what are you doing with those two match arms (checking between 32 and 255 and lower equals 26). That is obviously wrong :)

**Comment by gyscos** [comment]
It seems pancurses behaves differently on windows and linux here - and I could only test it on linux.

On linux, pancurses doesn't parse anything, and directly returns the raw utf8 bytes one by one. This means we don't receive `'ø'` (which in UTF8 is `0xC3 0xB8`), but `'Ã' '¸'` (which are the unicode values `U+C3` and `U+B8`). You can see it [in pancurses](https://github.com/ihalila/pancurses/blob/master/src/window.rs#L288) where it returns `Some(Input::Character(i as u8 as char))`.

This means pancurses is actually lying. For ASCII values, there's no difference anyway; but for utf8-encoded text, pancurses is returning raw bytes disguised as `char`. So in cursive, we treat is as raw bytes again, and parse utf8 here.

The mystery is what happens on windows. I suppose windows might encode its input as utf-16, which will definitely confuse both pancurses and cursive.

I think the cleanest solution would be to have pancurses actually parse the input (as utf8 on linux and utf16 on windows) and return an actual `char`.

**Comment by hellow554** [comment]
The [getch example] works though :/ It does recognize `ø` as single character under windows.


[getch example]: https://github.com/ihalila/pancurses/blob/master/examples/getch_example.rs

**Comment by gyscos** [comment]
I any case, panicing on weird input is pretty bad, so it should at least be better with the latest commit.

**Comment by gyscos** [comment]
This is fixed in pancurses 0.15.
