### ISSUE TITLE
Not rewritable global callbacks (`app.add_global_callback`)

### ISSUE THREAD

**Issue by Virtuos86** [gyscos/Cursive#214]
# Problem description
Not rewritable global callbacks:

```
extern crate cursive;

use cursive::Cursive;

fn main() {
    let mut siv = Cursive::new();

    // We can quit by pressing `q`
    siv.add_global_callback('q', Cursive::quit);
    siv.add_global_callback('q', |_| {});
    // A previous line should rewrite a callback in `app.callbacks`, because a field
    // `app.callbacks` has HashMap type. And if I type "q" then nothing will happen.
    // But seems like these callbacks collects and are called one by one,
    // because a program is closes.
    siv.run();
}
```

# Environment

* Operating system: Linux Mint 18.02.
* Backend used: ncurses (NCURSES_VERSION = "6.0").
* Current locale: ru_RU.UTF-8.
* Cursive version: from git.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, I think in version 0.8.0 we now store multiple callbacks per key press, which means it may be tricky to re-write previous callbacks.

I'm thinking of adding `Cursive::get_global_callbacks('q') -> Option<&mut Vec<Callback>>` or something like that, which would allow you to clear the callbacks for a given event (or just remove the first/last one, ...).
Alternatively, `Cursive::clear_global_callbacks('q')` would let you remove all callbacks for an event. This is simpler, but offer less flexibility if you only want to remove some callbacks.

I think `clear_global_callbacks` may be the best solution: it's easier to use, and is probably enough for most use-cases - users who need more control may add their own logic in the callback itself.

**Comment by Virtuos86** [comment]
@gyscos Thanks a lot! I was discouraged strange behavior of my code.

> I think clear_global_callbacks may be the best solution

It's the definitly good idea. Now I have a special function for avoiding previously settled callbacks when I'm opening a new view in my application:
```
fn disable_current_shortcuts(app: &mut Cursive) {
    use map::Direction::*;
    for character in CHARACTERS.iter() {
        app.add_global_callback(*character, |_| {});
    }
    app.add_global_callback( Key::Enter, |_| {} );
    app.add_global_callback( Key::Esc, |_| {} );
    app.add_global_callback( Key::Up, |_| {} );
    app.add_global_callback( Key::Down, |_| {} );
    app.add_global_callback( Key::Left, |_| {} );
    app.add_global_callback( Key::Right, |_| {} );
    app.add_global_callback( Key::Backspace, |_| {} );
}
```
It seems like a lot of copiepasted code. Just I'm adding new key events during the work, step by step.

**Comment by gyscos** [comment]
48514991d2ebc0121f76b2f6b1a559ed67c0cd2d adds `Cursive::clear_global_callbacks`
