### ISSUE TITLE
SelectView select_up/down doesn't trigger on_select closure

### ISSUE THREAD

**Issue by yeastplume** [gyscos/Cursive#217]
Hi @gyscos 

I've just noticed that if a closure is specified on a SelectView via set_on_select(), the callback isn't triggered when selecting programmatically via select_up() and select_down(). Is this intentional behaviour or an omission?

Many thanks!

**Comment by yeastplume** [comment]
Sorry, I just noticed now this is a complete duplicate of: https://github.com/gyscos/Cursive/issues/184.. was the solution suggested there implemented?

**Comment by gyscos** [comment]
Not quite yet  it seems - I'll get to that soon!

**Comment by gyscos** [comment]
Commit 987796f2faaa3158e6dd1279390d9da5652e81cb should bring the desired feature: `SelectView::select_up` now returns a `Callback` object; you should call it with a `&mut Cursive` to trigger any registered callback.

**Comment by yeastplume** [comment]
Thanks again! I'll give it a try at some point soon. Just a suggestion that it may be a little bit awkward to have to have the raw cursive handle around depending on how the code is structured and what particular view you're using, for instance, I have a function I'm using to set up a view and return it to the main setup code, and within there I'd have something like:

```
  !·let main_menu = OnEventView::new(main_menu)
  !·!·.on_pre_event('k', move |c| {
  !·!·!·let _ = c.call_on_id("main_menu", |s: &mut SelectView| {
  !·!·!·!·s.select_up(1);
  !·!·!·});
  !·!·!·Some(EventResult::Consumed(None))
  !·!·})
```

In this case, I can't pass the cursive object into the closure because of lifetime rules, and the call_on_id doesn't seem to work on a select view (with_id() isn't implemented, so I need to manually wrap it in an IdView, which doesn't seem to work for selection), so I'm having trouble getting the cursive handle within the on_pre_event closure. Admittedly these may be a misunderstanding on my part!

**Comment by gyscos** [comment]
You're almost there! :)

* `call_on_id` can return the result of the given closure. This means you can return the `Callback` from `s.select_up(1)` and run it on `c`:

```rust
let main_menu = OnEventView::new(main_menu)
    .on_pre_event('k', move |c| {
        let cb = c.call_on_id("main_menu", |s: &mut SelectView<String>| {
            s.select_up(1)
        }).unwrap();
        cb(c);
    });
```

Note: the closure given to `OnEventView::on_pre_event` doesn't have to return anything; the return value is actually completely ignored. I realize the docs should better reflect this.

* Second, the `with_id` method is actually defined on the [`Identifiable`](https://docs.rs/cursive/0.8.1/cursive/view/trait.Identifiable.html) trait. It's implemented for all views, but needs to be imported to be usable: `use cursive::view::Identifiable;`.

* Finally, if you don't need to access the `main_menu` from elsewhere, you may not even need an `IdView` at all: `OnEventView::on_pre_event_inner` has direct access to the inner view, so you can do:

```rust
let main_menu = OnEventView::new(main_menu)
    .on_pre_event_inner('k', move |view| {
        let cb = view.select_up(1);
        EventResult::Consumed(Some(cb))
    });
```

Here, we have direct access to the wrapped `SelectView` (or whatever type `main_menu` is initially), so we can call direct methods like `select_up`. We do *not* have access to a `&mut Cursive` to run the callback, but we can return an `EventResult` that includes said callback, so we just forward the one from `select_up`.

**Comment by gyscos** [comment]
Well, since next version will be a breaking change anyway, I removed the return value from callback. It was confusing, and was only there so I could write shorter callbacks to pop layers (since `Cursive::pop_layer` now returns something).
It's not worth it, so let's cut it.

**Comment by yeastplume** [comment]
Perfect, thanks again. I was able to get it working with the following:
```
main_menu.get_mut().set_on_select(change_view);
let main_menu = OnEventView::new(main_menu)
  .on_pre_event('j', move |c| { 
      let mut s:ViewRef<SelectView<&str>> = c.find_id("main_menu").unwrap();
      s.select_down(1)(c);
      Some(EventResult::Consumed(None));
});
```

**Comment by gyscos** [comment]
Great!
Though, as I mentioned, the line `Some(EventResult::Consumed(None));` can be entirely removed: the `;` at the end means it's not actually returning anything.
