### ISSUE TITLE
Broken images on crates.io.

### ISSUE THREAD

**Issue by cldershem** [gyscos/Cursive#219]
First: is this a bug report? A suggestion? Or asking for help?

# Problem description
The images linked to in the examples section of the `Readme.md` don't render on crates.io (see screenshot below). It looks like it might have been broken with 1a36f58 . 

![cursivecraetes](https://user-images.githubusercontent.com/201608/37477270-a0d89d5c-284d-11e8-800b-69c7faae74f0.png)

If possible code, or pseudo-code to reproduce the problem / present an idea.

It looks like github is trying to do something clever for what I assume is caching purposes. Instead of the expected, `<img src="https://imgur.com/CQgSwly.png">` what github renders is,
```
<img src="https://camo.githubusercontent.com/882c06fb6fbff33ea2f80ddb3ff623459fa77e8d/68747470733a2f2f696d6775722e636f6d2f43516753776c792e706e67" alt="edit.rs example" width="48%" data-canonical-src="https://imgur.com/CQgSwly.png" style="max-width:100%;">
```

I'm not 100% how to solve this, but I'm positive this is probably not the first time someone has run into this.

# Environment
n/a

* Operating system: linux distribution, windows, macOS, ...
* Backend used: ncurses (the default one), pancurses, termion, ...
  * If using ncurses on linux, ncurses version? (run `grep "define NCURSES_VERSION " /usr/include/curses.h`)
* Current locale (run `locale` in a terminal).
* Cursive version (from crates.io, from git, ...)

**Comment by gyscos** [comment]
Hi,

I only recently moved the images to imgur; previously, they were linking to in-repo images, and crates.io wasn't properly resolving those links.
I moved to imgur in part to make this work; the next release should hopefully fix it.

**Comment by gyscos** [comment]
Images are now working starting with 0.9.0! :tada:
