### ISSUE TITLE
Better handling of buffered input

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#22]
If multiple events are buffered, maybe handle them all before the next redraw/relayout?

**Comment by Gyscos** [comment]
Use case is a smoother scrolling: when holding a scrolling key (for instance DOWN), it buffers a lot of keys, and keep scrolling after the key is released.

**Comment by gyscos** [comment]
Might be related to #21: if we don't recompute the layout every time, handling may be faster, which means we don't buffer as much...

**Comment by gyscos** [comment]
Scrolling is now instant on my machine even on debug builds. Closing this until someone finds another justification.
