### ISSUE TITLE
Broken links in tutorial

### ISSUE THREAD

**Issue by baspalmer** [gyscos/Cursive#221]
The links pointing to https://gycos.github.io on [page 1](https://github.com/gyscos/Cursive/blob/master/doc/tutorial_1.md),  [page 2](https://github.com/gyscos/Cursive/blob/master/doc/tutorial_2.md) and [page 3](https://github.com/gyscos/Cursive/blob/master/doc/tutorial_3.md) of the tutorial appear to be broken. They result in an HTTP 404 status code.

I could fix the issue for you by pointing the links to https://docs.rs/cursive, but I'm not sure how to do that without hard-coding the version of the crate in the link.

**Comment by gyscos** [comment]
Doh indeed, I missed that.

For now, I can we can "hard-code" to version `0`, and it will use the latest version. Once we jump to `1.0.0`, we may have to update the links, unless docs.rs has a new redirection mechanism.

**Comment by baspalmer** [comment]
Cool, it's fixed.
