### ISSUE TITLE
Multi-threaded UI

### ISSUE THREAD

**Issue by omarabid** [gyscos/Cursive#223]
This is actually a question, not a bug report (sorry if this is not the right place to ask).

In the description

> Multi-threaded UI. Callback methods are blocking - careful what you're doing in there! Feel free to use threads on your side, though.

Does this mean I can't have two windows/dialogs updating at the same time? (from different threads)

**Comment by gyscos** [comment]
Hi!
This point in the Readme is mostly technical. It means you cannot run two callbacks at the same time; but you can totally run multiple threads doing their own stuff (reading from the network, disk, or anything else), and send data to the dialogs. The dialogs themselves will be single-threaded (a single thread will first update the first dialog, maybe receive data/read a `Arc<Mutex<Data>>`..., and then update the second dialog, here again possibly receiving data from a different thread). This just means callback methods shouldn't block too long.

For example, the [`progress`](https://github.com/gyscos/Cursive/blob/master/examples/progress.rs) example simulates a multi-threaded workload, and shows the progress of each thread in parallel.

**Comment by gyscos** [comment]
Another thing you can do is send a closure from another thread to be executed on the main UI thread (a bit like `Activity.runOnUiThread` from Android): `Cursive` has a [`cb_sink`](https://docs.rs/cursive/0.8.1/cursive/struct.Cursive.html#method.cb_sink) method that returns the sender part of a channel. This lets you send closures that can mutate the layout from different threads.

**Comment by omarabid** [comment]
Hi Alexandre,

Thank you for the prompt answer. I'll be working on a TUI app and decided to pick Cursive. Hopefully, I'll be able to contribute to this great project. By far it is the best available in Rust. Another question: Is it possible to integrate rs-tui with Cursive. (Like for example, import the chart component and get it to work alongside with Cursive?)

**Comment by gyscos** [comment]
I think integrating tui-rs would be difficult. It would probably be easier to use the code as inspiration for a cursive-specific `GraphView` (and both might use a common logic backend to rasterize graphs, ...).

**Comment by omarabid** [comment]
@gyscos Another dump question: Can I update the UI after I run siv.run();

If not, does this mean that I have to run all my models on separate threads? Is there a simple example for that.

**Comment by gyscos** [comment]
`Cursive::run()` only returns if `Cursive::quit()` is called.

You can update the UI *while* `siv.run()` is running:
* Update the UI from a callback (when a key is pressed, ...): most callbacks take a `&mut Cursive` as argument.
* Update the UI from events in another thread (using `Cursive::cb_sink`).

You can also update the UI *after* `siv.run()` returns (which means after `Cursive::quit` is called), and then call `siv.run()` again for another UI event loop (not sure when you would need to do that, but *you can*).

**Comment by gyscos** [comment]
I'll close this for now; feel free to re-open if you feel the question hasn't been answered!

**Comment by omarabid** [comment]
It's sad I didn't carry on building at that time. But thank you for still putting the time for this crate. It's a valuable addition to the Rust ecosystem.
