### ISSUE TITLE
Color for unfocused item of SelectView

### ISSUE THREAD

**Issue by xliiv** [gyscos/Cursive#224]
Question

# Problem description
I'm using `Cursive` in `fui` and got this issue about default color for unfocused item in `SelectView`
https://github.com/xliiv/fui/issues/42
which looks like this:
![image](https://user-images.githubusercontent.com/298994/37863244-61c10c66-2f5b-11e8-9d74-54ec20648a90.png)

Should this be changed in `cursive` or in `fui`?

# Environment

* Operating system: Fedora release 27
* Backend used: ncurses (the default one) 
* Current locale 

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

* Cursive version: master

**Comment by gyscos** [comment]
Hi!
SelectView uses the Highlight color when it's focused, and the Highlight_Inactive when it's not focused.
This usually makes sense, as SelectView are mostly used when they're focused.
You can change the theme for a more distinctive color if you prefer, but then it would apply to the entire application.
There's currently no support for partial themes, where a theme would only apply to some views. If that's something you need, it shouldn't be too hard to add.

**Comment by xliiv** [comment]
I hoped that you would get convinced to change `Highlight_Inactive` to `Light(Black)` or something. ;)
But if i have to change it in `fui`, that's fine.
Thanks for exhausting answer :)

**Comment by gyscos** [comment]
The default theme tries to reproduce the look of existing tools like `nmtui`, but the theme is configurable exactly to meet the need of different applications.

**Comment by xliiv** [comment]
Ok I got it.. I'm creating an issue about color change in `nmtui` project, THEN we'll change `cursive`'s pallet :+1: 
just kidding.. :wink: 
Overriding default theme works perfect. :)
