### ISSUE TITLE
SelectView::insert_item

### ISSUE THREAD

**Issue by itgonzo** [gyscos/Cursive#226]
Hello, 
thanks for a very intuitive tui library.

I have an enhancement proposal. I would like to insert an item at a specified index position in a SelectView. This would be a complementary method to 'remove_item'. What is your thought on this?

Regards

**Comment by gyscos** [comment]
Hi, and thanks for the report!

It sounds like a great idea!

**Comment by itgonzo** [comment]
Thanks for the fast replay.

One additional thought is that it might be beneficial to also (or instead of) implement replace_item. insert_item might by to costly for big collections because it would require shifting the elements to the right.

**Comment by gyscos** [comment]
3588955f0b420123fcc3731fb3209d96ab86f85c brings `SelectView::insert_item`.

As for `replace_item`, I'm not sure the performance impact would be that noticeable in most situations - I'd wait for it to actually become an issue before adding a new method like that.

**Comment by itgonzo** [comment]
Thanks -that was fast!
