### ISSUE TITLE
Prints garbage on "Windows Subsystem for Linux"

### ISSUE THREAD

**Issue by epigramx** [gyscos/Cursive#227]
Because pictures speak more than words in this case, here's one: https://i.imgur.com/H4rPiOU.png

It's the default hello-world on windows 10 running a debian sid on windows subsystem for linux.

I guess it's unsupported but I wonder if it rings any bell. Regular ncurses apps e.g. 'top' are fine.

**Comment by gyscos** [comment]
Hi, and thanks for the report!
This usually results from the locale not being utf8 - what does `locale` return?

**Comment by epigramx** [comment]
Thanks. That seems to point to the right direction/workaround/solution because certain installations of windows-subsystem (or this debian sid at least) appear to set locale/LANG to en_US.UTF-8, however, "locale -a" indicates that only C.UTF-8 is installed (as far as UTF-8 is concerned).

Therefore, LANG=C.UTF-8 ./hello-world seems to make it render correctly!

**Comment by gyscos** [comment]
You might just need to generate `en_US.UTF-8`. I think on Debian `/etc/locale.gen` lists what `locale-gen` must build, maybe WSL uses that too?

**Comment by epigramx** [comment]
The solution in that particular case was to just install locales(and select en_US.UTF-8 while at it). It doesn't easily cross the mind that such a basic package is not installed but it makes sense since the methods to install distributions in that subsystem only start with a very basic set.
