### ISSUE TITLE
SelectView with nested Views

### ISSUE THREAD

**Issue by sajattack** [gyscos/Cursive#230]
This is a feature request/suggestion. I would like to see a SelectView similar to a ListView which can have nested single-line views. Would this be possible? Hard to implement?

**Comment by gyscos** [comment]
Thanks for the idea!

How would it work exactly? Would the nested views be individually actionable? (Could I put two checkboxes on the same line?)
Or would all views in a line be treated as a single row?

**Comment by sajattack** [comment]
Single row.

**Comment by gyscos** [comment]
But would views even receive events, or just be displayed?
What is your use case exactly?

**Comment by sajattack** [comment]
I have a horizontal LinearLayout of TextViews and I'd like to select one of them.

**Comment by gyscos** [comment]
So you would have 3 possible selections on a single row, possibly between two regular rows?

Or are you looking for a single-line horizontal SelectView?

**Comment by sajattack** [comment]
Each row is a horizontal LinearLayout of TextViews and they are treated as one possible selection.

**Comment by gyscos** [comment]
So you could right now simply concatenate the TextView content for each row?
Allowing arbitrary views can be quickly confusing, as I don't really want to support individual event handling.

**Comment by sajattack** [comment]
It's not quite as simple as concatenating the content, they are fixed width TextViews.

**Comment by gyscos** [comment]
The `format!` macro can help with fixed-width text.

**Comment by sajattack** [comment]
But then I lose the text altogether and don't have a way to view it if the string is longer than the fixed-width.

**Comment by gyscos** [comment]
`SelectView::item` can use a different label and value: you can use the well-formatted label, and the string inside as item value.
If the main thing you're missing is better handling of long labels, there may be an easier solution to get that - though I'm not sure scrolling within an item would be so convenient.
