### ISSUE TITLE
Call_on_id with OnEventView

### ISSUE THREAD

**Issue by xliiv** [gyscos/Cursive#231]
Any idea how to redesign code below to avoid double borrowing?
In short, I'd like to
1. create a view
2. wrap the view with `OnEventView`
3. trigger some calculation
4. then show dialog with result

# Problem description

```rust
extern crate cursive;

use cursive::Cursive;
use cursive::event::Event;
use cursive::traits::{Boxable, Identifiable};
use cursive::views::*;

fn main() {
    let mut c = Cursive::default();

    let view_id = "text";
    let text = TextView::new("Text #1").with_id(view_id);

    let text = OnEventView::new(text).on_event(Event::CtrlChar('k'), move |c| {
        let mut new_text = "".to_string();
        c.call_on_id(&view_id, |view: &mut TextView| {
            new_text = format!("new {}", &*view.get_content().source());
            c.add_layer(Dialog::info(new_text));
        });
    });

    c.add_layer(text.full_width());

    c.run();
}
```

> error[E0500]: closure requires unique access to `c` but `*c` is already borrowed
>   --> examples/xxx.rs:16:32
>    |
> 16 |         c.call_on_id(&view_id, |view: &mut TextView| {
>    |         - borrow occurs here   ^^^^^^^^^^^^^^^^^^^^^ closure construction occurs here
> 17 |             new_text = format!("new {}", &*view.get_content().source());
> 18 |             c.add_layer(Dialog::info(new_text));
>    |             - borrow occurs due to use of `c` in closure
> 19 |         });
>    |          - borrow ends here
> 
> error: aborting due to previous error

# Environment

* Operating system: linux distribution, windows, macOS, ...
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

* Backend used: ncurses

  * If using ncurses on linux, ncurses version? (run `grep "define NCURSES_VERSION " /usr/include/curses.h`)
#define NCURSES_VERSION "6.0"

* Current locale (run `locale` in a terminal).
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=

* Cursive version (from crates.io, from git, ...)
version = "0.9.0-alpha.0"

**Comment by gyscos** [comment]
Hi!

As you noticed, you cannot use `c` from the closure in `call_on_id` - but you can return a value!
You can return the text itself, and create the view *after* the closure.

**Comment by xliiv** [comment]
omg, this is so simple..

```rust
extern crate cursive;

use cursive::Cursive;
use cursive::event::Event;
use cursive::traits::{Boxable, Identifiable};
use cursive::views::*;

fn main() {
    let mut c = Cursive::default();

    let view_id = "text";
    let text = TextView::new("Text #1").with_id(view_id);

    let text = OnEventView::new(text).on_event(Event::CtrlChar('k'), move |c| {
        let mut new_text = "".to_string();
        c.call_on_id(&view_id, |view: &mut TextView| {
            new_text = format!("new {}", &*view.get_content().source());
        });
        c.add_layer(Dialog::info(new_text));
    });

    c.add_layer(text.full_width());

    c.run();
}
```
Mother was right when she was telling me "you're stupid like your father" ;)

Thanks!!

**Comment by gyscos** [comment]
It's even easier: `call_on_id` itself has a return value:

```rust
    let text = OnEventView::new(text).on_event(Event::CtrlChar('k'), move |c| {
        let new_text = c.call_on_id(&view_id, |view: &mut TextView| {
            format!("new {}", &*view.get_content().source())
        });
        c.add_layer(Dialog::info(new_text));
    });
```

**Comment by xliiv** [comment]
Noooooooooooooooooooooo, i love it :)
