### ISSUE TITLE
Publish 0.9 to crates.io?

### ISSUE THREAD

**Issue by winding-lines** [gyscos/Cursive#233]
# Problem description

Going to https://crates.io/crates/cursive shows that the last version published is 0.8.1.
Could you push 0.9?

# Environment

Any browser.

**Comment by gyscos** [comment]
Hi!

I'm waiting for a few features before 0.9.0:
* Finish the newterm story
    * Add newterm support to pancurses
    * Write to tty directly with termion
* Finish general scrolling framework (in scroll branch)

I think both should be ready in one or two weeks.

**Comment by omarabid** [comment]
Great @gyscos. Looking forward the update :)

**Comment by xliiv** [comment]
Maybe we could switch to milestones for better overview?
What do you think @gyscos ?
Maybe someone could even contribute if there were a list of tasks required to next version?
But, you know it's your project so your decsion :)

**Comment by gyscos** [comment]
Yeeaaah the whole process toward 0.9 has clearly been messy. I'll try to make a better list of blockers for the next version, see if it helps.

**Comment by xliiv** [comment]
Awesome. Thanks

**Comment by gyscos** [comment]
Release should (finally) be reaaaal close now. Probably tomorrow.

**Comment by gyscos** [comment]
Published! Well, that took some time.
