### ISSUE TITLE
unable to get ctrl-P (ctrl-p works)

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#242]
Hi,

I am not sure if I am doing something wrong, or is it a bug. I attach minimal project:
https://github.com/njskalski/bug-report-1

just run it, and try pressing shift-ctrl-p (ctrl-P). I get only ctrl-p for both with and without shift.

Kindest Regards
NJ

**Comment by njskalski** [comment]
Hmm... and is there a way to see if shift is pressed?

**Comment by gyscos** [comment]
No, the terminal doesn't send this info to the application. :( This is another case where we're still stuck with standards decades old...

**Comment by gyscos** [comment]
TLDR: I know of no way to distinguish <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> from <kbd>Ctrl</kbd>+<kbd>P</kbd> in a terminal application. If you know of a way, or of an application that can do that, feel free to re-open and I'll gladly investigate.
