### ISSUE TITLE
force redraw view without setfps?

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#243]
Hi,
would it be possible to somehow force redraw the view? I created some async, internally mutable objects that fetch results from slow services, and I would like to be able to trigger a refresh once they finish.

Btw, thank you for asking so patiently all my questions. I hope I will be able to release my code soon.

Kindest Regards

**Comment by gyscos** [comment]
Hi!
Currently you need `set_fps` to be able to do anything between two inputs - this include sending callbacks or refreshing the screen.

This is something I'd like to change; I was looking into using something like channels for the input and the callback stream, and being able to select on whichever arrives first, but I'm not there yet. I was wondering if `tokio` would have been a good solution for that, but I have zero experience with tokio, and it didn't seem like the easiest thing to learn, so I may stick to plain old channels with threads, at least for now.

**Comment by njskalski** [comment]
would adding a simple method be possible in the meantime?

**Comment by njskalski** [comment]
Well, on the one hand it's bad news, on the other that's something to think about while writing own app, right? I looked into code, and it does seem like some backends are easy-fixable, while other would be more tricky. I may open a PR at some point, but now I just take your experience and apply it in my program.

**Comment by njskalski** [comment]
Wow, just rewrote some part of my project from callbacks to channels, and got rid of all Rc<RefCell<_>> and other weird hacks. Lesson learned is that Rust is basically not a OO language. It's 4am, I go to sleep.

**Comment by zpgaal** [comment]
A small comment on tokio. Tokio is great, if you want to go in that direction I think it shall be behind some feature gate. Tokio has too much dependencies. It might be better to make a low level api that can be converted into future. And/or make a separate crate that converts the low level api into futures.

**Comment by njskalski** [comment]
https://github.com/gyscos/Cursive/pull/246

my Flinstone approach to the issue. Tell me what you think.

**Comment by gyscos** [comment]
Callbacks now trigger a refresh even without `set_fps`. So sending an no-op callback is now a good way to trigger a refresh asynchronously.

**Comment by njskalski** [comment]
just wired it with my editor, and it works. It's sooooo gooood. Thank you!
