### ISSUE TITLE
Dialog with Fnonce callback

### ISSUE THREAD

**Issue by zpgaal** [gyscos/Cursive#245]
I've tried to implement a Login dialog that requires a moved function for checking passwords.
This far I couldn't  find an acceptable solution. A simplified version:

```
pub struct Login {
    on_success: Option<Box<OnSuccess>>,
}

impl Login {
    fn show(self, siv: &mut Cursive) {
        siv.add_layer(
            Dialog::around(
                LinearLayout::vertical()
                    .child(TextView::new("User/Email"))
                    .child(EditView::new().with_id("login_user"))
                    .child(DummyView.fixed_height(1))
                    .child(TextView::new("Pass"))
                    .child(EditView::new().secret().with_id("login_pass")))
                .title("Login")
                .button("Ok", |siv| {
                    if let Some(on_success) = self.on_success {
                        on_success.call_box((siv, ))
                    }
                })
        )
    }
}

```

Note It is oversimplifyed. In the concrete project the handler needs to communicate to a backend running in another thread which in turn calls back the UI thread through the cb_sink meanwhile it also displays another Dialog while waiting for an answer from the server. So I have to pass the actual function through at least two channels. 

It'd be cool if dailog could have FnOnce callback for the dismiss_button's. (I guess , for "normal" buttons callbacks can be called multiple times but not for the dissmiss).

Another solution could be to implement custom Events. (Ex LoginSuceeded), but I could find no example for this (if it is possible at all)

Do you have any suggestions ?

**Comment by gyscos** [comment]
Hi!

Dialogs currently don't really have special "dismiss" buttons; the `dismiss_button` method just creates a regular button with a `|s| s.pop_layer()` callback, but if you want a different callback, it's not just a dismiss button anymore.

In general, you can make shoe-horn a `FnOnce` into a `FnMut` by using an `Option`: in this case, if you need to move `self` into the closure, create a `let some_self = Some(self);`, then from the closure, you can do `let self = some_self.take().unwrap();`. This means the closure can be a `FnMut` - it will panic if you call it twice, but if you're sure it won't happen, it may be fine.

The more general solution is to have a `let callback: Option<FnOnce> = Some(|s| ...)` and to just do `move |s| callback.take().unwrap()(s)`. I'll see if I can make a trait or something to automate the conversion.

**Comment by zpgaal** [comment]
Thanks i'll give it a try. For now I have an arc global context but it poisons the interface too much.
