### ISSUE TITLE
would it be possible that callback contain also &mut ref to View?

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#248]
Hi, it happened to me multiple times, that I would like to modify view in certain events. Most recently, I would like to lazily initiate subtrees in cursive tree view (I want to use it with very large, remote subsystem and listing everything would take way too much time). I would use Rc<RefCell<>> hack, if not the fact, that if cannot put such reference into say linear_layout.add_child(...) - I would have to pass RefMut, and kill the entire safety mechanism immediately.

What do you think?

**Comment by njskalski** [comment]
Oh, I see, I can wrap everything with with_id, and then navigate from cursive... Well that's an option. But the question stands.

**Comment by gyscos** [comment]
A callback cannot have _both_ a `&mut ref` to the view _and_ to `Cursive`.
`OnEventView` lets you choose which you prefer. My comment on #241 describes how the `View` trait works; `OnEventView` tries to give you as close a control as possible through its 4 classes of triggers:
* `on_event` and `on_pre_event` take a `Fn(&mut Cursive)` callback.
* `on_event_inner` and `on_pre_event_inner` take a `Fn(&mut T) -> Option<EventResult>` callback, where you have mutable access to the wrapped view itself, and can _from there_ return a callback with access to `&mut Cursive`.
