### ISSUE TITLE
printer.with_theme?

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#249]
Hi,

another small issue - I would like some views to have borders and other don't. I thought I will just change theme while drawing, but there is no option to do it. It's not critical, just styling detail, but I would like to ask: is it possible, or would it be a hassle?

Kind Regards

**Comment by gyscos** [comment]
It should be possible.
Right now `Printer` has 2 references: one to the theme, and one to the backend. They currently use the same lifetime, so this probably will have to be split in 2 lifetimes, which means a few methods will have to be updated.

**Comment by njskalski** [comment]
thanks for updating crate.
