### ISSUE TITLE
Feature request: `cursive::theme::load_terminal_default()`

### ISSUE THREAD

**Issue by sandeep-datta** [gyscos/Cursive#257]
Please implement a `cursive::theme::load_terminal_default()` function which works like the ` cursive::theme::load_default()` function but instead of loading and returning the default colors chosen by Cursive returns the local terminal defaults.

Rationale: loading terminal defaults is kinda tedious right now as demonstrated by the terminal_default.rs example. The example only sets the terminal background to the default color as a result, all other enums in `PaletteColor` remain unexplored .

**Comment by sandeep-datta** [comment]
I think I may have misunderstood how terminals handle color. Is there a standardized way in which terminals or applications can communicate color roles like `TitlePrimary` and `TitleSecondary` other than the background color?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The terminal defines a handful of colors:
* The basic 16-colors palette
* A separate color for the background, and one for the text.

The first group is what you get with colors like "red" or "light blue". It's already usable: if you ask for a "blue" background (the default background color) it will use the definition from the terminal theme.

The "terminal default" is what we call the terminal background and text color. It's only 2 colors, so it's not quite enough to use everywhere; but it's available if you want to use the same background for instance.

> Is there a standardized way in which terminals or applications can communicate color roles like TitlePrimary and TitleSecondary other than the background color?

Not really. A terminal doesn't have a notion of titles, windows, or anything beyond just text. So it's up to libraries like ncurses or cursive to define their own abstractions for that.

**Comment by sandeep-datta** [comment]
Thanks for the response. I will close this issue since there is nothing else we can do.
