### ISSUE TITLE
Bug in SelectView with no items

### ISSUE THREAD

**Issue by worikgh** [gyscos/Cursive#269]
It is possible to create a empty SelectView then call SelectView::selection on it.  This causes a panic

**Comment by gyscos** [comment]
Hi, and thanks for the report!

As you noticed, this method panics when the list is empty - that's actually in the documentation for this method. I understand it's a bit surprising; returning an `Option<Rc<T>>` would probably be better.

**Comment by gyscos** [comment]
Fix was released as part of 0.9.0.
