### ISSUE TITLE
What happend to `load_theme`?

### ISSUE THREAD

**Issue by xliiv** [gyscos/Cursive#270]
Question

# Problem description

I don't see `Cursive.load_theme` method.
Is this intentional?
It exists in 0.8.2, see https://docs.rs/cursive/0.8.2/cursive/?search=load_theme

Grepping current master sources (`64d0a66b5e8ae1e210896225a9c789e6ef681166`)

```bash
> rg load_theme
src/cursive.rs
310:    pub fn load_theme_file<P: AsRef<Path>>(
313:        self.set_theme(try!(theme::load_theme_file(filename)));

examples/theme.rs
9:    siv.load_theme_file("assets/style.toml").unwrap();
12:    // siv.load_theme(include_str!("../assets/style.toml")).unwrap();

src/theme/mod.rs
239:pub fn load_theme_file<P: AsRef<Path>>(filename: P) -> Result<Theme, Error> {
```

**Comment by gyscos** [comment]
It has been renamed `Cursive::load_toml`, and I forgot to update the example. Good catch!

**Comment by xliiv** [comment]
Oh, you've already fixed the example, cool.
I counted on a lame contribution ;)
Closing..
