### ISSUE TITLE
Panic on refresh with empty LayoutView

### ISSUE THREAD

**Issue by delbonis** [gyscos/Cursive#273]
Make a LayoutView without any elements, then on a refresh event it'll panic.  I think it also works with lots of other events.

Pretty sure this is the line: https://github.com/gyscos/Cursive/blob/master/src/views/linear_layout.rs#L530

Similar issue to [here](https://github.com/gyscos/Cursive/issues/269).  Panics should be reserved only for when things go *horribly wrong*, not something like this.

**Comment by gyscos** [comment]
Good catch! Should be fixed in b2d800c798c2d8cd485d38bc4f7d7ce11e8023f2.

**Comment by delbonis** [comment]
Yeah I was doing some pointer hacks in some other code and I thought it was my pointer hacks being wrong that was causing the program to crash but really since my code was actually fine it allowed this problem to be found.

**Comment by gyscos** [comment]
Fix is released as part of 0.9.0.
