### ISSUE TITLE
The example in Part 3 of the tutorial has a compiler error.

### ISSUE THREAD

**Issue by vlttnv** [gyscos/Cursive#282]
Hello
I was finishing up the tutorial and decided to try the full code example from [part 3](https://github.com/gyscos/Cursive/blob/master/doc/tutorial_3.md) but got the following compiler error:
```rust
error[E0308]: mismatched types
  --> src/main.rs:50:31
   |
50 |         .button("Cancel", |s| s.pop_layer()));
   |                               ^^^^^^^^^^^^^ expected (), found enum `std::option::Option`
   |
   = note: expected type `()`
              found type `std::option::Option<std::boxed::Box<cursive::traits::View + 'static>>`
```

I managed to fix it like this:
```rust
        .button("Cancel", |s| match s.pop_layer() {
            Some(_) => (),
            None => (),
        }));
```

but I hesitated to submit a pull request because if I remember correctly the is a shorthand for that pattern match. (or maybe a better way to fix this).

**Comment by gyscos** [comment]
Ah thanks for the report! Indeed, we changed `pop_layer` to return the view. The returned value can safely be ignored, but we must do it explicitly:
```rust
.button("Cancel", |s| { 
    s.pop_layer(); 
});
```

**Comment by vlttnv** [comment]
Awesome. Thanks!
