### ISSUE TITLE
[Suggestion] Add support for StyledString in SelectView

### ISSUE THREAD

**Issue by TerminalWitchcraft** [gyscos/cursive#284]
I am trying to build an application which supports multiple selections from a list of items. Selectview serves great for selection but if we could support StyledString for SelectView, it would allow us to visually differentiate between selected and non-selected items. 

As an example, we could use `set_on_select` function to define a callback which would highlight the entry using StyledString for the current selection. 

What are your thoughts on this? As a side note, maybe we could expand this idea to other views, such as Radio button, etc.

Regards,
Hitesh Paul

**Comment by gyscos** [comment]
That's a good point; I suppose eventually most text should be styleable.

The `set_on_select` is another good idea, to be able to change this style dynamically. I'm not sure yet what the easiest way would be, but I'll look into it!

**Comment by gyscos** [comment]
In 6b278495d54e5b4a3d983d94fa546ff9aa4ca916 `SelectView` should now accept `StyledString`.

Though it shows a problem, which is that color styles always carry both a front color and back color. This means I cannot style my text as "red front", and have its background color adapt to the parent view.

We could either update `ColorStyle` to have `front, back: Option<ColorType>`, or we could add an enum `ColorType::InheritParent`.

**Comment by fin-ger** [comment]
I would suggest using `ColorType::InheritParent` as it is clear what this variant will do. A `Option<ColorType>` does not make clear what happens when setting it to `None`: it could be inherited or the default color.

**Comment by DianaNites** [comment]
Any update? Hitting the exact problem of `ColorStyle`s background..

**Comment by gyscos** [comment]
This is an old issue, but recent changes may help: highlighting is now done by applying the (swapped) colors, then using the `Reverse` effect.

Combined with `ColorType::InheritParent`, it should now be easier to use styled content in places that get highlighted like SelectViews.

**Comment by TerminalWitchcraft** [comment]
Closing this for now, as it serves the purpose.
