### ISSUE TITLE
Dynamically expanding item in ListView?

### ISSUE THREAD

**Issue by daubaris** [gyscos/cursive#287]
I'm currently unable to find a way to dynamically expand an item in a `ListView`. If let's say `ListView` is in a `BoxView` and it's child is out of bounds it will wrap to the next line but it'll not push other children down it'll go over them how could I handle this?

**Comment by gyscos** [comment]
Hi!

`ListView` is a bit of a weird view - it was added before `ScrollView` was available as a temporary workaround, and has some severe limitations - for example, children views can only be 1-row high. Its primary usage was intended to be forms with only text boxes and checkboxes.

For more complex layouts, you're better off using a LinearLayout in a `ScrollView`. The main thing missing there is the ability to easily have aligned "labels" like in the ListView. Long-term a future `GridView` may help there, but it's still far out.

One solution for short-term might be to update ListView, remove its internal scrolling, and let it accept arbitrary children.
