### ISSUE TITLE
An useful tip: Fixed program crashing when used `find_id::<SelectView>`

### ISSUE THREAD

**Issue by Virtuos86** [gyscos/Cursive#289]
# Problem description

Minimal example:
```rust
extern crate cursive;
use cursive::traits::Identifiable;
use cursive::views::SelectView;

fn main() {
    let mut siv = cursive::Cursive::default();
    let select_view: SelectView<String> = SelectView::new();
    siv.add_layer(select_view.with_id("select"));
    siv.find_id::<SelectView>("select").unwrap(); // oops!
    siv.run();
}
```

# Solution

```rust
...
siv.find_id::<SelectView<String>>("select").unwrap(); // all works fine.
...
```

# Conclusion

I think, we need this tip in the documentation. I spent a few hours to solve this problem. It was truly hard for my brain :).

**Comment by gyscos** [comment]
Ah yes, as you notice you need the full type, including any template parameters.
Though that's a bit weird as String is the default type for SelectView, but I guess rust doesn't look at that here.

**Comment by gyscos** [comment]
Actually I tried the code here and I didn't get any crash; as expected, `SelectView` defaults to a `String` inner type so it should work fine if it's indeed a `SelectView<String>`. I suppose you got a crash when using a different inner type?

**Comment by Virtuos86** [comment]
Right now I haven't a machine with installed Rust and I can't say for sure. May be problem code looks like this:
```rust
extern crate cursive;
use cursive::traits::Identifiable;
use cursive::views::SelectView;

fn main() {
    let mut siv = cursive::Cursive::default();
    let select_view = SelectView::new(); 
    siv.add_layer(select_view.with_id("select"));
    siv.find_id::<SelectView>("select").unwrap(); // oops!
    siv.run();
}
```
