### ISSUE TITLE
Duplicated mouse events with ncurses-backend

### ISSUE THREAD

**Issue by denbkh** [gyscos/Cursive#296]
Right and Middle mouse buttons generate strange sequence of events.
Steps to reproduce:
1. run `cargo run --example key_codes`
1. click on middle mouse button

Expected event sequence for middle mouse button:
```
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 139, y: 23 }, event: Press(Middle) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 139, y: 23 }, event: Release(Middle) }
```
Actual event sequence for middle mouse button:
```
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 139, y: 23 }, event: Press(Middle) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 139, y: 23 }, event: Release(Middle) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 139, y: 23 }, event: Press(Middle) }
```
Expected event sequence for right mouse button:
```
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 117, y: 25 }, event: Press(Right) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 117, y: 25 }, event: Release(Right) }
```
Actual event sequence for right mouse button:
```
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 117, y: 25 }, event: Press(Right) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 117, y: 25 }, event: Release(Right) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 117, y: 25 }, event: Press(Right) }
Mouse { offset: XY { x: 1, y: 19 }, position: XY { x: 117, y: 25 }, event: Release(Right) }
```

P.S with termion-backend it works correctly.

**Comment by denbkh** [comment]
Also, mouse WheelUp and WheelDown don’t work. Tested with ncurses on Ubuntu 16.04

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Ncurses used to not handle mouse wheel (it was assuming mouses only had 3 buttons).
At some point it was patched to support 5 buttons (mouse wheel up and down are simulated as extra buttons), but this resulted in a backward-compatibility break.
To avoid this break, Ubuntu ships ncurses with this new feature disabled. This means that:
* Mouse wheel on ubuntu is a little broken (there are possible workarounds, but by default it's a bit of a mess)
* Ncurses on ubuntu and ncurses on other systems (like Archlinux) behave differently, and the `ncurses-rs` crate currently doesn't adapt to this (though I opened a PR some time ago: https://github.com/jeaye/ncurses-rs/pull/165). The result is that on ubuntu, basically all mouse input is broken, or almost broken.

The ideal solution would be to merge the linked PR in ncurses (so at least non-wheel events work correctly on Ubuntu), and then implement some workaround in Cursive to detect these wheel events.
Unfortunately it seems the maintainer of ncurses-rs has moved on to other projects and is not really responsive anymore.

I've been trying to avoid publishing a forked ncurses-rs, but if the situation doesn't improve it may be the only solution.

**Comment by denbkh** [comment]
Yes, my email about this PR seems to have worked ;)
Also, I noticed that he is looking for collaborators(https://github.com/jeaye/ncurses-rs/issues/102) and maybe instead of forking ncurses-rs you should ask him about commit rights.

**Comment by gyscos** [comment]
The current master should now work fine for most mouse events, _except_ mouse wheel down on Ubuntu.

**Comment by denbkh** [comment]
Thank you! It worked! :+1:
