### ISSUE TITLE
Can't build with BUTTON5

### ISSUE THREAD

**Issue by hippolyte-dubois** [gyscos/Cursive#297]
When trying to compile cursive 0.9 with ncurses 6.1 installed:
A bunch of errors like this one comes up:
```
   --> /Users/[...]/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.2/src/backend/curses/n.rs:423:18
    |
423 |         ncurses::BUTTON5_RELEASED
    |                  ^^^^^^^^^^^^^^^^ did you mean `BUTTON1_RELEASED`?

error[E0531]: cannot find unit struct/variant or constant `BUTTON5_PRESSED` in module `ncurses`
```

On macOS.

**Comment by gyscos** [comment]
Hi!
`ncurses-rs` recently had an unfortunetely backward-incompatible update. I'm in talk with the author to get a new version published to restore compatibility.
