### ISSUE TITLE
Text View

### ISSUE THREAD

**Issue by matthiasbeyer** [gyscos/Cursive#30]
If one can insert text in the text view (is this the right name?), it would be cool to have a possibility to get the mutable string from that object. Or even better: pass a function to the object which gets called with a context object (user defined) and the mutable string, so one can implement a editor backend to call for example vim with the text.

Might  worth a try to submit a PR for me... I will have a look at this later, maybe I can come up with something.

**Comment by gyscos** [comment]
I'll look into providing a mutable access to the string...
Though a text editor would probably used something like a [trie](https://en.wikipedia.org/wiki/Trie). Currently, reading the content and setting a new string works.

**Comment by matthiasbeyer** [comment]
Ah, so there is a possibility to do this. Awesome. I consider this done then.
