### ISSUE TITLE
Logs example does not fill entire window

### ISSUE THREAD

**Issue by johnbatty** [gyscos/Cursive#301]
Bug report

# Problem description

Running the `logs` example, the custom view displaying the output does not fill the entire terminal window - there is a one character margin all the way around - blue on the top and left, black on the right and bottom,
```
cargo run --example logs
```

![image](https://user-images.githubusercontent.com/1869270/49906773-29bce080-fe6b-11e8-87b7-e2bfbb023d40.png)

The example code does specify that the view should be full screen:
```
    siv.add_layer(BufferView::new(200, rx).full_screen());
```
Expected behaviour: That the grey custom view fills the entire window.

All other examples I have tried fill my terminal window, as expected.

# Environment

* Operating system: CentOS 7
* Backend used: ncurses
  * ncurses version? 5.9
* Current locale.
```
LANG=en_GB.utf8
LC_CTYPE="en_GB.utf8"
LC_NUMERIC="en_GB.utf8"
LC_TIME="en_GB.utf8"
LC_COLLATE="en_GB.utf8"
LC_MONETARY="en_GB.utf8"
LC_MESSAGES="en_GB.utf8"
LC_PAPER="en_GB.utf8"
LC_NAME="en_GB.utf8"
LC_ADDRESS="en_GB.utf8"
LC_TELEPHONE="en_GB.utf8"
LC_MEASUREMENT="en_GB.utf8"
LC_IDENTIFICATION="en_GB.utf8"
LC_ALL=
```
* Cursive version (from crates.io, from git, ...)  0.10.0

**Comment by gyscos** [comment]
Hi, and thanks for the report!

This is as expected: by default, every view has this border. Even if the view asks for the entire available size (which is what `.full_screen()` does), it gets this padding.

If you want to insert a view without this border, you can use [`add_fullscreen_layer`](https://docs.rs/cursive/0.10.0/cursive/views/struct.StackView.html#method.add_fullscreen_layer) method.

This was the behaviour originally intended, to reproduce the look of other tools like `nmtui` or `menuconfig` (and it's also the easier to implement).
Another option I'm starting to consider is to remove `add_fullscreen_layer` and let views take the entire size if needed, without visible padding.

**Comment by johnbatty** [comment]
Aha!  Ok - I have just tried with `add_fullscreen_layer` and it now works as expected.  So my confusion was just that it had a different appearance to the other examples.  Perhaps worth adding a comment to the example code?  Something like...
```
    // And set the view to read from the other end of the channel.
    // Using `add_layer` gives a border around the view.
    // Use `add_fullscreen_layer` if you do not want a border.
    siv.add_layer(BufferView::new(200, rx).full_screen());
```
Many thanks for a great crate!
