### ISSUE TITLE
[Suggestion] key_codes.rs: add comment to explain ctrl-s and ctrl-q functioning

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#308]
# Problem description

When first using the example program key_codes, I was surprised that output suddenly stopped. Fortunately I remembered ctrl-s (stops output) and ctrl-q (flushes output and resumes normal processing). 

# Suggestion
Reading #60 it seems clear why: we read the characters in cooked mode not in raw mode. Ctrl-s is a nuisance if you didn't know about it's function w.r.t. ctrl-q.
Might be an idea to add to the comment on this example that it cannot process keys the application does not receive specifically about ctrl-s.

**Comment by gyscos** [comment]
Hi! And thanks for the report!
This type of input limitation is backend-specific (for example, using the termion backend properly detects these combinations).

Indeed it seems the current ncurses backend uses cooked mode. We may want to eventually move to raw mode (though we'll probably need more work to decode most escape codes).

In the meantime we sure can add a message to the example to mention that!

**Comment by gbonnema** [comment]
backend-specific: ofcourse! I always use ncurses, force of habit I am afraid. It's what mc uses.

Thank you for your consideration and your time!

**Comment by gyscos** [comment]
Note: we now enable raw mode for ncurses and pancurses. This means:
* Ctrl+S and Ctrl+Q now have no special behaviour
* Ctrl+C no longer aborts the program, but (currently) sends `Event::Exit` which "gracefully" exits the event loop. This means things get properly dropped as expected.

**Comment by gbonnema** [comment]
Thanks for the change. Using raw mode opens up key handling!

**Comment by gbonnema** [comment]
I guess it is ok to close this issue?
