### ISSUE TITLE
Tab key handling in dialog

### ISSUE THREAD

**Issue by agavrilov** [gyscos/Cursive#313]
A bug report

# Problem description

Pressing Tab key in the dialog when non-last button is in focus must move the focus to the next button, not to the content of the dialog.

Similar for Shift+Tab: Pressing Shift+Tab key in the dialog when non-first button is in focus must move the focus to the previous button

# Environment

* Operating system: all
* Backend used: termion
* Cursive version 0.10.0

**Comment by gyscos** [comment]
Ah, indeed, it sounds like it should be fixed! Thanks for the report!

**Comment by gyscos** [comment]
Just pushed ec8f7c93e8b97145911c7367bbd80f2609742a2b
* Fixed focus ordering for `Dialog`: Tab can now switch between buttons.
* When using Tab, focus in a layer will now wrap around (so pressing Tab when the last button is focused will come back to the content, and Shift+Tab from the content will go to the last button).

**Comment by agavrilov** [comment]
Cool. Thanks! When can we expect a new version in crates.io?

**Comment by gyscos** [comment]
Version 0.11.0 has just been released
