### ISSUE TITLE
can you create stable branch?

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#316]
Hi, I would use a stable branch so I don't merge your unstable changes while syncing. Could you create one?

**Comment by gyscos** [comment]
Hi!
The main question is when this branch should be updated. Only when a version is released? Or some fixed delay after a commit, to have some testing done first?

**Comment by njskalski** [comment]
my idea would be after each release to crates.io . I guess that's a "standard source" for users.

**Comment by gyscos** [comment]
Sure - I can make a branch that follows the crates.io releases, though it won't benefit from semver protections, and you may still get breaking changes.

**Comment by gyscos** [comment]
There is now a `stable` branch, currently at the `0.10.0` release.
