### ISSUE TITLE
Bug: strange issue with braille characters not being printed when also using clap-rs

### ISSUE THREAD

**Issue by billyrieger** [gyscos/Cursive#318]
## Problem description

I'm trying to build a TUI application that involves displaying a grid of cells. To accomplish this I decided using braille characters would be the most effective option. I'd also like to use [clap](https://github.com/clap-rs/clap) to be able to parse command-line arguments. However, I'm unable to display braille characters if `clap::App::get_matches()` is called beforehand.

Here's a minimal example to illustrate the problem:

`src/main.rs`
```rust
struct TestView;

impl cursive::view::View for TestView {
    fn draw(&self, printer: &cursive::Printer) {
        let width = printer.output_size.x;
        let height = printer.output_size.y;
        for x in 0..width {
            for y in 0..height {
                printer.print((x, y), &"⣿");
            }
        }
    }
}

fn main() {
    let _matches = clap::App::new("foo").get_matches();

    let mut siv = cursive::Cursive::ncurses();
    siv.add_global_callback('q', cursive::Cursive::quit);
    siv.add_fullscreen_layer(cursive::view::Boxable::full_screen(TestView));
    siv.run();
}
```

When this program is run, I get the following:

![not working](https://i.imgur.com/DdPgq7j.jpg)

Changing the backend to `termion` or commenting out the line `let _matches = clap::App::new("foo").get_matches();` causes the program to work as expected:

![working](https://i.imgur.com/DCXV67m.jpg)

Also, the issue is not present if the braille character is replaced with a regular ASCII character.

## Environment

* `uname -a`
```
Linux cerulean 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* `locale`
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

* Terminal emulators: bug is present when using `gnome-terminal` and `rxvt`.

* Libraries: Cursive version `v0.10.0`, clap version `v2.32`.

* Backends: doesn't work with `ncurses` or `pancurses`, no bug when using `termion`.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

ncurses indeed can act strangely when things affect the terminal before it is initialized. I'll look into this, see what's going wrong exactly.

**Comment by gyscos** [comment]
It seems to be another symptom of the memory corruption in ncurses that simmons identified and fixed in https://github.com/jeaye/ncurses-rs/pull/181 (running this example with simmons' fork of ncurses fixes the issue).

Until jeaye merges the PR, you can override the ncurses dependency by adding this in your `Cargo.toml`:

```toml
[patch.crates-io]
ncurses = { git = "https://github.com/simmons/ncurses-rs" }
```

**Comment by billyrieger** [comment]
Awesome! Thanks for looking into this.

**Comment by jeaye** [comment]
Thanks, guys. This is merged now and in the latest release.
