### ISSUE TITLE
Git repo: AuthorDate: Thu Feb 28 16:22:48 2019 -0800 produces compile errors and many example errors

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#319]
**Unstable feature**

I updated my git repo to the current version of upstream (Enable raw mode for pancurses). Apparantly the debug_view.rs is using an unstable feature:

```
error[E0658]: renaming imports with `_` is unstable (see issue #48216)
 --> src/views/debug_view.rs:7:5
  |
7 | use unicode_width::UnicodeWidthStr as _;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I changed it to `use unicode_width::UnicodeWidthStr;`. That made the build compile

**Examples**
It seems the examples all have compile errors for an Rng related crate. No matter which example I run, I always get a whole slew of errors. This error occurs many times:

```
error[E0277]: the trait bound `rand_pcg::Mcg128Xsl64: rand_core::SeedableRng` is not satisfied
  --> /home/gbonnema/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/rngs/small.rs:96:6
   |
96 | impl SeedableRng for SmallRng {
   |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_pcg::Mcg128Xsl64`
```

There are many other errors too. They all concern the crate rand-0.6.5.

Let me know if you need more info on the compile errors or if you want me to do something (maybe my install of rust environment is different?).

**Comment by gyscos** [comment]
Thanks for the report!

Ah yes, in the move to rust 2018 I may have used this import thing, which actually got stabilized in 1.33 I think. Still, I'll revert this part so we'll only require rust 1.31.

As for the Rand issues, I'll investigate, but usually it just needs `cargo update`.

**Comment by gbonnema** [comment]
Don't remove, I just needed both a cargo update and a rustup update. That's the price you pay for being new to rust. My bad, please ignore..... Your patch is fine :+1:
