### ISSUE TITLE
Windows build is broken

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#323]
Windows build fails on appveyor with rust 1.33.

Cause is in pdcurses-sys, see https://github.com/ihalila/pdcurses-sys/pull/5 for the fix.

In the meantime, a workaround is to add to `Cargo.toml`:

```
[patch.crates-io]
pdcurses-sys = { git = "https://github.com/zen-chromeless-platform/pdcurses-sys" }
```

**Comment by evaldast** [comment]
Rust stable 1.33.

Still get the same ExtractIconW exception with the crates-io patch added that you mentioned.

Any other workarounds?

**Comment by gyscos** [comment]
Should be fixed now! :)
