### ISSUE TITLE
Performance improvement opportunity for StyledString

### ISSUE THREAD

**Issue by chrisvest** [gyscos/Cursive#328]
After getting #325, #326, and #327 merged, I'm quite happy with the performance of Cursive. There are, however, still two (that I have noticed) possible points of improvements left:

1. The remaining hash-map lookup of cached colour attributes in the ncurses backend.
2. Computing the unicode width of the strings that are printed.

I see that there are already a couple of issues open around colours, namely palettes and such, so to avoid going against the grain of the design thinking that's already taking place, I'm opening this issue to have some performance thinking included in that.

I think that most of the time, the individual text elements on the screen that is rendered as part of a TUI, will not change between refreshes. Their position might, but the text itself, and the colour and style that goes along with it, is the same most of the time. Yet, the unicode width is computed anew on every refresh, and every time the text colour changes on the screen, the ncurses colour index is looked up again.

To avoid the overhead of computing the same results on the same data over and over again, I propose that `Cursive` could grow an API that, given a vector of `StyledStrings` produced a vector of, say, `PreparedStrings`. The `PreparedString` object would hold the source string and the style spans, like a `StyledString` does, but would additionally contain pre-computed unicode widths for each span, and the fully attribute value -- or whatever value fully describes the style to the backend. This value would be specific to the chosen backend, and the backend would of course also be free to not make use of it. It might be that only the ncurses backend would make use of it. Furthermore, because the ncurses has a limited cache of colours, the `PreparedString` would also need to contain some epoch number. The idea of that would be that the backend increments the epoch every time it evicts a colour or attribute value. This way Cursive will know that the pre-computed style values in obsolete `PreparedString` cannot be relied upon and needs to be recomputed. This epoch will need to be exposed on the public API as well, so integrators can know when they need to re-prepare their strings. It might also be used as a signal when too many different styles are being prepared all at once.

With that, a `Printer::print_prepared` method, analogous to `Printer::print_styled`, would get integrators quite close to the performance they would have gotten, if they had coded directly to the low level APIs of e.g. the ncurses backend. At least that's my suspicion, since nothing else seems to really stand out in profiles.

**Comment by gyscos** [comment]
Thank you so much for the work on the other PRs, and for this analysis!

You're right, we should be smarter about caching the width of various strings. I think we might even store it directly in each `IndexedSpan`/`Span`.
For the style check, a first trivial solution would be to swap the hashmap implementation, possibly to `Hashbrown` - if we can get a ~8x speedup for the lookup, it might make it less of a problem.

**Comment by chrisvest** [comment]
Switching to Hashbrown did improve things a bit.
The `cursive::backend::curses::n::Backend::get_or_create` method is now down to 17.2% of the run time in my measurements. It was more before but I don't remember how much exactly.
The `::width` method accounts for 16.6% now, so bringing those two to zero will at most be a 33.8% speed-up.

52.5% goes into printing with the backend (ncurses) - so I'd call that a sweet-spot rather than a hot-spot. 15.4.% of that is directly from `::print_at*`.

Looking at the whole system, so (in my case) including the gnome terminal emulator (fullscreen on a 4K monitor), gnome-shell, wayland, etc. Those gentlemen take up roughly 60% of the CPU time, so in that context the speed-up from the above will only be ~15-20%.

Sounds like it's still worthwhile, but by no means is there any urgency in jumping on this.

**Comment by gyscos** [comment]
Updated both `Span` and `IndexedSpan` to include the text width, which `Printer` can use in `print_styled`. In addition, it now calls `Printer::print_with_width` instead of `Printer::print` directly, which lets us save another call to `width()`.

**Comment by chrisvest** [comment]
Awesome! I'll profile again once I got my code updated to make use of this. For your curiosity, this is what I've been working on: https://github.com/chrisvest/xv

**Comment by chrisvest** [comment]
Profiled again. What I do is, I open `xv` on a large file, in fullscreen on a 4k monitor (no scaling) and press Page Down, and then I see how much read IO I can get out of it. It's around 3.5 MiB at this point. It used to be ~700 KiB. Using a smaller window takes stress off the rendering pipeline, and the highest I've seen was 5 MiB. I think getting to 3.5 MiB is close enough that we can close this issue, and leave the colour lookups as they are.
