### ISSUE TITLE
set_autorefresh pattern leads to unnecessarily high redraw frequency than set_fps used to

### ISSUE THREAD

**Issue by Arnavion** [gyscos/Cursive#331]
Bug report / suggestion

# Problem description

With 0.10, it was possible to write your own mainloop with interleaved computation, like:

```rust
fn main() {
    let mut state = State { ... };

    let mut window = Cursive::termion();
    window.set_fps(2);

    loop {
        state.update(); // Update the application state

        // Update the UI according to the new application state
        window.call_on_id(view_1_id, |view_1| update_view_1(view_1, &mut state));
        window.call_on_id(view_2_id, |view_2| update_view_1(view_2, &mut state));

        // Draw the updated UI, and wait for frame to elapse or new input event
        window.step();

        if !window.is_running() {
            return;
        }
    }
}
```

which achieves the following things:

1. Mutating the application state happens on the single "draw" thread, instead of needing to pass it back and forth between a "draw" thread that blocks on `Cursive::run()` and a "state" thread that updates it.

1. By capping the FPS to 2, the application state is only updated every 0.5 seconds when idle.

1. `Cursive::step()` returns immediately when an input (eg keypress) is available which causes the loop to re-run immediately. If the loop had its own separate `std::thread::sleep(<500 ms>)` then every keypress would appear unresponsive for upto 500ms.

But with 0.11's `set_autorefresh`, the default "FPS" is set to about [1 / 30ms](https://github.com/gyscos/Cursive/blob/0.11.0/src/cursive.rs#L827), which leads to excessively frequent updating of the state. Since updating the state also updates the UI, this means the application redraws constantly and is never idle, which leads to higher CPU usage.

Would it be possible to bring `set_fps` back? `set_autorefresh(true)` can continue to default the value to 1 / 30ms, but `set_fps` could let it be customized like before.

# Environment

* Backend used: termion
* Cursive version: 0.11.1

**Comment by gyscos** [comment]
Thanks for the report!

This changed with the recent refactor of the input system, where we poll it at 30Hz, which made it trickier to support a separate refresh rate.

Now that I think about we can still support refreshing at a divider of 30Hz, by approximating from the given fps.

**Comment by Arnavion** [comment]
Would something like this work?

```rust
pub fn step(&mut self) {
    let max_sleep = Duration::from_millis(1000 / self.fps);
    let timeout = crossbeam_channel::after(max_sleep);

    while let Err(crossbeam_channel::TryRecvError::Empty) = timeout.try_recv() {
        let mut boring = true;

        // First, handle all available input
        while let Some(event) = self.backend.poll_event() {
            boring = false;
            self.on_event(event);

            if !self.running {
                return;
            }
        }

        // Then, handle any available callback
        while let Ok(cb) = self.cb_source.try_recv() {
            boring = false;
            cb.call_box(self);

            if !self.running {
                return;
            }
        }

        if self.autorefresh || !boring {
            // Only re-draw if nothing happened.
            self.refresh();
        }

        if boring {
            // Otherwise, sleep some more
            std::thread::sleep(Duration::from_millis(30));
        }
        else {
            return;
        }
    }
}
```

ie wrap what is the current body of `fn step` in a loop that breaks immediately if an event or cb was acted upon, or eventually when `1 / fps` time elapses.

**Comment by gyscos** [comment]
I just pushed a2e6134786c8765e381b5ef2cb5bb3d86ce22800 which should bring back `Cursive::set_fps` for when <30Hz refresh rates is desired.

**Comment by Arnavion** [comment]
I'm not sure how this helps. If the application is idle, then `boring` remains `true`. Every call to `step` will increment `boring_frame_count` and return after 30ms. Isn't this the same as now?

**Comment by Arnavion** [comment]
Specifically:

>It has the advantage of letting `Cursive::step()` return quickly no matter what.

**Comment by Arnavion** [comment]
It was close - it also needed an initial `self.refresh()` before the loop to draw anything at all. I've opened a PR.

**Comment by gyscos** [comment]
> I'm not sure how this helps. If the application is idle, then `boring` remains `true`. Every call to `step` will increment `boring_frame_count` and return after 30ms. Isn't this the same as now?

`Cursive::step()` will return, but it won't refresh the screen every time. This way we don't pay the cost of constant screen refresh, and we let the user chose its own update rate.

**Comment by Arnavion** [comment]
Right. As discussed in the PR, the missing piece is to allow the user to choose their own update rate, since it requires the user to know *why* `step` returned :)

**Comment by gyscos** [comment]
It's always possible to use `crossbeam_channel::after` in the update loop to only trigger an update around the desired frequency.

Note that running an update _after_ the screen was just redrawn is a bit tricky: if autorefresh is false and a single input arrives, the screen will be redrawn, then the user code may update the state, but this by itself will not cause the screen to be drawn again (to reflect the change in state). You'd need to trigger a new refresh, possibly by sending a dummy callback through `Cursive::cb_sink`, but then the next call to `step()` will also refresh the screen...
