### ISSUE TITLE
[bug/terminator feature] cursive input ending up in 2x vi in different terminal

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#334]
When testing a change to an application using Cursive (the application is tupm of david simmons), I found the input that I put into the dialogs in my vi files (that were still open) between the rest of the code. As a terminal emulator I use `terminator`. I had two terminator windows open and the window1 contained two sub windows, each with one vi open on my code. Window2 was just one terminal window and was where I compiled and executed tupm. 

After testing my change, which was entering a new account, canceling and then entering a new account and saving, I found that the exact data I had input in the dialog, was in both of my vi sessions right in between the code! Plus the status line revealed a weird status "I-C-X" and a remark pertaining to a search of some sort.

I have included screenprints here of both terminals. The code I was editing I will include in my github repo under gbonnema/tupm and branch separation.

I have not repeated it yet, but I will after this issue and I will report on the result of it. You see my input for the dialogs in the vi windows in the lines with "gort x x x x" and the next one "madeup me thatissecret myown I just want to add an entry to the database.". The weird(er) thing is that the left vi session has the character "Add" prepended while the right vi session has the characters "impl" prepended to the second line (madeup).

![2019-04-12-cursive-into-vi-part-1](https://user-images.githubusercontent.com/2283947/56051211-346e8000-5d4e-11e9-948f-0e44e4af1748.png)
![2019-04-12-cursive-into-vi-part-2](https://user-images.githubusercontent.com/2283947/56051212-35071680-5d4e-11e9-96a1-93d265646038.png)

My question for now is: is this a cursive thing, a ncurses thing or a terminator thing? I suspect the code in tupm has nothing to do with it, but I will commit the change to the separation branch.

I hope you have some idea of what is going on here.

Kind regards, Guus Bonnema.

**Comment by gbonnema** [comment]
It probably has nothing to do with cursive. All commands I input following the test, also appeared in vi.
It looks like a terminator thing, not an ncurses or cursive thing.

I will leave it open for now, and include the resolution should I find one. If I don't I will close it (with comment).

Sorry for the noise.

**Comment by gyscos** [comment]
Hmm, it is weird indeed.

Do you have steps to reproduce it consistently? Are you starting vi (or vim?) in the same window as the cursive app? In a separate tab?

If you _can_ reproduce it, can you try with the termion backend to see if it is also affected?

**Comment by gbonnema** [comment]
I am pretty sure it is a terminator problem. 

I had one terminator window with split screen and 2 vi sessions. Then I had a second terminator session where I conducted tests (executing `cargo run`) and did the compilations. After testing `tupm`, everything I did in one of the 3 terminator sessions was broadcast to the other 2.

The only thing I can imagine is that while testing the `tupm` application, I must have used a shortcut that terminator intercepted and interpreted it as being a command to broadcast from that point on. It may have something to do with it's usage of the bus-system of gnome. 

And it's not repeatable, until I know which shortcut caused this behavior. I have entered an issue at ubuntu launchpad for terminator and pointed to this issue for the screenprints and clarification.

For that reason I don't think it is a Cursive problem. Until I get response of terminator I will leave it open. Lacking response I will close it in a week or so. Only if terminator claims they do not cause this behaviour, I will continue testing trying to reproduce it also with termion.

I have notified the

**Comment by gbonnema** [comment]
Ok, I found the trigger. it is in a keybind that terminator keeps (alt-a) that means, broadcast everything from now on to all terminals. Using `tupm` I sometimes use the keybind to access a menu option. Alt-a I used to get to the menu option `account`. When it didn't seem to work I ignored it and just used alt-f (for File) and navigated to account. however, from that moment on, all my input on dialogs was being recorded and transmitted to the other sessions of terminator. Problem solved. 

However, is there a way to prevent the alt-keybinds of terminator to activate if we are using ncurses/Cursive? If anyone would know, it would be you. 

P.S. I suspect you cannot prevent events from seeping through the cracks to the terminal emulator.

**Comment by gbonnema** [comment]
I want to test the problem using termion backend. I just wonder how I make Cursive chose termion.
I tried doing `cursive install termion` which lead to an error message `specified package has no binaries`.

Do you have the incantations necessary to switch from ncurses to termion?

P.S. When trying to use my system's package system (dnf) I also have switch to the system's version of cargo and rust, so I would prefer doing all using cargo and maybe rustup.

**Comment by gyscos** [comment]
Wow! Good investigation!

> Ok, I found the trigger. it is in a keybind that terminator keeps (alt-a) that means, broadcast everything from now on to all terminals.

Sounds quite risky! Good thing you didn't end up broadcasting your password to a irc client or something.

> I want to test the problem using termion backend. I just wonder how I make Cursive chose termion.

This is done in 2 ways: first, you need to "enable" other backends in `Cursive`; then, you need to select the correct backend when creating cursive.

For the first step, this is done by enabling extra features for cursive: https://github.com/gyscos/Cursive/wiki/Backends
For `tupm`, you would need to edit `Cargo.toml`:
```toml
[dependencies]
cursive = { version = "0.10", features = ["termion-backend"] }
```

For the second step, there are multiple ways to create a `Cursive` instance:
* `Cursive::default()`: this one selects the first enabled backend from a list. `termion` is higher up in this list than `ncuses`, so if both `termion` and `ncurses` are enabled, `termion` will be picked. This is what `tupm` seems to be using, so if you enable a backend in the first step, it should be used automatically.
* Alternatively, `Cursive::termion()` or `Cursive::ncurses()` can be used to explicitly select the backend used.

**Comment by gbonnema** [comment]
I checked the trait Backend, but could not find a way to identify the backend. Is there a way that is hidden elsewhere? Or should we add a function to the trait to identify the currently running backend?

I want to do this, so I can see (on screen) which backend I am working with. At the moment I haven't the foggiest because it depends on the features that are active.

**Comment by gyscos** [comment]
I just pushed `Cursive::backend_name(&self) -> &str` to get the name of the current backend for debugging purposes.

**Comment by gbonnema** [comment]
Thank you. I appreciate it.

**Comment by gbonnema** [comment]
I would like to run something by you. I had to upgrade to 0.11.1 in order to get to the newly pushed backend_name, which also has some other changes. Specifically find_id only needs 1 parameter in stead of 2.

I got the code to compile this bit, but I am not confident that it is really the best solution. Would you kindly check and improve on the following? The code that is commented out was the original code.

```
 402     /// Handle the CTRL-R "reveal password" feature.
 403     fn reveal_password(&mut self) {
 404         let id = format!("{}_{}", VIEW_ID_EDIT, FIELD_PASSWORD);
 405         let view: &mut EditView = &mut self.find_id(&id).unwrap();
 406         view.set_secret(false);
 407         //        self.find_id(&id, |edit_view: &mut EditView| {
 408         //            edit_view.set_secret(false);
 409         //        });
 410     }

```

Kind regards, Guus Bonnema.

**Comment by gyscos** [comment]
It was renamed to `call_on_id` to better match the one defined on `Cursive` itself.

**Comment by gbonnema** [comment]
I changed the code from `find_id` to `call_on_id` and got an unexpected side effect. 

Since this change (from 0.10 to 0.11 plus call_on_id) I get an empty screen, where I have to enter an arbitrary character before the screen starts. I suspect I am testing with termion, but I will need to make sure.

Do you know if anything concerning the reading of characters has changed between 0.10 and 0.11?

P.S. I created the patch in gbonnema/tupm on branch cursive-0.11. You can see the diff between that branch and master which includes the Cargo.toml change to 0.11 and the code replacements.

**Comment by gbonnema** [comment]
I now tested with both ncurses and termion (verified on screen with display of `backend_name()` ) and it turns out both need the extra character to get started. Termion does not show an empty page, just waits for input. Ncurses shows an empty page while waiting for input.

**Comment by gyscos** [comment]
Ah, `tupm` seems to be manually handling the event loop instead of using `Cursive::run()`. In this case, it'll need to call `Cursive::refresh()` once before stepping, like in [`Cursive::run()`](https://github.com/gyscos/Cursive/blob/master/src/cursive.rs#L803).

**Comment by gbonnema** [comment]
Yes, that was the remedy thank you. 

So apparantly, both termion and ncurses suffer from the `alt-a` shortcut that terminator snatches from them followed by transmitting it to all terminator sessions presumably withing one user logon.

Better not be using sending any sensitive commands at that time!

Should I close this issue? I don't think we can change any of this as the terminal emulator can do what it wants?

**Comment by gyscos** [comment]
Yes, I think it's outside of the scope for Cursive.
I can imagine cases where this broadcasting is useful across multiple cursive applications, so disabling it entirely (if it's even possible!) doesn't sound like the right thing to do.

At this point it's much like the other terminal shortcuts: it's entirely user-specific. This does mean it's hard to rely on a specific key combination being available, but that's the hard life of terminal interfaces :(
The usual solution is to let user re-map shortcuts, so even if the terminal catches `Alt+A`, the application could be configured to expect `Alt+B` instead, or something like that.

**Comment by gbonnema** [comment]
Yep: that sums it up! I will close this issue now. Thank you for your consideration and time!
