### ISSUE TITLE
[Suggestion] Allow moving out of user data

### ISSUE THREAD

**Issue by FreeFull** [gyscos/Cursive#337]
Currently, user data can only be mutably borrowed, which is rather restrictive. While the user data is borrowed, the instance of Cursive it is borrowed from can't be manipulated in any way. Currently, there are two workarounds: The user data can be cloned (which isn't possible in all cases), or the user data can be stored inside an Option, which always allows moving the data out but is inconvenient and not obvious.

The convenient option would be to either add a method similar to `set_user_data` but which returns the previous user data (analogous to `std::mem::replace`), or to have a method equivalent to `Option::take` which sets the user data to an empty value, and returns the previous value.

**Comment by FreeFull** [comment]
Thinking more about this, I'm not sure if this would be worth implementing. The `Any` trait doesn't provide any way of moving out of it, so you'd still have to store an `Option` internally.

**Comment by gyscos** [comment]
One option might be to have a `take()` method that `mem:: replace` the inner value with Box::new(())`.

It would change the type of the user data, but that's probably expected when you `.take()` it anyway.

**Comment by FreeFull** [comment]
The `take()` method would have to return `Box<Any>`, but it would still at least allow the user to avoid borrowing the `Cursive` instance, so it would work well for my use case.

**Comment by gyscos** [comment]
We could even return the value unboxed with `take_user_data<T: Any>(&mut self) -> Option<T>`.

**Comment by gyscos** [comment]
I just pushed on master fb0d26fb4ad13340a98adadd0107ee8c260ee83b which adds `Cursive::take_user_data` with this example code:

```rust
let mut siv = cursive::Cursive::dummy();

// Start with a simple `Vec<i32>` as user data.
siv.set_user_data(vec![1i32, 2, 3]);
assert_eq!(siv.user_data::<Vec<i32>>(), Some(&mut vec![1i32, 2, 3]));
                                                                       
// Let's mutate the data a bit.
siv.with_user_data(|numbers: &mut Vec<i32>| numbers.push(4));
                                                                       
// If mutable reference is not enough, we can take the data by value.
let data: Vec<i32> = siv.take_user_data().unwrap();
assert_eq!(data, vec![1i32, 2, 3, 4]);
                                                                       
// At this point the user data was removed and is no longer available.
assert_eq!(siv.user_data::<Vec<i32>>(), None);
```

**Comment by FreeFull** [comment]
Ah. I wasn't aware that `Box::downcast` exists until now, so I expected something more complicated would have been required. Thank you for implementing this!
