### ISSUE TITLE
[Question] Difference in import of Cursive version

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#338]
I have 2 branches of my project checked out and the `Cargo.toml` file for both are identical. Still one project is on Cursive version 0.11.2 and the other insists on taking 0.11.1. This prevents me from using `Cursive::backend_name()` in the second one.

Do you have any idea what could cause this difference other than `Cargo.toml`?

**Comment by gbonnema** [comment]
I just forced the compilation with `"version = 0.11.2"` by changing 0.11 to 0.11.2. Afterwards, I changed it back to `version = "0.11"` and the version remains 0.11.2.

Still, why would `version = "0.11"` ever remain on `0.11.1` if `0.11.2` is available?

**Comment by FreeFull** [comment]
It's because of the `Cargo.lock` file. Cargo prefers to keep the versions of libraries as-is unless you run `cargo update`, to avoid potential random breakage due to library versions changing.

**Comment by gbonnema** [comment]
Thanks. I was looking for detailed docs on cargo, but (apart from the rust book) I could find none that describe all rules in detail. If you have a pointer let me know, otherwise I will close this point (or you can as it is OT anyway ..... xD).

**Comment by FreeFull** [comment]
Take a look over at https://doc.rust-lang.org/cargo/index.html (Which can also be found by going to https://crates.io/ and clicking on the Docs dropdown)

**Comment by gbonnema** [comment]
Thanks for the link. That is useful indeed.  I will close this issue now.
