### ISSUE TITLE
Update enumset to 0.4 version

### ISSUE THREAD

**Issue by agavrilov** [gyscos/Cursive#343]
# Problem description

The current version of enumset is 0.4.0. Cursive depends on 0.3.17, making it incompatible with 0.4.0.

**Comment by gyscos** [comment]
Good point, thanks for the report!

**Comment by gyscos** [comment]
Pushed to master ; I'm afraid bumping a public dependency like that is a breaking change :(

**Comment by agavrilov** [comment]
You can publish 0.12 version. If I understand correctly, if other projects have dependencies on Cursive specified as "0.11", 'cargo update' will not bump the version to 0.12 as it considers to be incompatible

**Comment by gyscos** [comment]
Yup, that's what I meant by breaking change. A bit of a shame, as it always add _some_ maintenance cost (need a similar breaking change + release for all third-party libs, need users to update their `Cargo.toml`, ...). But alas, what can we do? :woman_shrugging:
