### ISSUE TITLE
[Question] What is the method File::events ?

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#344]
I was checking out crossbeam and stumbled on this code in `backend/termion.rs`:

```
 71             let input = std::fs::File::open("/dev/tty").unwrap();
 72             let mut events = input.events();
 73 
 74             // Take all the events we can
 75             while let Some(Ok(event)) = events.next() {
 76                 // If we can't send, it means the receiving side closed,
 77                 // so just stop.
 78                 if input_sender.send(event).is_err() {
 79                     break;
 80                 }
 81             }
```

However, looking at std::fs::File doc in `https://doc.rust-lang.org/std/fs/struct.File.html`, I could not find the `File::events` method. 

Could you point me in the right direction? Where do I find the docs for this method if not in the std docs?

P.S. I have had this problem before (not being able to find stuff) so I thought I'd ask. hope you don't mind .... :-)

**Comment by gyscos** [comment]
Hi!

Often in these cases it's a method from a trait that was implemented in a different crate.
In this case, it's [`termion::input::TermRead`](https://docs.rs/termion/1.5.2/termion/input/trait.TermRead.html).

Without an IDE it's not easy to find which trait brings this method. At least you know the trait must be imported to be used, so you could check all the traits imported in `backend/termion.rs`, but I understand that would be a pain.

**Comment by gbonnema** [comment]
Wait .... you have an IDE that shows this kind of connection? I mostly use `vi` but I would be interested to know. 

I didn't realize it was a trait from termion, because the method was on File. Thank you for the tip though. I will look deeper next time, before asking such questions.

**Comment by gyscos** [comment]
I think rls can show the doc for a function, which should include the trait it's defined for.

**Comment by gbonnema** [comment]
rls! I did not know of its existance. I am very interested to find any vi-related stuff using rls. 

Also the jump should be useful, I used to do that in C a lot. 

I will close this now as my query is answered.

**Comment by gyscos** [comment]
Glad it answered your question!

You may have found it already, but here is [`LanguageClient-neovim`](https://github.com/autozimu/LanguageClient-neovim), a plugin for vim and neovim to connect to rls (and language servers of other languages if available).
