### ISSUE TITLE
facing problem with Event::Refresh

### ISSUE THREAD

**Issue by wu000227** [gyscos/Cursive#345]
I am currently struggling with event handling. If I am understanding correctly, **_Event::Refresh_** should be fired continuously if **_Cursive auto_refresh_** is set **_true_**. I wrote a simple test as following to help me understand how it works:

```
struct ImplView;

impl View for ImplView {
  fn draw(&self, _: &Printer) {}
  fn take_focus(&mut self, _: Direction) -> bool { true }
  fn on_event(&mut self, event: Event) -> EventResult {
    match event {
      Event::Refresh => panic!("Executed"),
      _              => EventResult::Ignored
    }
  }
}

fn main() {
  let mut app = Cursive::default();
  app.add_layer(
    Dialog::new().content(ImplView{})
  );
  app.set_autorefresh(true);
  app.run();
}
```

The code above first **_set_autorefresh(true)_** and then catch **_Event::Refresh_** in **_on_event_** of the View I implemented which yields a panic when receiving **_Event::Refresh_**. To my understanding, this program should crush as soon as it starts; but it seems to never catch that event for some reason (while still catching events other than **_Event::Refresh_**).

I've tried to **_return true_** for **_take_focus_**, and also tried changing **_set_autorefersh_** to **_set_fps(30)_** but still no luck. Please help.

## Environment:
* OS: macOS mojave 10.14.3
* backend: cursive
* cursive version: brew install cursive, should be the latest from git
* terminal: iTerm2 and builtin Terminal.app

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Auto-refresh got a bit of a refactor lately, and it seems that `Event::Refresh` is indeed no longer sent.

First, note that `Event::Refresh` is mostly an artifact of how I initially added auto-refresh. It is sometimes a bit surprising: for example, as most events, it is only sent to the currently focuses view, so there is no guarantee your view will receive it if something else is in focus (like a popup).

Still, I can imagine people relied on it, so it shouldn't be too hard to bring back.

**Comment by wu000227** [comment]
Thanks for the update and notice, I will refactor my program in the future to remove it's dependency on ```Event::Refresh```.
