### ISSUE TITLE
[Question] Example vpv.rs does not stop on stdin

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#346]
I was checking out examples. The `vpv.rs` example seemed interesting so I ran it. This turned out to be less than wise as the tool reads from standard input and -- as far as I can see -- there is no way to stop it.

I vaguely remember there is an EOF which should be ctrl-d, but it didn't work unfortunately. The source doesn't give any indication how to stop the process, so I had to use the tool `htop` to kill it.

The source code uses `io::copy` to copy the stream and it also "locks" stdin. So I was wondering if stopping stdin input was even an option? There probably is a way to stop the copying and I just don't see it. 

How do I stop the program when called without arguments short of killing the process?

**Comment by gyscos** [comment]
Hi!

Indeed, this example could benefit from a better interface with a cancel option.
For now, most backends (ncurses and termion at least) stop the application when Ctrl-C is received; this can be used to stop the transfer.

**Comment by gbonnema** [comment]
Maybe you mean when a file is copied? With stdin, ctrl-c does not do anything, other than add 1 to the counter of input. To be sure I added a statusline (from #300) and with backend name which was ncurses.

Unless, this is terminal dependent.

**Comment by gyscos** [comment]
Ah right, it seems that input is indeed not received at all when stdin is not redirected... :S I guess `/dev/tty` and `stdin` are reading concurrently from the same stream rather than each receiving a copy of the data.

So... yeah, we should probably check if `stdin` is a terminal, and show an error in this case.

**Comment by gyscos** [comment]
On `master` the example should now show an error message if no input is given. It also includes an "Abort" button when transferring a file for backends that don't support Ctrl-C.

**Comment by gbonnema** [comment]
Thank you very much!
