### ISSUE TITLE
Allow access to CursiveLogger without initiating it as the global logger?

### ISSUE THREAD

**Issue by daboross** [gyscos/Cursive#348]
I currently like being able to have a `DebugView`, but it's somewhat annoying to have to initialize cursive as the global logger in order to do it.

I'd like to be able to have some `log::Log` which I can point another logger system towards to output logs to both cursive's `DebugView` and, for example, file debug logs.

# Problem description

Using `DebugView` seems to be only possible by using the `cursive::logger::init()` function. But this function initiates `DebugView` as a global logger, which means I can't log to anything else.

I'd like to be able to log to a file as well, or possible syslog, etc. while still taking advantage of `DebugView`. My current solution generally involves logging crates, like [`fern`](https://docs.rs/fern/) and [`slog`](https://docs.rs/slog/) with the [`slog-syslog`](https://docs.rs/slog-stdlog/), which compose over `log::Log`s. Cursive's DebugView doesn't seem compatible with these, though, since it doesn't export a `log::Log`-implementing thing directly.

Ideally, if cursive allowed direct access to `CursiveLogger`, then `DebugView` could be used in tandem with other loggers.

# Environment

Using cursive 0.12.0 right now.

**Comment by gyscos** [comment]
Thanks for the report!

All the logging part is still very new, and could benefit from a bit of polishing. In particular, some more fields might be made public! I pushed f8fb240049fd0bfd02243f5cc3085f4245f5f05f which brings:
* `logger::log()` which is the base function used to log things
* `logger::get_logger()` which returns a (now public) `CursiveLogger`, which implements `log::Log`

**Comment by daboross** [comment]
Awesome, thanks! Glad to be able to use `DebugView` along side log files.

Overall, have to say I'm really enjoying working with cursive.

**Comment by gyscos** [comment]
Thanks for the kind words! :)
