### ISSUE TITLE
Ability to see if "ScrollView" is at edge

### ISSUE THREAD

**Issue by daboross** [gyscos/cursive#355]
# Problem description

I'm using a `ScrollView<TextView>` for a constantly updating console-like view.

When creating it, I set ScrollView to stick to the bottom. When the user scrolls, this reset to "KeepRow".

The problem is that after the user has scrolled once, they're stuck forever in the "KeepRow" mode. I update too often to make resetting to "StickToBottom" every update reasonable. Ideally I would like to implement the scroll resetting back to "StickToBottom" if the user scrolls to back down to the bottom of the view.

I imagine implementing this with something like the following in my update function:

```rust
if scroll_view.is_at_bottom() {
    scroll_view.set_scroll_strategy(ScrollStrategy::StickToBottom);
}
```

But if something works more naturally than `is_at_{edge}`, like getting the size and scroll position, then I'd be good with that - as long as the above could be implemented in some fashion.

It seems like something using `ScrollView::content_viewport` could work, but I'm not at all sure how the numbers relate to each other and I haven't done the research into that.

**Comment by gyscos** [comment]
Thanks for the report!

Indeed, it looks like a gap in the API. `ScrollView` is still a bit fresh, so it might miss a few key features.

`ScrollView::content_viewport` could work if we also had the inner size; you'd then compare the viewport bottom to the inner height. But right now ScrollView doesn't let you access the inner size, so that's one thing we should add.
Convenience functions like `is_at_bottom` might be nice as well.

**Comment by gyscos** [comment]
Just pushed ad23dfe59b2132f45149be245c704380b775f3e5 which brings `ScrollView::inner_size`, as well as the convenience methods `is_at_bottom`, ...

For left/right, I named them `is_at_left_edge` since `is_at_left` didn't sound quite right. Open for bikeshedding.

**Comment by daboross** [comment]
Awesome, thanks! `is_at_bottom` works well for my purpose.

Those left/right function names do sound nicer. Maybe `top`/`bottom` could have `_edge` too for consistency? Either way is good.
