### ISSUE TITLE
Adding items to a selectview inside a scrollview doesn't update the scrollview

### ISSUE THREAD

**Issue by alexanderkjall** [gyscos/cursive#365]
First: is this a bug report? A suggestion? Or asking for help?

Something between a bug report and asking for help. I think it might be a bug but I'm not that experienced with either rust or cursive.

# Problem description

If i have a selectview inside a scrollview, and remove or add items to the selectview, then the scrollbar doesn't get updated.

Here is some code to reproduce the issue:

```
extern crate cursive;

use cursive::Cursive;
use self::cursive::views::{
    Dialog, ScrollView, LinearLayout, SelectView,
};
use self::cursive::direction::Orientation;
use cursive::traits::Identifiable;
use cursive::traits::Boxable;
use self::cursive::event::Event;

fn add(ui: &mut Cursive) -> () {
    ui.call_on_id("results", |results: &mut SelectView<String>| {

        for i in 0..100 {
            results.add_item(i.to_string(), i.to_string());
        }
    });
}

fn main() {
    let mut ui = Cursive::default();

    let results = SelectView::<String>::new()
        .with_id("results")
        .full_height();

    ui.add_global_callback(Event::CtrlChar('a'), add);

    ui.add_layer(
        LinearLayout::new(Orientation::Vertical)
            .child(
                Dialog::around(
                    LinearLayout::new(Orientation::Vertical)
                        .child(ScrollView::new(results)),
                ).title("example"),
            ),
    );
    ui.run();
}
```

# Environment

* Operating system: linux
* Backend used: ncurses
* If using ncurses on linux, ncurses version? 6.1
* Current locale (run `locale` in a terminal).
```
LANG=sv_SE.UTF-8
LANGUAGE=en
LC_CTYPE="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_PAPER="sv_SE.UTF-8"
LC_NAME="sv_SE.UTF-8"
LC_ADDRESS="sv_SE.UTF-8"
LC_TELEPHONE="sv_SE.UTF-8"
LC_MEASUREMENT="sv_SE.UTF-8"
LC_IDENTIFICATION="sv_SE.UTF-8"
LC_ALL=
```

* Cursive version from crates.io: 0.12

**Comment by gyscos** [comment]
Thanks for the report!

The problem is with `full_height`: it was always giving the entire height to the `SelectView`, even when it had 100 items, so it never had to scroll.
I updated `full_height` and `full_width` so that it is now gives the view _at least_ the full size, but it can still grow bigger. This should solve this problem.
