### ISSUE TITLE
Trigger with cb_sink does not appear to redraw the screen

### ISSUE THREAD

**Issue by dfangx** [gyscos/cursive#373]
Hi, I have a custom view which is basically like a select view but with my own formatting. I want to do a redraw of the view whenever the the user submits new content to the view through and EditView. I tried using cb_sink() right after setting the content in my set_content() method, but the custom view stays unchanged. Below is the code for my draw() method for my custom view, as well as my on submit code and set_content(). My first time posting an issue, so let me know if anything is unclear or if you need more information.
```rust
impl View for ListView {
    fn draw(&self, printer: &Printer) {
        self.scroll.draw(printer, |printer, i| {
            let item = &self.content[i];
            let right = item.right_text();
            let left = item.left_text();

            let style = if self.selected == i {
                let fg = PaletteColor::Primary.resolve(&printer.theme.palette);
                ColorStyle::new(
                    ColorType::Color(fg),
                    ColorType::Palette(PaletteColor::Highlight))
            }
            else {
                ColorStyle::primary()
            };
            printer.with_color(style, |printer| {
                printer.print_hline((0,0), printer.size.x, " ");
                printer.print((0,0), &left);
                let offset = HAlign::Right.get_offset(right.len(), printer.size.x);
                printer.print((offset,0), &right);
            });
        });
    }
}

let cmd_line = EditView::new()
    .filler(" ")
    .on_submit(|s, command| {
        s.call_on_id("cmd_line", |view: &mut CmdlineView| {
            view.process_command(command);
        });
        s.focus_id("tab_view").expect("FATAL: unable to focus onto id tab_view");
        s.cb_sink().send(Box::new(Cursive::noop)).unwrap();
    });

impl <T: 'static + ListItem> ListView <T> {
    pub fn set_content (&mut self, content: Vec<T>) {
        self.content = content;
        self.cb_sink.send(Box::new(Cursive::noop)).unwrap();
    }
}
```

**Comment by gyscos** [comment]
Hi, and thanks for the report!

In your case, you might not even need `cb_sink` in the `on_submit`: the view should already be re-drawn after any event. As for the `set_content` function, I would need a bit more context to see how you are calling it.

**Comment by dfangx** [comment]
Hey, thanks for the quick reply. Below is the function that calls `set_content`:

```rust
impl CmdlineView
    fn process_command(&mut self, command: &str) {
        self.clear();
        if self.search_mode {
            let search_term = &command[1..];
            let results = match self.search_engine.search(Some(search_term.to_string())) {
                Ok(results) => results,
                Err(_) => Vec::new(),
            };

            self.call_on_id("video", |view: &mut ListView<_>| {
                view.set_content(results);
            });
        }
        else {
        }
        self.search_mode = false;
        self.enabled = false;
    }
}
```
The `perform_search` method just performs some search functions and then calls `set_content` to set the content of the custom ListView. CmdlineView is a container view I made to group all the associated data of a command line together.

I did a little more digging and it seems like `self.call_on_id` doesn't seem to be working properly. The program isn't entering that part at all. Is there an issue with the way I'm using `call_on_id`? Below is the list view being creating in `main`:
```rust
    let a = TabView::new()
        .tab(String::from("video"), ListView::new(b.clone(), cb.clone()).with_id("video"))
        .tab(String::from("channel"), ListView::new(b.clone(), cb.clone()).with_id("channels"))
        .tab(String::from("channel"), ListView::new(b.clone(), cb.clone()).with_id("channels"))
        .with_id("tab_view");
```
TabView is a custom view which holds the ListView.

**Comment by gyscos** [comment]
That's probably the problem: call_on_id wants the exact type you used with_id on. So it would have to be `TabView` here, and you'll need to get to the ListView in the closure (or expose the method on TabView).

**Comment by dfangx** [comment]
So I would have to use call_on_id on a `Cursive` type, then within that closure use `call_on_id` on `TabView`, and then within that closure `call_on_id` on `ListView<_>`? Correct me if I'm wrong (First rust program ever I'm writing so I may not be understanding everything properly). This is what I've changed it to in CmdlineView:
```rust
            self.cb_sink.send(Box::new(|s| {
                s.call_on_id("tab_view", |view: &mut TabView| {
                    view.call_on_id("video", |list_view: &mut ListView<_>| {
                        list_view.set_content(results);
                    });
                });
            })).unwrap();
```
Still doesn't appear to work. Here's the TabView definitions btw.
```rust
pub struct TabView {
    tabs: Vec<Tab>,
    selected: usize,
}

pub struct Tab{
    label: String,
    view: Box<dyn View>,
}
```

**Comment by gyscos** [comment]
Ah, if you implement TabView as a custom "view group", then you will need to implement a few more methods, like dispatch call_on_any to the children.

If you do that (or if it's already done), you may be able to call .with_id on the child view instead of TabView itself. This way, you could directly call_on_id the child view without explicitly going through the TabView.

**Comment by dfangx** [comment]
Thanks I think I got it working. So by implementing call_on_any in the view group, it forwards any call_on calls to it's children.

**Comment by gyscos** [comment]
Exactly! You can check the implementation from other view groups like [`LinearLayout`](https://github.com/gyscos/cursive/blob/master/src/views/linear_layout.rs#L639):

```rust
    fn call_on_any<'a>(
        &mut self,
        selector: &Selector<'_>,
        mut callback: AnyCb<'a>,
    ) {
        for child in &mut self.children {
            child
                .view
                .call_on_any(selector, Box::new(|any| callback(any)));
        }
    }
```

**Comment by dfangx** [comment]
Thanks :) I think I understand call_on_id now. I will be closing this issue then
