### ISSUE TITLE
Still has hashbrown as dependency

### ISSUE THREAD

**Issue by chrunchyjesus** [gyscos/cursive#377]
> First: is this a bug report? A suggestion? Or asking for help?

A question.

# Problem description

Is there a minimal rustc version cursive needs to support or something like that? Because hashbrown has become the default hashmap implementation for rustc and cursive has it as an explicit dependency. 

https://github.com/rust-lang/hashbrown

**Comment by gyscos** [comment]
Thanks for the report!

I was still using `hashbrown` for the faster hasher used, but I guess I could instead use https://github.com/cbreeden/fxhash with `HashMap::with_hasher`.

**Comment by gyscos** [comment]
Should be replaced on master.
