### ISSUE TITLE
Examples: `extern crate cursive;` required by the compiler

### ISSUE THREAD

**Issue by lunakid** [gyscos/cursive#378]
Rust absolute newbie here (with only hello-world mileage). My very first package build attempt was compiling the demo in the README, which failed, until I added `extern crate cursive;`, as the compiler hinted.

Should it be included in the example source(s) then? Or if not (I think there's a good reason why it's not included there, and in any of the example sources), then some hint in the README on how to avoid this pitfall might be helpful.

~~~
$ rustc -V
rustc 1.36.0
$ cargo build
   ...
   Compiling ncurses v5.99.0
   ...
   Compiling cursive v0.13.0
   Compiling test v0.0.0 (/.../rust/cursive)

error[E0433]: failed to resolve: maybe a missing `extern crate cursive;`?
 --> example-dlg.rs:2:5
  |
2 | use cursive::views::{Dialog, TextView};
  |     ^^^^^^^ maybe a missing `extern crate cursive;`?

error[E0432]: unresolved import `cursive`
 --> example-dlg.rs:1:5
  |
1 | use cursive::Cursive;
  |     ^^^^^^^ maybe a missing `extern crate cursive;`?

error[E0433]: failed to resolve: use of undeclared type or module `Dialog`
 --> example-dlg.rs:9:19
~~~

FYI, Cargo.toml (created by hand):

~~~
[package]
name = "test"
version = "0.0.0"

[dependencies]
cursive = "0.13"

[[bin]]
name = "test"
path = "example-dlg.rs"
~~~

**Comment by FreeFull** [comment]
Usually, people use `cargo init` to create their projects, which includes `edition = "2018"` under `[package]`

**Comment by gyscos** [comment]
As @FreeFull mentioned, `extern crate` was made optional in Rust 2018, which requires to be set in `Cargo.toml`. Note that projects created with `cargo new` should automatically include this.

**Comment by lunakid** [comment]
Yes, thanks, I've found it out in the meantime.
