### ISSUE TITLE
Making toml an optional dependency

### ISSUE THREAD

**Issue by chrunchyjesus** [gyscos/cursive#379]
> First: is this a bug report? A suggestion? Or asking for help?

Suggestion.

# Problem description

With just a few `cfg(feature = ...)` I managed to make `toml` an optional feature. With that, the release binary size got reduced from 5.14MB to 4.73MB without that feature enabled. Do you think it is of benefit to make loading theme files an optional feature? If yes then I can create a pull request for it.

**Comment by gyscos** [comment]
Good idea! I was thinking of pushing both `toml` and `serde` to a `serialize` feature (or even a separate crate), since it's only used to parse themes, which is far from the common use-case.

**Comment by gyscos** [comment]
On latest master it's now behind a `toml` feature.
