### ISSUE TITLE
Scrollbar still drawn despite show_scrollbars(false)

### ISSUE THREAD

**Issue by Inrin** [gyscos/cursive#381]
First: is this a bug report? A suggestion? Or asking for help?
bug
# Problem description
`show_scrollbars(false)` inside a `LinearLayout`-`SelectView`-child only disables mouse support.
```
fn main() {
    let mut siv = Cursive::default();
    siv.add_global_callback('q', Cursive::quit);

    let mut list = SelectView::new().h_align(HAlign::Left);
    for i in 0..siv.screen_size().y + 10 {
        list.add_item(i.to_string(), i);
    }

    siv.add_fullscreen_layer(
        LinearLayout::vertical()
            .child(list.scrollable().show_scrollbars(false))
            .full_screen(),
    );

    siv.run();
}
```

# Environment
* Arch Linux
* ncurses 6.1
* cursive "0.13"

**Comment by gyscos** [comment]
Whoops indeed! It seems `show_scrollbars` is currently quite broken :S
Will investigate.

**Comment by gyscos** [comment]
Just pushed a fix on master - does it solve your problem?

**Comment by Inrin** [comment]
Works like charm!
Thank you veyr much.
