### ISSUE TITLE
EventResult callback

### ISSUE THREAD

**Issue by dfangx** [gyscos/cursive#382]
Hi

I'm running to a problem with `EventResult::Consumed(cb)`. It appears that the callback I am giving the EventResult is not being run. Below is my code:
```rust
Event::char('o') => {
                    let selected = self.selected;
                    let content = self.content.clone();
                    //panic!("Before cb"); 
                    return EventResult::with_cb(move |s| {
                        //panic!("In cb"); 
                        s.call_on_id("ncyt", |ncyt: &mut NcytView| {
                            let content = content.read().unwrap();
                            if let Some(v) = content[selected].open() {
                                ncyt.push_view(v);
                            }
                        });
                    })
                },
```
As you can see, I am using the `panic!()` macro to see if the callback is being run. The first `panic!()` runs so I know that code for `Event::Char('o')` runs. The second `panic!()` does not run when the first is commented out, leading me to believe that the closure is not being run. Could I get some help on this? If additional context is needed, please let me know.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

It's possible the `EventResult` is not properly bubbled up to the `Cursive` root, where it would usually be called. Where is this code being called? In a custom `View` implementation? What is the view tree?

In some cases, you are supposed to call an `EventResult` by yourself, for example if you manually call `.on_event()` on a view (maybe from another callback). Some other methods also return an `EventResult` that you'll need to manually call, like `Checkbox::select()` (though it seems unlikely to be the case here).

Do you have a complete example I could run to reproduce this bug?

**Comment by dfangx** [comment]
Hey, thanks for the tip. I think I've solved this issue. Turns out I wasn't sending the EventResult all the way up the tree. Thanks!

**Comment by gyscos** [comment]
Glad you find the problem!
I'm considering making `EventResult` `#[must_use]` to avoid ignoring one by mistake, but I'm afraid it could be quite annoying in some cases. Hmm...
