### ISSUE TITLE
Could this be evolved into a state based library like react or flutter

### ISSUE THREAD

**Issue by noelzubin** [gyscos/cursive#386]
Asking for help 

Was going through the code. Do you think its possible to add setState function to View or perhaps ViewWithState(like in flutter) and only redraw areas where state was udpdated.
Or was this intentionally left out ?

**Comment by gyscos** [comment]
It was mostly to keep the core logic as simple as possible - it's already a bit convoluted as it is.

In addition, this sounds like it may be implemented entirely as a custom `View` which would generate a cached content based on a shared state, a bit like `TextView` with its `TextContent`.
Generalizing this pattern might be a good thing; if you have some ideas, don't hesitate to post some example use-cases to see how this could be useful!

**Comment by schneiderfelipe** [comment]
I think this might be related to #597.
This kind of functionality might be well suited for a sister library.
