### ISSUE TITLE
Add set_focus_index for LinearLayout

### ISSUE THREAD

**Issue by CoNsTaRs** [gyscos/cursive#388]
As title suggested, is there any reason that `set_focus_index` doesn't exist?
Thanks.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Ah indeed we might add this function.

Right now you would use something like `View::focus_view`, but that only works if you are targetting a known ID (though "eventually" there should be a `Selector` to select the nth view, which would do what you want).

In the meantime I'll add this `set_focus_index`; it'll probably return a `Result<(), ()>` just like `focus_view` in case the nth element is not focusable.

**Comment by CoNsTaRs** [comment]
Thanks for the response! I am closing this issue since the function will be added.
