### ISSUE TITLE
SelectView.select_up and select_down moves selection but not viewport 

### ISSUE THREAD

**Issue by alexanderkjall** [gyscos/cursive#392]
First: is this a bug report? A suggestion? Or asking for help?

A bug report

# Problem description

This is a somewhat strange use case, but it's what we do in https://github.com/cortex/ripasso/

We have an EditView with a SelectView below, and map Key::Up and Key::Down events to movement of the select marker in the SelectView. When moving the select marker offscreen, the selectview doesn't scroll with it, and I can't find any way to make it do that.

Here is an example program that displays the problem:

```
extern crate cursive;

use cursive::Cursive;
use self::cursive::views::{
    Dialog, ScrollView, LinearLayout, SelectView, BoxView, IdView, OnEventView, EditView
};
use self::cursive::direction::Orientation;
use cursive::traits::Identifiable;
use cursive::traits::Boxable;
use self::cursive::event::Event;

fn add(ui: &mut Cursive) -> () {
    ui.call_on_id("results", |results: &mut SelectView<String>| {

        for i in 0..100 {
            results.add_item(i.to_string(), i.to_string());
        }
    });

    ui.call_on_id("scroll", |scroll: &mut ScrollView<BoxView<IdView<SelectView<String>>>>| {
        scroll.scroll_to_bottom();
    });
}

fn down(ui: &mut Cursive) -> () {
    ui.call_on_id("results", |l: &mut SelectView<String>| {
        l.select_down(1);
    });
}

fn up(ui: &mut Cursive) -> () {
    ui.call_on_id("results", |l: &mut SelectView<String>| {
        l.select_up(1);
    });
}

fn main() {
    let mut ui = Cursive::default();

    let results = SelectView::<String>::new()
        .with_id("results")
        .full_height();

    let scroll = ScrollView::new(results)
        .with_id("scroll");

    ui.add_global_callback(Event::CtrlChar('a'), add);

    let searchbox = EditView::new()
        .with_id("searchbox")
        .fixed_width(72);

    let searchbox = OnEventView::new(searchbox)
        .on_event(cursive::event::Key::Up, up)
        .on_event(cursive::event::Key::Down, down);

    ui.add_layer(
        LinearLayout::new(Orientation::Vertical)
            .child(searchbox)
            .child(
                Dialog::around(
                    LinearLayout::new(Orientation::Vertical)
                        .child(scroll),
                ).title("example"),
            )
    );
    ui.run();
}

```

# Environment

* Operating system: linux (Ubuntu 19.10)
* Backend used: ncurses
  * If using ncurses on linux, ncurses version? 6.1
* Current locale (run `locale` in a terminal).
```
LANG=sv_SE.UTF-8
LANGUAGE=en
LC_CTYPE="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_PAPER="sv_SE.UTF-8"
LC_NAME="sv_SE.UTF-8"
LC_ADDRESS="sv_SE.UTF-8"
LC_TELEPHONE="sv_SE.UTF-8"
LC_MEASUREMENT="sv_SE.UTF-8"
LC_IDENTIFICATION="sv_SE.UTF-8"
LC_ALL=
```
* Cursive version 0.13.0 from crates.io

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, currently `ScrollView` only refreshes its position in response to direct events, so if the child view changes its important area outside of an event, it won't be picked up. This is to let the scrollview scroll outside of the important area, for example when using the scrollbar. Any event to the inner view will bring back the important area in view.

One solution I see is to add a function to `ScrollView` to manually bring back the important area in view, without the need for an event to be actually sent. Would this fit your use-case?

**Comment by alexanderkjall** [comment]
That would work nicely I think :)

**Comment by gyscos** [comment]
Just pushed `ScrollView::scroll_to_important_area` - let me know if it works or not for you! :)

**Comment by alexanderkjall** [comment]
Maybe I'm not understanding something, but shouldn't it be `SelectView::scroll_to_important_area` ?

How can i access the ScrollView from my SelectView?

**Comment by gyscos** [comment]
SelectView doesn't know about any scrolling: for all it knows, the screen is unlimited and everything can fit.
The ScrollView is what decides what should be visible from that. If the inner view changes without a direct event, it needs to be told to update its offset.

One way is to put an id on the ScrollView itself, not the SelectView; then you'd access the inner SelectView with ScrollView::get_inner_mut.
Another way is to put an id on both views, especially if the ScrollView has other children as well.

**Comment by alexanderkjall** [comment]
Thanks for the great example :)

I got confused from the differances between my example program and ripasso, but I also got it to work in ripasso.

Agree on that the types isn't very pretty or easy to work with, but i'm not experienced enough with rusts type system to be able to have any opinions on how to solve it.

**Comment by jansc** [comment]
For some reason, in my application, the ScrollView's `scroll_to_important_area` would also jump to the top of the contained SelectView, even if the selected line in the SelectView was below the visible screen. The only way to make the ScrollView behave, was to call `set_offset()` with the selected item. See [this commit](https://github.com/jansc/ncgopher/commit/88ff5232cd8702f858bb24b7cef639b98ef15350). Not sure if this is a bug in cursive, probably in somewhere in my code.
