### ISSUE TITLE
as_inner for ViewWrapper?

### ISSUE THREAD

**Issue by PoYen000227** [gyscos/cursive#396]
This is either a suggestion or an asking for help.

I am trying to work with `PaddedView` and need to constantly access to its inner view, I am wondering if there is anything like `as_inner` or `as_inner_mut` I can use? Since `into_inner` consumes itself, it is not really suitable for such scenarios.

Thanks!

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The `ViewWrapper` trait _by itself_ does not give you direct access to the inner view (though `with_view` or `with_view_mut` can usually handle most use-cases). But many views implementing `ViewWrapper` also implement a few other methods, like `get_inner` and `get_inner_mut`. [There's even a macro to help define these two methods](https://docs.rs/cursive/0.13.0/cursive/macro.inner_getters.html). Though it seems that I forgot to add these for `PaddedView`! :S

**Comment by PoYen000227** [comment]
Thanks for the explanation and help!
I am closing this as it is no longer a problem.
