### ISSUE TITLE
Inconsistent rendering in `markup` example in crossterm and termion

### ISSUE THREAD

**Issue by vmedea** [gyscos/cursive#401]
In some terminals, the `markup` example is rendered inconsistently for termion and crossterm backend. This doesn't happen for the ncurses backend.

in tmux (after pressing `Tab` once)
![tmux](https://user-images.githubusercontent.com/43048142/67663200-3eac4080-f965-11e9-8ef2-a2e2c4a80bd8.png)

in gnome-terminal:
![gnome-terminal](https://user-images.githubusercontent.com/43048142/67663212-453ab800-f965-11e9-8aff-1d12e89147b8.png)

Also reported here: https://github.com/gyscos/cursive/issues/90#issuecomment-515743068

The root problem is that the `NoBold` (21) terminal attribute doesn't reliably work over terminals https://github.com/crossterm-rs/crossterm/issues/294

It appears that `NormalIntensity` (22) instead works more portably to cancel bold. ~~That catch is that this ends italic as well, so this would need some more logic… (this doesn't seem to be true)~~

**Comment by gyscos** [comment]
Blast! :^/

I guess one way would be to reset all the attributes, and re-enable the ones we want to keep. The backend code would have to store the current style; when calling `unset_effect`, it would update this current style, send a big `Reset` that disables all attributes, then re-set the current style. It means a few more escape codes to send, but it shouldn't be _that_ bad most of the time (except when assigning a different style to each cell in a nethack-style where it would ~double the required bandwidth).

I'm curious how `termion` and `ncurses` handle this - do they handle this state internally? Or are they using a different escape code? Will need to investigate.

**Comment by vmedea** [comment]
> I guess one way would be to reset all the attributes, and re-enable the ones we want to keep.

Resetting all attributes every time a state is disabled would be the surest, but that'd involve re-sending the foreground and background color too!

Good news: I've done some testing on the affected terminals and it seems that using 22 instead of 21 "just works". It doesn't disable italic or any of the other supported attributes, as I thought.
```bash
echo -e "\x1b[1m bold enabled\x1b[22m disabled"
echo -e "\x1b[3m italic\x1b[22m (still italic)\x1b[23m disabled"
echo -e "\x1b[4m underline\x1b[22m (still underline)\x1b[24m disabled"
echo -e "\x1b[7m reverse\x1b[22m (still reverse)\x1b[27m disabled"
echo -e "\x1b[9m strikethrough\x1b[22m (still strikethrough)\x1b[29m disabled"
```
So for now, unless we find a terminal where this breaks end-bold, it seems to be the quickest workaround.

> except when assigning a different style to each cell in a nethack-style where it would ~double the required bandwidth

Oh yes that's definitely the worst-case scenario! though in that case, assuming not every cell changes every frame, updating only the cells that change from frame to frame would be the most effective way to save bandwidth.

> I'm curious how termion and ncurses handle this

Termion does the same kind of low-level handling as crossterm, and has the same problem here.

Ncurses keeps track of state internally, and pulls in this terminfo monster database that tracks what escape codes are supported by which terminal (based on the TERM env variable), so in theory it might be able to emit the state changes selectively. It's kind of crufty though—half of the time, people have misconfigured TERM.

**Comment by gyscos** [comment]
> Termion does the same kind of low-level handling as crossterm, and has the same problem here.

Ha ha indeed, it has the same problem with the markup example! Somehow I missed that. I guess it will need its own update to move away from `NoBold`. It seems they call the 22 code `NoFaint`?
https://github.com/redox-os/termion/blob/master/src/style.rs#L14

**Comment by vmedea** [comment]
> Ha ha indeed, it has the same problem with the markup example! Somehow I missed that. I guess it will need its own update to move away from NoBold. It seems they call the 22 code NoFaint?

exactly !
