### ISSUE TITLE
How to add a Box<View> back to a LinearLayout?

### ISSUE THREAD

**Issue by vmedea** [gyscos/cursive#404]
I'm doing dynamic manipulation of the view tree, where I need to remove a view and re-add it as a child of an intermediate node;
```rust
        let v1 = layout.remove_child(pleaf).unwrap();
        let mut sublayout = match method.dir() {
            winmethod::Left => LinearLayout::horizontal().child(win).child(v1),
            winmethod::Right => LinearLayout::horizontal().child(v1).child(win),
            winmethod::Above => LinearLayout::vertical().child(win).child(v1),
            winmethod::Below | _ => LinearLayout::vertical().child(v1).child(win),
        };
        layout.insert_child(pleaf, sublayout);
```
It's not working though.
```
error[E0277]: the trait bound `std::boxed::Box<dyn cursive::traits::View>: cursive::view::ViewWrapper` is not satisfied
   --> src/window_manager.rs:125:78
    |
125 |                             winmethod::Below | _ => LinearLayout::vertical().child(v1).child(win),
    |                                                                              ^^^^^ the trait `cursive::view::ViewWrapper` is not implemented for `std::boxed::Box<dyn cursive::traits::View>`
    |
    = note: required because of the requirements on the impl of `cursive::traits::View` for `std::boxed::Box<dyn cursive::traits::View>`
```
Is there any way that this is possible that I'm missing?

**Comment by gyscos** [comment]
You can do 2 things:
* If you know the type `T` of the view, you can use [`AnyView::downcast()`](https://docs.rs/cursive/0.13.0/cursive/view/trait.AnyView.html#method.downcast) to go from `Box<dyn View>` to `Box<T>` then dereference to get a `T`, and add this `T` to the child.
* Wrap the `Box<dyn View>` in a [`ViewBox`](https://docs.rs/cursive/0.13.0/cursive/views/struct.ViewBox.html), and add _that_ to the child.

The first option needs you to know at compile time the type of the view. The second option means that the child will re-box the given already-boxed view, so it causes a bit more indirection.

The second solution could be improved if parent views could have a special path for to add `ViewBox` without re-boxing them. It could be done with specialization, or with a dedicated method.

**Comment by gyscos** [comment]
Actually it seems I already added `IntoBoxedView` for this purpose, it just wasn't used for `LinearLayout`. You should now be able to add the `Box<dyn View>` directly, and it won't be re-boxed.

**Comment by vmedea** [comment]
That's perfect, it just works now!

Thank you!

> If you know the type T of the view, you can use AnyView::downcast()

The idea was to keep the information of what view is used abstracted, if possible. I guess wrapping it one time in a ViewBox would have worked too because from then on the type is known :smile: But this is great.
