### ISSUE TITLE
Less confusing order for margins

### ISSUE THREAD

**Issue by gyscos** [gyscos/cursive#407]
The `Margins` struct is used wherever we need padding/margins. It needs 4 values (for each side), and the order is kind of a mess because there is no clear canonical way to group them.

We could have 2 `XY<usize>` to represent two corners, but which one is top_left? Or is it top_right?
We could have a single `XY<(usize, usize)>`, but is it `(top, bottom)`? `(bottom, top)`?
Also, if we accept `T: Into<XY<...>>`, then we'll end up working with `((usize, usize), (usize, usize))` - which one of the two is that?

The current `Margins::new` method takes `left`, `right`, `top`, `bottom`.
I recently realized CSS makes another choice, with the now famous `trbl` ordering: `top`, `right`, `bottom`, `left`.

All in all, it's kind of a mess, and `Dialog::new().padding((1,1), (0,0))` will probably stay ambiguous.

Maybe this is a place where we should force named parameters, and not try to be smart with all these `From` implementations?

```rust
use cursive::view::Margins as M;

Dialog::new().padding(M { left: 1, right: 1, top: 0, bottom: 0 })
```

**Comment by vmedea** [comment]
I tend to agree that there's not really a clear non-confusing way to order margins. I think the `M {...}`  structure is a clear approach. But very verbose without the `use cursive::view::Margins as M;`. It's a shame that rust doesn't have real named parameters, sometimes.

**Comment by gyscos** [comment]
Version 0.14.0 dropped support for these tuples, and instead uses `Margins::lrtp`, `Margins::trbl`, ... to be more explicit about the order of the fields.

Though I also added `PaddedView::lrtp(left, right, top, bottom, view)`, and now realize I probably should have used `PaddedView::lrtp((left, right, top, bottom), view)` instead, so that it is mostly compatible with the previous `PaddedView::new`. Ah well... :S
