### ISSUE TITLE
loss panic message

### ISSUE THREAD

**Issue by s97712** [gyscos/cursive#409]
First: is this a bug report? A suggestion? Or asking for help?

# Problem description
When my program crash caused by exception like `panic` or `unwrap`, I can't see any message on the terminal, this is bug or feature? How do I find the cause of the crash?
# Environment

* Operating system: archlinux
* Backend used: ncurses (
  * If using ncurses on linux, ncurses version? 6.1
* Current locale: en_US.utf8
* Cursive version: least

**Comment by FreeFull** [comment]
I suspect this might be due to Rust first printing the panic message, and then unwinding the stack. The message ends up on the terminal's alternate screen,so it's not visible after the destructors run.

**Comment by Lesik** [comment]
This issue was closed, but I'm still unsure as to what the best course of action would be. Can clearing the screen be prevented? Should the panics be redirected to another output somehow?

**Comment by gyscos** [comment]
A common debugging solution is to redirect stderr to a file, and print this file separately:
```
$ cargo run 2> err_file
$ cat err_file
```

**Comment by gyscos** [comment]
A more long term solution will be to replace the panic handler to avoid printing when panicking, use catch_unwind to recover from a panic, and either re-panic after cleaning the screen, or do some other error handling.

**Comment by Lesik** [comment]
Thanks for the info!
