### ISSUE TITLE
Wrapped text in TextView is not aligned properly

### ISSUE THREAD

**Issue by j-tai** [gyscos/cursive#426]
# Problem description

In a TextView, if a line of text is wrapped, then the line is not aligned properly:

```rust
use cursive::align::Align;
use cursive::view::Resizable;
use cursive::views::TextView;
use cursive::Cursive;

fn main() {
    let mut c = Cursive::default();
    c.add_layer(
        TextView::new("abcdef abcdefghij abcdef abcde")
            .align(Align::center())
            .fixed_size((16, 5)),
    );
    c.run();
}
```

![Screenshot_20200216_182410](https://user-images.githubusercontent.com/45131430/74619223-a2cd5d00-512c-11ea-848e-22255895f920.png)

I expected the text to look like this:

![Screenshot_20200216_182338](https://user-images.githubusercontent.com/45131430/74619231-a9f46b00-512c-11ea-8c80-1b6a4b846cac.png)

The same problem occurs with right-aligned text.

# Environment

* Operating system: Arch Linux
* Backend used: ncurses
  * If using ncurses on linux, ncurses version? 6.1
* Current locale: en_CA.UTF-8
* Cursive version: 0.14.0 from crates.io

**Comment by gyscos** [comment]
Thanks for the report!
Indeed, it used to be this way, but it got messed up at some point. Will look into that.
