### ISSUE TITLE
views::Panel can be too small to display it's own title

### ISSUE THREAD

**Issue by DianaNites** [gyscos/cursive#435]
Bug? Panels size don't account for their titles

# Problem description

The following code reproduces

```rust
use cursive::view::Resizable;
let mut root = Cursive::default();
let title = "Hello World";
root.add_layer(
cursive::views::Panel::new(cursive::views::TextView::new("Hi!"))
    .title("Hello World")
    // .min_width(title.len() + 6), // Uncomment to get title
);
root.run();
```

To display the title it needs to be *six* characters larger, because of padding?

# Environment

* Backend used: Termion
* Cursive version "0.14.0"

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, right now `Panel` completely ignores the title when computing the size - the idea was to let the view gracefully shrink if needed by hiding the title. I understand it's not always desired - `Dialog` for example makes sure the title fits in the window, so we could do the same here.
