### ISSUE TITLE
Help building a timed counter.

### ISSUE THREAD

**Issue by emilnd** [gyscos/cursive#442]
I'm asking for help.

# Problem description
Hi.
I'm trying to build a timed countdown with cursive. 25, 24, 23 .... 0 in seconds.
I've made an atempt by using the Mutation example:  https://github.com/gyscos/cursive/blob/master/examples/mutation.rs

```rust
use cursive::Cursive;
use cursive::traits::*;
use cursive::views::{Dialog, OnEventView, TextView};
use cursive::view::{Offset, Position};

fn main() {
    let mut siv = Cursive::default();

    let content = "I want to be a counter!";

    siv.add_layer(
        OnEventView::new(TextView::new(content).with_name("count"))
            .on_event('p', |s| change_content(s)),
    );

    siv.run();
}

fn change_content(siv: &mut Cursive) {
    siv.screen_mut().add_layer_at(
        Position::new(Offset::Center, Offset::Parent(5)),
        Dialog::around(TextView::new("Start counter"))
            .button("Start", |s| {
                s.call_on_name("count", |view: &mut TextView| {

                view.set_content("never let go");
                view.set_content("of the handlebars");
                view.set_content("when you eyes are");
                view.set_content("closed..");
                /*
                    for x in 25..0 {
                        view.set_content(format!("{}", x.to_string()));
                        view.set_content("not even this :/");
                    }
                */
                });
            })
            .dismiss_button("Ok"),
    );
}
```
On line 26-29 I'm able to update **content** with **view.set_content()**. But only the last one is displayed, although I guess the first three entries (26,27,28) actually are shown but in a blink of second, so only the last i left to be shown?

As you can see I've also tried to go with an for-loop, but there, actually nothing at all gets updated for **view.set_content()**

Can someone explain to me why the for-loop does not work? And am I going the right direction for accomplishing a timed counter, or is there a better way to do this, like in the example Progress?

# Environment

* Operating system: Linux Devuan Ascii (Debian Stretch)
* Backend used: ncurses 
NCURSES_VERSION "6.0"
* Current locale: en_US.UTF-8
* Cursive version: 14

**Comment by gyscos** [comment]
Hi, and thanks for the report!

As you noticed, the callback method is executed instantly, and any intermediate state doesn't have any time to be visible.

This is by design: callbacks are _supposed_ to be run instantly. Actually, cursive will not even refresh the screen until the callback function completes! So even if you added some steps to sleep between changes, you wouldn't actually see the changes. These callbacks are meant to run one action, like `view.set_content("never let go");` _or_ `view.set_content("of the handlebars");`.

What you probably want is to run many different callbacks, each some time apart. For example, after waiting 1 second, we want to trigger something, run a callback to change the text, then keep running as usual for the next second, when another callback will change the content further. We want some chain of logic to progress in parallel of the cursive loop, which is focused on printing the screen and handling user events. We can do that with a separate thread.

```rust
let sleep_duration = std::time::Duration::from_millis(1_000);  // 1 second
std::thread::spawn(move || {
    std::thread::sleep(sleep_duration);
    // Run action 1, display "never let go"
    std::thread::sleep(sleep_duration);
    // Run action 2, display "of the handlebars"
    std::thread::sleep(sleep_duration);
    // ...
});
```

So now all we need is to trigger each action from a separate thread. How? We can't move the `s: &mut Cursive` in there, but there's another way: [`Cursive::cb_sink`](https://docs.rs/cursive/0.14.0/cursive/struct.Cursive.html#method.cb_sink). It gives you the sending half of a pipe, so you can send callbacks from another thread. Let's use it!

```rust
let cb_sink = s.cb_sink().clone();
let sleep_duration = std::time::Duration::from_millis(1_000);  // 1 second
std::thread::spawn(move || {
    // Here we are running in the parallel thread. We can block however we want.
    std::thread::sleep(sleep_duration);
    // Run action 1, display "never let go"
    cb_sink.send(Box::new(|s| {
        // _This_ callback will be run in the main thread. Don't sleep here!
        s.call_on_name("count", |view: &mut TextView| view.set_content("never let go"));
    })).unwrap(); // This would only fail if `Cursive` was dropped in the main thread.

    std::thread::sleep(sleep_duration);
    // Run action 2, display "of the handlebars"
    cb_sink.send(Box::new(|s| {
        s.call_on_name("count", |view: &mut TextView| view.set_content("of the handlebars"));
    })).unwrap();

    std::thread::sleep(sleep_duration);

    // Run action 3, display "of the handlebars"
    cb_sink.send(Box::new(|s| {
        s.call_on_name("count", |view: &mut TextView| view.set_content("when you eyes are"));
    })).unwrap();

    std::thread::sleep(sleep_duration);

    // Run action 4, display "closed"
    cb_sink.send(Box::new(|s| {
        s.call_on_name("count", |view: &mut TextView| view.set_content("closed"));
    })).unwrap();
});
```

Of course something repetitive like that can be simplified:

```rust
let cb_sink = s.cb_sink().clone();
let sleep_duration = std::time::Duration::from_millis(1_000);  // 1 second
std::thread::spawn(move || {
    for text in &["never let go", "of the handlebars", "when you eyes are", "closed"] {
        std::thread::sleep(sleep_duration);

        cb_sink.send(Box::new(|s| {
            s.call_on_name("count", |view: &mut TextView| view.set_content(text));
        })).unwrap();
    }
});
```

(This code would go in the callback from `.button("Start", |s| { ... })`

Using a separate thread like this is how `Progress` works, but in a more specialized way.

**Comment by emilnd** [comment]
Hi!
Thank you so much for your very clear and educating answer. I've only quickly tried your code in my own, and at the moment I'm stuck on compiling erros. But I'm sure I will get out of it as soon as I'm able to give coding a bit more time later this week.

**Comment by emilnd** [comment]
I'm really scratching my head right now.
Only by following your last example and writing a list manually and with **for text in &["25", "24" ...]** , I do get the desired result. Though I can't manage to generate the list automatically.

This is what I've tried:
`
            std::thread::spawn(move || {

                     //for text in &["25", "24", "23", "22", "21", "20"] {

                     let mut bucket = vec![];
                     for b in (25..0).rev() {
                         bucket.push(b.to_string());
                     }

                     //for num in (25..0).rev() {
                     for text in bucket {
                         std::thread::sleep(sleep_duration);
                         cb_sink.send(Box::new(move |s| {
                             //s.call_on_name("count", |view: &mut TextView| view.set_content(num.to_string()));
                             s.call_on_name("count", |view: &mut TextView| view.set_content(text));
                         })).unwrap();
                     }
`

As you can see, I have tired some different solutions. All is coming down to somehow give set_content some strings to use. I looked up on the documentation about set_content and StyledString/SpannedString, but I can't understand if it **only** accepts Strings like "example" and not in any other way?

**Comment by gyscos** [comment]
It's a bit convoluted, but:
* `TextView::set_content` takes a `S: Into<StyledString>`
* `StyledString` is really a `SpannedString<Style>`: https://docs.rs/cursive/0.14.0/cursive/utils/markup/type.StyledString.html
* We have `impl <S, T> From<S> for SpannedString<T> where S: Into<String>, T: Default`: https://docs.rs/cursive/0.14.0/cursive/utils/span/struct.SpannedString.html#impl-From%3CS%3E
* We also have `Style: Default`: https://docs.rs/cursive/0.14.0/cursive/theme/struct.Style.html#impl-Default
* From this we can deduce that any `S: Into<String>` also implements `Into<SpannedString>`. This includes, among others, `String`, `&String`, and `&str`: https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#impl-From%3C%26%27_%20String%3E

So `set_content` should work both with `&str` or `String`.

Here's a quick example running on the latest git branch that looks like your code:
```rust
use cursive::traits::*;
use cursive::views::{Dialog, TextView};

fn main() {
    let mut siv = cursive::default();
    siv.add_layer(Dialog::around(
        TextView::new("Starting...").with_name("text"),
    ));

    let cb_sink = siv.cb_sink().clone();

    let duration = std::time::Duration::from_millis(1000);
    std::thread::spawn(move || {
        for num in 0..25 {
            std::thread::sleep(duration);
            cb_sink
                .send(Box::new(move |s| {
                    s.call_on_name("text", |v: &mut TextView| {
                        v.set_content(num.to_string())
                    });
                }))
                .unwrap();
        }
        cb_sink.send(Box::new(|s| s.quit())).unwrap();
    });

    siv.run();
}
```

**Comment by emilnd** [comment]
Yes! It now works as I want/need it to do.

Thank you for the tracing of TextView::set_content. I'll guess I need to get an better understanding of Impl and such.

Either way the only difference I could found with your latest example and my is added brackets around v.set_content(num.to_string()) and that I use the latest git-version as you said.

![cursive-brackets](https://user-images.githubusercontent.com/41476744/80475773-add11480-8949-11ea-8e75-3d1b40aaa3cc.png)

I would just like to get a confirmation on this, and then we can close the issue. Thanks so much for all your help!

**Comment by gyscos** [comment]
The brackets shouldn't matter; and the latest git master only affects the initialization (`Cursive:: default` vs `cursive::default`).

If you have a compiler error message, and/or a complete code to try, I could look into what's going on, but it's a bit tricky to figure it out from what I have so far.

**Comment by emilnd** [comment]
Yes I understand.
It was a while since I looked into it. I might check it out again during the summer. Thanks for all help!
