### ISSUE TITLE
How to run theme example?

### ISSUE THREAD

**Issue by vmedea** [gyscos/cursive#451]
According to the Readme.md this should work, but it doesn't:
```bash
$ cargo run --release --bin theme --features cursive/toml
error: failed to select a version for `cursive`.
    ... required by package `cursive-examples v0.1.0 (/home/user/upstream/Cursive/examples)`
versions that meet the requirements `= 0.15.0-alpha.0` are: 0.15.0-alpha.0

the package `cursive-examples` depends on `cursive`, with features: `toml` but `cursive` does not have these features.

failed to select a version for `cursive` which could resolve this conflict
```
The example itself still erroneously says to use `cargo run --example theme --features toml` but that doesn't work anymore since the examples were split out.

**Comment by gyscos** [comment]
Arf indeed and it seems impossible to specify features 2 levels down (`cursive/cursive-core/toml`).
Guess we do need to forward these after all.

Anyway, thanks for the report!

**Comment by gyscos** [comment]
Should work again on latest master

**Comment by vmedea** [comment]
Better, but still doesn't entirely work!
See  #452 for a proposed fix.

**Comment by gyscos** [comment]
Woops, missed that - thanks!

**Comment by vmedea** [comment]
This is resolved!
