### ISSUE TITLE
example code for 0.14.0 fails to compile, cannot find cursive::default()

### ISSUE THREAD

**Issue by flajann2** [gyscos/cursive#455]
First: is this a bug report? A suggestion? Or asking for help?
Bug

# Problem description
I tried compiling the same code:
-----
use cursive::views::TextView;
fn main() {
	let mut siv = cursive::default();
	siv.add_global_callback('q', |s| s.quit());
	siv.add_layer(TextView::new("Hello cursive! Press <q> to quit."));
	siv.run();
}
-----

And I get:
-----
error[E0425]: cannot find function `default` in crate `cursive`
 --> src/bin/test-c-hello.rs:3:25
  |
3 |     let mut siv = cursive::default();
  |                            ^^^^^^^ not found in `cursive`
-----

# Environment
Rust 1.45.0-nightly
Kubuntu 12.04

I also have pancurses included, but only because I started out with that and am considering using cursive instead.

I have tried grepping through your source code on a couple of your branches, and there appears to be some problems. But I'll let you sort that one out.

LANG=C.UTF-8
LANGUAGE=de:en_GB
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=de_DE.UTF-8

libncursesw5/focal,now 6.2-0ubuntu2 amd64  [installiert]
  shared libraries for terminal handling (wide character legacy version)

libncursesw5-dev/focal,now 6.2-0ubuntu2 amd64  [Installiert,automatisch]
  transitional package for libncurses-dev

**Comment by momozor** [comment]
Same. I can't compile the example code either with exact same error.

Using cursive version 0.14

**Comment by gyscos** [comment]
Thanks for the report!

The current git master branch has some breaking change; it will soon be released as 0.15.
Among these changes, it replaces `Cursive::default` with `cursive::default()`, which was not present in 0.14.

Note that to make the transition easier, I just released 0.14.1 which backports this method.

So:
* On 0.14.0 and before, use `Cursive::default()`
* On 0.14.1, the git master, and the future 0.15.0, use `cursive::default()`.
