### ISSUE TITLE
cursive::wrap_impl macro has hygiene issues

### ISSUE THREAD

**Issue by The0x539** [gyscos/cursive#458]
```rust
use cursive::view::ViewWrapper;
use cursive::views::DummyView;

use std::io::Result;

struct DummyWrapper{ inner: DummyView }

impl ViewWrapper for DummyWrapper {
    cursive::wrap_impl!(self.inner: DummyView);
}

fn main() {}
```
Should probably use fully qualified paths in macro bodies.

**Comment by gyscos** [comment]
Good point! Should be fixed on latest master.

**Comment by The0x539** [comment]
I think best practice is to also have a leading `::`, which *completely* prevents shadowing.
(Also missed `::std::marker::Sized`)

**Comment by gyscos** [comment]
Added the leading colons (does it prevent `extern crate fake_std as std;` though?)

**Comment by The0x539** [comment]
I believe that's exactly what it prevents.

**Comment by gyscos** [comment]
Nah I think this kind of crate import re-naming is just impossible to protect against.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=542af62d7946d866ead14bf70b19506a

Still, it should at least prevent most forms of shadowing. Importing a crate as `std` (without the usual std types there) is really asking for troubles.
