### ISSUE TITLE
Window resize event not firing

### ISSUE THREAD

**Issue by samtay** [gyscos/cursive#461]
First: is this a bug report? A suggestion? Or asking for help?
**Bug report**

# Problem description
Window resize event fails ~~within tokio runtime~~ after using `crossterm::event::read()`; see the next comment.

# Environment
* Operating system: Arch Linux
* Backend used: crossterm
* Current locale: en_US.UTF-8
* Cursive version: 0.15.0

# context
I'm not sure why this happens, but it does. I have a `View` that `wrap_on_event` listens to `WindowResize` and automatically handles the children view ratios. This worked fine, but after I added tokio and wrapped my `main` func with the `tokio::main` attribute, this event stopped firing. My code looks something like this
```rust
#[tokio::main]
async fn main() -> Result<(), Error> {
    // do a bunch of parallel and concurrent things
    let final_result = do_things.await;
    run_tui(final_result);
}
```
Where `run_tui` is not asynchronous and just does the normal `cursive::run()` stuff. It's a strange issue. Any ideas why this happens?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I think this may be a crossterm issue, but in general, window resizing is done by listening to a signal, and this can be thrown off by a number of things. Also I don't have a lot of experience with tokio, so I'm not quite sure how they interact.

**Comment by samtay** [comment]
Oh wow, sorry, I should have confirmed this was the actual issue before posting. I just did a binary search down my commit history, and found the real issue. I have this function
```rust
pub fn wait_for_char(c: char) -> Result<bool> {
    terminal::enable_raw_mode()?;
    let mut pressed = false;
    loop {
        match read()? {
            Event::Key(KeyEvent {
                code: KeyCode::Char(ch),
                ..
            }) if ch == c => {
                pressed = true;
                break;
            }
            Event::Key(_) => {
                break;
            }
            _ => (),
        }
    }
    terminal::disable_raw_mode()?;
    Ok(pressed)
}
```
which acts as a sort of prompt, where the user presses SPACE if they want to enter into the TUI. If I run this before the cursive app, resize events do not work. If I rip this out, they do work!

I thought it might have been the raw mode commands, but even after removing them, the problem persisted. Is there something up with my `loop` that somehow keeps capturing resize events, even after this function returns?

**Comment by gyscos** [comment]
Weird indeed.
Does this only affect Resize events?
One thing to check: what version of crossterm are you using? Is it the same as the one used by cursive?

**Comment by samtay** [comment]
It appears that all of the normal key and mouse events are working fine; I'm unaware of it affecting anything other than resize (then again my app isn't super complicated).

I'm on crossterm 0.17.5 and cursive 0.15.0, and it looks like that matches up with the cursive-0.15.0 lock file. 

I'm guessing this issue would be more appropriate to log on crossterm, but it's hard to say exactly what's going on wrong.. Seems like there's some internal crossterm state that's getting mishandled by the `read` function? Idk

**Comment by gyscos** [comment]
Does the UI resize itself (stays centered) when you resize the window?

I tried this simplified example, but it does re-position the central view correctly (and this require the `WindowResize` event):

```rust
fn main() {
    println!("Hello, world!");

    crossterm::terminal::enable_raw_mode();
    crossterm::event::read().unwrap();
    crossterm::terminal::disable_raw_mode();

    let mut siv = cursive::default();

    siv.add_layer(cursive::views::Dialog::text("foo"));

    siv.run();
}
```

**Comment by gyscos** [comment]
Maybe the main issue is that listening to `Event::WindowResize` changed recently, and is no longer forwarded to child views by default.

I can look into making it easier to process this, but taking a step back - why are you listening on this event? Why not use `View::layout` (or `ViewWrapper:wrap_on_layout` if you are writing a wrapper)?
`Event::WindowResize` is _rarely_ what you need. Other things can affect the size of a view apart from the window being resized (other views can change size, or you could add/remove other views). `View::layout` and `View::required_size` are usually the main place to react to this.

**Comment by samtay** [comment]
Okay, interesting find! Your example above does *not* work in my environment. Here is what happens when the screen is widened:
![2020-06-19-021912_831x387_scrot](https://user-images.githubusercontent.com/7246591/85117240-693c5980-b1d3-11ea-962c-f046f9fcf357.png) and shortened 
![2020-06-19-021928_680x390_scrot](https://user-images.githubusercontent.com/7246591/85117273-76594880-b1d3-11ea-95c5-af80718d15fc.png)

To your second point, I imagine you are correct, I am probably misusing your library in more ways than one. I am new to it and still kind of stumbling around. Currently, I have my own ViewWrapper implemented on kind of the "top layer" of my views. It contains 4 panes and maintains a certain ratio of the total screen size for each one (e.g 1:2 height, 1:1 width, etc.). This currently isn't possible with only the LinearLayout, since that deals with absolutes and not ratios of the current screen size.

So my layout view wrapper listens for `WindowResize` in its `wrap_on_event` simply to set `self.size_invalidated = true`. This is then checked by the `wrap_needs_relayout`, and if its invalidated, my `wrap_layout(size)` takes the `size` and divies up the appropriate ratios to the child views.

I think you are correct that I could probably just check if the size has changed since the last call, and use that to invalidate the layout. (Depending on the order of when `wrap_required_size` and `wrap_needs_layout` get called - I'm not sure). Instead of using the WindowResize event directly. However, given the results of your example program on my machine, it doesn't seem like this will fix my problem.

**Comment by gyscos** [comment]
Well, that's peculiar. It _sounds_ like Cursive isn't using the same crossterm as the one used to read the event (this would likely cause this issue) - one possible explanation is that cursive isn't using crossterm at all. What features are you using for `cursive`?

Here's the `Cargo.toml` for my example:

```toml
[package]
name = "cursive-test"
version = "0.1.0"
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = { version = "0.15.0", default-features = false, features=["crossterm-backend"] }
crossterm = "0.17.5"
```

**Comment by samtay** [comment]
Oh my god. I am *so* sorry! I forgot to set the cursive crossterm-backend feature. I guess it was just using the default, and I suppose if you run the crossterm `read()` that kind of clobbers the `/dev/tty` so that other backends won't be able to read from it? That's still not the behavior I would expect, but anyway, this fixes the issue! Sorry for the goose chase.

**Comment by gyscos** [comment]
No worries! Actually `/dev/tty` is (mostly) fine, the real problem is the signal detection which detects window resize event. `crossterm` sets it up the first time it is used, and doesn't currently provide a way to disable it.

If you want a very specific backend, you can use for example `cursive::crossterm()` instead of `cursive::default()`: this will make sure you are using the crossterm backend, and will fail to compile if the feature is missing (rather than silently switch to ncurses).
