### ISSUE TITLE
Temporarily "leaving" the curses mode

### ISSUE THREAD

**Issue by liushuyu** [gyscos/cursive#464]
I am asking for help.

# Problem description

Hi,

I am trying to figure out how to temporarily leaving the curses mode so that I can spawn a command-line program (for example, `bash`), and the user can interact with it.

I have searched the documentation and can't find a specific function to achieve this. The best I could think of was to save the current state, exit `Cursive` entirely using `siv.quit()` and when the external program is finished, a new `Cursive` instance is started. But I think this is too inconvenient and prone to mistakes.

During my research, I found out a library from another language contains such functionality: https://metacpan.org/pod/Curses::UI#leave_curses-(-) so I think `Cursive` should be able to do the same.

Did I miss something or `Cursive` currently does not have similar functionality?

Thanks!

# Environment

* Operating system: `Arch Linux (x86_64)`
* Backend used: `ncurses`
  * If using ncurses on linux, ncurses version? `6.2`
* Current locale
```bash
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```

* Cursive version `crates.io version 0.15.0`

**Comment by gyscos** [comment]
Hi, and thanks for the report!

This is a planned feature, however it's not currently available. See also #199 and #358.

Right now the only alternative is to stop cursive entirely (and drop the `Cursive` object); this will revert the terminal to normal; then start cursive again when desired.

Note that you can keep _views_ around even if you drop `Cursive`. `StackView::pop_layer` returns the view it removes, so you can pop all layers, save them, drop `Cursive`, run another program, create a new `Cursive`, and push the layers back.

**Comment by gyscos** [comment]
Note: to ease the "dump it all, bring it back", we could help define a `cursive::Dump` struct, and provide methods on `Cursive` to generate and load that.
It'd include the list of layers, the current global callbacks, and maybe would re-connect the callback sinks.

**Comment by liushuyu** [comment]
> Note: to ease the "dump it all, bring it back", we could help define a `cursive::Dump` struct, and provide methods on `Cursive` to generate and load that.
> It'd include the list of layers, the current global callbacks, and maybe would re-connect the callback sinks.

Thanks for your reply! Yeah, a `cursive::Dump` would be awesome to have! This opens up much more possiblities.



> Hi, and thanks for the report!
> 
> This is a planned feature, however it's not currently available. See also #199 and #358.
> 
> Right now the only alternative is to stop cursive entirely (and drop the `Cursive` object); this will revert the terminal to normal; then start cursive again when desired.
> 
> Note that you can keep _views_ around even if you drop `Cursive`. `StackView::pop_layer` returns the view it removes, so you can pop all layers, save them, drop `Cursive`, run another program, create a new `Cursive`, and push the layers back. (EDIT: just realized that's exactly what you're suggesting >_< )
> 
> It's far from ideal, so we still plan on adding proper "pause" support later on.

Right. Thanks for the links to the issues, and sorry for opening a duplicate issue report. I think I will stick to the original plan then.

Also thank you for making `Cursive`!

**Comment by gyscos** [comment]
Just added on master `Cursive::dump` and `Cursive::restore`. Tell me if it works for you!

**Comment by liushuyu** [comment]
> Just added on master `Cursive::dump` and `Cursive::restore`. Tell me if it works for you!

Will do with pleasure!

**Comment by liushuyu** [comment]
> Just added on master `Cursive::dump` and `Cursive::restore`. Tell me if it works for you!

Hi there, I just tried and it worked in my case (yay!). 

Although I have a complain which you might not be able to / want to address: because I used `siv.run()` in my main loop, the current dump/restore implementation does not allow me to do it easily in a callback (`Cursive` does not have `Copy` or `Clone`), thus I need to use a hack to pass a state to my `main` (telling that it's a pause, not a quit) to do something after the callback.

I understand the reason behind the current implementation, so if you are reluctant to make `dump` not moving out the reference, I am fine with the hacks.

Also, huge thanks for the incredibly fast implementation!

**Comment by gyscos** [comment]
On latest master `Cursive::dump` takes a `&mut self` instead of consuming `self`.

Note that the resulting `Cursive` instance will be cleaned out, like new.

**Comment by liushuyu** [comment]
> On latest master `Cursive::dump` takes a `&mut self` instead of consuming `self`.
> 
> Note that the resulting `Cursive` instance will be cleaned out, like new.

Thanks for the changes! Now it works like a charm in my case.

Because I need to reset the terminal, I need to `drop` the previous instance anyways. So I am not worried about the previous instance being wiped clean.

**Comment by Szpadel** [comment]
Is there any way to restore terminal without dropping Cursive?
