### ISSUE TITLE
[Help request] TextView, scrolling and focus

### ISSUE THREAD

**Issue by HenryTheCat** [gyscos/cursive#465]
I know this is a silly question, but I can't figure it out from the documentation. I have a `TextView` I want to use as a log. The naive attempt is to `append` strings to it. After the `TextView` is filled, though, it doesn't scroll down and newly appended strings can't be seen. Then, what I do is to wrap the `TextView` in a `ScrollView`, set the scroll strategy to `StickToBottom`, and even hide the scrollbar.

```Rust
ScrollView::new(NamedView::new("log", TextView::new("Hello world!")))
    .scroll_strategy(ScrollStrategy::StickToBottom)
    .show_scrollbars(false)
```

Still, I have the issue that the users can accidentally focus on the `TextView` while using the arrow keys and start scrolling up and down when they meant to do something else. I don't really need the view to get focus or to remember but the last few lines that were appended.

Is there a simple solution to this that would not involve writing a custom view?

Version: Cursive 0.15.0

**Comment by gyscos** [comment]
If you don't want the view to receive any event, you can wrap it in an `OnEventView`, then use `on_pre_event_inner` to disable all events:

```rust
let text = TextView::new();

let no_input = OnEventView::new(text)
        .on_pre_event_inner(
            EventTrigger::any(), 
            |_, _| Some(EventResult::Ignored)
        );
```

**Comment by HenryTheCat** [comment]
Thank you! What you suggested works at making the `TextView` unresponsive. Though, the `TextView` can still get focus. I came to realize that my issue was not with the `TextView` getting focus, but my other custom view loosing it. The root of the issue was returning `EventResult::Ignored` in the `on_event` method for the custom view. Having replaced those with `EventResult::Consumed` the view does not loose focus anymore and I get the desired behaviour. Of course, all of this is well documented in the package's documentation, and it's only my fault for not seeing it earlier.

Thanks again for the assistance, I will close the issue here.

**Comment by gyscos** [comment]
Ay indeed, blocking events will not block taking focus :^S

(You'd need to override `View::take_focus`), and there's currently no easy wrapper for that. Shoot.
