### ISSUE TITLE
Finder::call_on_name() with mut access to Cursive instance?

### ISSUE THREAD

**Issue by matthiasbeyer** [gyscos/cursive#466]
*A suggestion / Asking for help*

# Problem description

So I have the problem that I need to create a View and put it into Cursive in `call_on_name()`. For that, though, I need `&mut Cursive`, which I cannot have in the closure passed to `call_on_name()`.
Conceptually, I have a "Sidebar" that is a list of directories. As soon as one is selected, I want to open a view in the "main" window (with cursive-tabs) that loads the selected directory (async via cursive-async-view, but that shouldn't matter for this issue).

Is there a pattern to use here, or is it simply not possible with the current API?

Related: https://github.com/deinstapel/cursive-async-view/issues/6
My code (WIP): 
* https://git.sr.ht/~matthiasbeyer/muar/tree/async-view/src/sidebar.rs#L57
* https://git.sr.ht/~matthiasbeyer/muar/tree/async-view/src/main_view.rs#L71

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Usually you would return something from `call_on_name` and add it to `Cursive` outside of the function.

**Comment by matthiasbeyer** [comment]
Awesome, that worked!
