### ISSUE TITLE
View always has a shade

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#470]
Hi, I'm learning rust and in order to do that I've decided to create an terminal application like mc but using Cursive. I'm using cursive views in order to present the folder content to the user. Is there a way to not have a shade under the view so the view can actually fit the entire screen?
Thank you
![Cursive_Shade](https://user-images.githubusercontent.com/3456691/87845672-ab87b200-c8c9-11ea-8369-86a87e5f8b11.png)

**Comment by gyscos** [comment]
Hi, and thanks for the report!

You may be interested in [`Cursive::add_fullscreen_layer()`](https://docs.rs/cursive/0.15.0/cursive/struct.Cursive.html#method.add_fullscreen_layer). You can also check the [`lorem` example](https://github.com/gyscos/cursive/blob/main/examples/src/bin/lorem.rs) which uses it.

**Comment by smallB007** [comment]
Hi there!
Thanks so much for such a quick reply.
Will definitely check that out!
Best regards and have a nice weekend!
