### ISSUE TITLE
Having cursive_table_view fit entire dialog

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#473]
Hi, is there a way so the cursive_table_view is actually fitted in entire dialog so the columns are drawn from top right down to the bottom even if the number of items is not large enough to fill entire view?
Pic will show what I mean:
![Screenshot at 2020-07-20 07-35-39](https://user-images.githubusercontent.com/3456691/88033116-3a513480-cb3f-11ea-903b-1aad783829a0.png)

**Comment by gyscos** [comment]
Hi, and thanks for the report!

It's totally doable, but it's something `cursive_table_view` should implement.
