### ISSUE TITLE
Missing methods to change min/max values of `&mut ProgressBar`

### ISSUE THREAD

**Issue by j-tai** [gyscos/cursive#476]
First: is this a bug report? A suggestion? Or asking for help? Bug report/suggestion

# Problem description

For a `&mut ProgressBar`, there are no methods to set its `min` and `max` values. The only methods to change their values (`min(self, usize)`, `max(self, usize)`) take ownership of the ProgressBar, which is not possible if you have a reference.

Workaround: to gain ownership, create a "dummy" progress bar and use `mem::swap`, or use unsafe code:

```rust
let progress_bar: &mut ProgressBar = ...;
// This is safe because we have exclusive (&mut) access
unsafe {
    use std::ptr;
    let mut value = ptr::read(progress_bar);
    value = value.max(new_max);
    ptr::write(progress_bar, value); // This consumes 'value' so it is not dropped twice
}
```

# Environment

* Operating system: Arch Linux
* Backend used: ncurses
  * If using ncurses on linux, ncurses version? 6.2
* Current locale (run `locale` in a terminal). en_CA.UTF-8
* Cursive version (from crates.io, from git, ...) main branch

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, looks like a gap in the API!

**Comment by gyscos** [comment]
Latest commit should now bring `set_{min,max,range,label,counter}` to bring parity with the chainable functions.
