### ISSUE TITLE
Help implemeting a layout with percentages using FixedLayout and OnLayoutView.

### ISSUE THREAD

**Issue by jaygazula27** [gyscos/cursive#478]
First: is this a bug report? A suggestion? Or asking for help?
Asking for help.

# Problem description

This is a continuation of the discussion in this [issue](https://github.com/gyscos/cursive/issues/370). I did not want to derail that thread.  
  
I'm trying to create a UI where we have three panels/views. The left panel takes up ~40% width and the right panel takes up ~60% width. Both the left and the right panels have a height of ~90%. Then we also have a bottom panel which takes up 100% width but takes up the bottom 10% of the screen. In case this description is unclear, I have a screenshot below.

Using the FixedLayout and OnLayoutView idea that you had suggested, I came up with the following:

```
use cursive::view::SizeConstraint;
use cursive::views::{FixedLayout, OnLayoutView, Panel, ResizedView, TextView};
use cursive::Cursive;
use cursive::{Rect, Vec2};

fn main() {
    let mut siv = cursive::default();
    render(&mut siv);
    siv.run();
}

fn render(siv: &mut Cursive) {
    let left_panel = Panel::new(TextView::new("left"));
    let right_panel = Panel::new(TextView::new("right"));
    let bottom_panel = Panel::new(TextView::new("bottom"));

    let resized_view = ResizedView::new(
        SizeConstraint::Full,
        SizeConstraint::Full,
        FixedLayout::new()
            .child(Rect::from_size((0, 0), (1, 1)), left_panel) // dummy sizes since they'll get overridden in OnLayoutView?
            .child(Rect::from_size((0, 0), (1, 1)), right_panel)
            .child(Rect::from_size((0, 0), (1, 1)), bottom_panel),
    );

    let view = OnLayoutView::new(resized_view, |v, s| {
        let fixed_layout = v.get_inner_mut();

        let left_panel_top_left = Vec2::new(0, 0);
        let left_panel_bottom_right =
            Vec2::new((s.x as f32 * 0.4) as usize, (s.y as f32 * 0.9) as usize);
        let left_size = Rect::from_corners(left_panel_top_left, left_panel_bottom_right);
        fixed_layout.set_child_position(0, left_size);
        let left_panel = fixed_layout.get_child_mut(0).unwrap();
        left_panel.layout(left_size.size());

        let right_panel_top_left = Vec2::new((s.x as f32 * 0.405) as usize, 0);
        let right_panel_bottom_right = Vec2::new(s.x, (s.y as f32 * 0.9) as usize);
        let right_size = Rect::from_corners(right_panel_top_left, right_panel_bottom_right);
        fixed_layout.set_child_position(1, right_size);
        let right_panel = fixed_layout.get_child_mut(0).unwrap();
        right_panel.layout(right_size.size());

        let bottom_panel_top_left = Vec2::new(0, (s.y as f32 * 0.905) as usize);
        let bottom_panel_bottom_right = Vec2::new(s.x, s.y);
        let bottom_size = Rect::from_corners(bottom_panel_top_left, bottom_panel_bottom_right);
        fixed_layout.set_child_position(2, bottom_size);
        let bottom_panel = fixed_layout.get_child_mut(0).unwrap();
        bottom_panel.layout(bottom_size.size());
    });

    siv.add_fullscreen_layer(view);
}
```

This code gets me very close to what I want:
![cursive](https://user-images.githubusercontent.com/7519114/88468855-47f81880-ceb7-11ea-96c5-9465f327b043.png)

However, as you can see, only the left panel is rendering the view within it. The right panel and the bottom panel have no text (they each should render a TextView). I've been messing around for quite a bit and I've been unable to figure out what I'm doing wrong. One thing I noticed is that if I comment out the left panel child, the right panel gets rendered properly. This makes me think the left panel is somehow interfering with the other panels even though the borders don't overlap?  Not sure. 

How can I ensure that all the views get rendered properly? 
 
p.s. I know this code can be refactored quite a bit, but I extracted every single thing into a variable since I was experimenting. I also hardcoded the percentages. Hopefully this doesn't make things confusing. Please let me know if it does.

# Environment

* Operating system: Ubuntu 20.04
* Backend used: Crossterm
* Current locale: en_US.UTF-8
* Cursive version: 0.15.0

**Comment by gyscos** [comment]
Hi!

When wrapping the `layout` call, it is your responsibility to call `layout` on the wrapped view - but you only need to call it on the _directly_ wrapped view, not on each child individually.

```rust
    let view = OnLayoutView::new(resized_view, |v, s| {
        let fixed_layout = v.get_inner_mut();

        let left_panel_top_left = Vec2::new(0, 0);
        let left_panel_bottom_right =
            Vec2::new((s.x as f32 * 0.4) as usize, (s.y as f32 * 0.9) as usize);
        let left_size = Rect::from_corners(left_panel_top_left, left_panel_bottom_right);
        fixed_layout.set_child_position(0, left_size);

        let right_panel_top_left = Vec2::new((s.x as f32 * 0.405) as usize, 0);
        let right_panel_bottom_right = Vec2::new(s.x, (s.y as f32 * 0.9) as usize);
        let right_size = Rect::from_corners(right_panel_top_left, right_panel_bottom_right);
        fixed_layout.set_child_position(1, right_size);

        let bottom_panel_top_left = Vec2::new(0, (s.y as f32 * 0.905) as usize);
        let bottom_panel_bottom_right = Vec2::new(s.x, s.y);
        let bottom_size = Rect::from_corners(bottom_panel_top_left, bottom_panel_bottom_right);
        fixed_layout.set_child_position(2, bottom_size);

        v.layout(s);
    });

```

**Comment by jaygazula27** [comment]
Ah, didn't realize I just had to call the `layout` method on the wrapped view only.
And damn, that's an embarrassing mistake on my part regarding calling `get_child_mut` on the same child. 

This fixed my issue. Thanks for the help again!
