### ISSUE TITLE
Get active view

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#479]
First: is this a bug report? A suggestion? Or asking for help?
Ask for help.

How to get currently active view? I assume cursive have it stored somewhere but I couldn't find it.

Thanks

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Cursive has currently no generic way to get "whatever view is active".

However, most view group provide a way to get their current focus. For example, `LinearLayout::get_focus_index`. For `StackView`, it's always the last layer.
Most of the time, you're interested in the currently active item _within a specific parent_.

There is a long~ish plan to bring `ViewPath` for more view-tree exploration, and a function to retrieve the viewPath for the current focus would probably come with it, but it's not planned for the short term.

**Comment by smallB007** [comment]
Hi, thanks for the reply.
What if linearLayout has two views in it and I'm interested in the one that is actually active? Just like file explorer has two panes, those two panes are in the same linearlayout but one of them is in the focus and the other is not. How would I achieve that, that is how would I get that info about currently active view on the same layout? Example would be great.

**Comment by smallB007** [comment]
Thanks, that would be actually what I need. Really appreciated.

**Comment by gyscos** [comment]
I'll close this for now, feel free to re-open if you have further questions!
