### ISSUE TITLE
[Help] Ability to disable mouse support?

### ISSUE THREAD

**Issue by jansc** [gyscos/cursive#482]
I'm not sure if this is possible, help needed.

# Problem description

I'd like to turn off mouse support for my application. The reason I want to do this is that I'd like to able to select text from within my application for copy&paste.

Rationale: My gemini/gopher-client "ncgopher" presents a lot of markdown and otherwise text-formatted content. I'd like users to be able to copy e.g. URLs from within text. For text rendering, I currently use a SelectView. The URLs are usually only a part of a line in the SelectView. Clicking with the mouse will change the selected row, but it will not let me select text like in other terminal applications.

# Environment

* Operating system: Arch Linux
* Backend used: pancurses, ncurses 5.9
* Current locale:
```
LANG=nb_NO.UTF-8
LC_CTYPE="nb_NO.UTF-8"
LC_COLLATE="nb_NO.UTF-8"
LC_TIME="nb_NO.UTF-8"
LC_NUMERIC="nb_NO.UTF-8"
LC_MONETARY="nb_NO.UTF-8"
LC_MESSAGES="nb_NO.UTF-8"
LC_ALL=
```
* Cursive version 0.15.0

**Comment by gyscos** [comment]
Hi, and thanks for the report!

We may add some special backend initializer that omit the mouse mode part.
In the meanwhile, many terminal emulators let you ignore mouse mode by pressing "Shift". For example on gnome-terminal, you can press Shift+Ctrl and drag around for a block select, even with "mouse mode applications" (like vim or cursive). On Konsole, block select is Ctrl+Alt+drag, so Shift+Ctrl+Alt+drag will let you block-select in cursive applications.

Most of the time this is the preferred way, as it let users use the mouse for interaction, and ignore mouse mode for selecting the text.

**Comment by jansc** [comment]
Thanks for the quick response! I was not aware of the "Shift" modifier. Works fine in my terminal, so I'm closing the issue.
