### ISSUE TITLE
Scrollable SelectView issues inside LinearLayout

### ISSUE THREAD

**Issue by codingkoi** [gyscos/cursive#487]
Bug Report

# Problem description
When you put a scrollable SelectView inside of a LinearLayout, the mouse controls for the scrolling become broken.

I've created a small repro case here. Not sure if this is Windows 10 specific though (see env details below).

In the first layer, you'll notice that the mouse wheel doesn't scroll down properly (only seems to scroll the top item) and that if you scroll manually with the scrollbar and click on an item further down (after the selected item is off the screen) then it jumps back up to a different item than the one you clicked on.

In the second layer (after you click the "next" button), you'll see that it works as expected.

I've tried looking into this, but I'm new to Rust so I'm not having much luck. Am I missing something obvious? Apologies if this has already been reported. I didn't find anything while searching.

```rust
use cursive::traits::{Resizable, Scrollable};
use cursive::views::{Button, LinearLayout, Panel, ResizedView, SelectView};
use cursive::{Cursive, CursiveExt};

fn main() {
    let mut siv = Cursive::default();
    make_broken_scrolling(&mut siv);
    siv.add_global_callback('q', |siv| siv.quit());
    siv.run();
}

fn create_select_view() -> ResizedView<SelectView> {
    let select = SelectView::<String>::new();
    let items = (0..100).map(|i| i.to_string()).collect::<Vec<String>>();
    select.with_all_str(items).fixed_width(30)
}

fn make_broken_scrolling(siv: &mut Cursive) {
    let select = create_select_view();
    let view = LinearLayout::vertical()
        .child(select.scrollable())
        .child(Button::new("Next", make_working_scrolling));
    siv.add_layer(Panel::new(view).title("Broken Mouse Scrolling"));
}

fn make_working_scrolling(siv: &mut Cursive) {
    siv.pop_layer();
    let select = create_select_view();
    let view = select.scrollable();
    siv.add_layer(Panel::new(view).title("Working Mouse Scrolling"));
}
```

# Environment

* **Operating system:** Windows 10
* **Backend used:** Crossterm and BLT both exhibit this behaviour
* **Cursive version:** 0.15.0 (I have `*` set in my Cargo.toml while developing)

**Comment by jansc** [comment]
Your example works fine on Linux (Arch/Manjaro) with cursive 0.15.0, crossterm backend.

**Comment by codingkoi** [comment]
Hmm, I wonder what's different about Windows that would be causing the difference.  Here's what I'm seeing (using Crossterm, but it also does it in BTL).
![screencapture](https://user-images.githubusercontent.com/28966/90410603-2fbb8980-e070-11ea-81f6-57d2fe0d7d6f.gif)

**Comment by gyscos** [comment]
I confirm I can reproduce the bug on linux running the default `ncurses` backend. Dragging the scrollbar works fine, but things go wrong the moment the mouse wheel is used - very weird, will investigate.

**Comment by codingkoi** [comment]
I want to point out the part where I pick item 50 and end up with item 16 selected. That might be a symptom of the underlying problem. This happens whether you use the scroll wheel or not. It also only happens when the current selection is not in the visible list of items.

**Comment by gyscos** [comment]
At least one problem was with the way `ScrollView` handled some focus changes caused by mouse events.
I just pushed a possible fix, it seems to help in this case.

**Comment by codingkoi** [comment]
That definitely fixes the issues I'm seeing here. Thanks!

**Comment by gyscos** [comment]
Should be deployed as part of 0.16.0.
