### ISSUE TITLE
`call_on_name` does not work for ScreensView

### ISSUE THREAD

**Issue by JoshMcguigan** [gyscos/cursive#491]
First: is this a bug report? A suggestion? Or asking for help?

bug report

# Problem description

I was trying to use a `ScreensView` compontent to switch between a couple different views within some small part of a dialog box. I setup global callbacks to `set_active_screen`, but it seems `call_on_name` does not find the `ScreensView` component. I believe this is due to how the `ViewWrapper`  trait defines `wrap_call_on_any`. It seems forwards that call directly to the children of the `ScreensView`, but doesn't actually check whether the `ScreensView` itself matches the selector.

# Environment

* Cursive version - crates.io 0.15

Thanks for all your work on this crate!

**Comment by gyscos** [comment]
Should be fixed with ad935f5126ed5ac763b57e3c08a73bd3d69676df.

**Comment by JoshMcguigan** [comment]
I haven't had a chance to try it out yet, but will that fix the situation where the `ScreensView` itself is named? My reading of it suggests that change only handles the case where the screens within a `ScreensView` are named (due to iterating over `self.screens`), but I haven't studied this code base much so I could be off here.

Thanks for your quick response btw!

**Comment by gyscos** [comment]
Hmm that should already have worked. Note that `ScreensView` is a generic, so you'll need to call it with the same generic type in case it isn't the default (`BoxedView`).

**Comment by JoshMcguigan** [comment]
Ah, there is a good chance that was my issue. I'm not sure exactly how the default generic type vs type inference would play out in the code that I had, since I think I was doing `ScreensView::new()` and then adding two views which would have had the exact same type. 

Unfortunately I've worked around this in another way for now so I don't have an easy way to test it, but I'll assume this is the explanation. 

Thanks again for yoru quick feedback. I'll go ahead and close this now as resolved.
