### ISSUE TITLE
Publish newest version of cursive & cursive-core to crates.io to fix scrollable select view bug

### ISSUE THREAD

**Issue by JoshMcguigan** [gyscos/cursive#497]
First: is this a bug report? A suggestion? Or asking for help?

Suggestion / asking for help

# Problem description

I was debugging an issue where a scrollable select view would not select the proper value after scrolling. I was able to re-create the issue on the `select` example, by compiling that example against cursive `0.15` from crates.io, but the issue does not exist in the latest master branch.

Unfortunately, pointing my project to the git version of cursive does not seem to fix the issue. I suspect this is because even that git versions pulls in the crates.io version of `cursive-core`, where I believe the fix is. I did confirm that my project works properly if I pull down the cursive repo and point my project directly to the latest versions of `cursive` and `cursive-core`.

Given this, I believe if the latest version of `cursive-core` was uploaded to crates.io, and then `cursive` was updated to point to that version, and then `cursive` itself was updated on crates.io, that would fix this issue.

Thanks again for your work on this crate! It has been a huge productivity boost!

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The past few weeks have been pretty crazy, but I should finally be able to find some free time and push a new version soon~ish...

**Comment by gyscos** [comment]
Well, it only took 4 months, but it's now published... <_<

**Comment by JoshMcguigan** [comment]
Thanks for the release, and again for your work on this crate!
