### ISSUE TITLE
Suggestion: Template on user data type

### ISSUE THREAD

**Issue by nothien** [gyscos/cursive#498]
Instead of using `Box<dyn Any>` to be able to store anything as user data, perhaps make the `Cursive` structure a template on the user data type (defaulting to `Box<dyn Any>` for compatibility)?  This would be much faster than dealing with memory allocation, works well for most users of `cursive` (who use a single userdata type and assume it's always there), and would remove a lot of `unwrap()`s.

What it might look like:
```rust
pub struct Cursive<UserData = Box<dyn Any>> {
    // ...
    user_data: UserData,
    // ...
}

impl<UserData> Cursive {
    fn new(user_data: UserData) -> Self {
        // ...
    }

    fn user_data(&mut self) -> Option<&mut UserData> {
        // ...
    }
}

impl Cursive<Box<dyn Any>> {
    fn new() -> Self {
        // ...
    }

    fn user_data<T>(&mut self) -> Option<&mut T> {
        // ...
    }
}
```

The primary drawback is that this could break preexisting code.  Most of the issues in this area could be put off by adding specializing functions for `Cursive<Box<dyn Any>>` (although I'm forgetting about the stability of specialization atm).

If breaking changes are possible, it would also be nice to move `user_data()` to `user_data_mut()` and make `user_data()` work immutably.

I may make a PR for this, but I wanted to put the idea out there to see if there are any similar ideas or attempts.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Unfortunately making `Cursive` generic on the stored user data type would bring a few issues. Callback types would need to be generic on this too, and so would the `View` trait. It would show up everywhere, adding a generic type to almost any type/functions throughout the library. It may also complicate type inference for closures taking a `&mut Cursive<T>`.

> This would be much faster than dealing with memory allocation

While _storing a new data_ would be faster, accessing it would not be very different. We can also add methods to let users re-use the existing `Box` allocation, so they don't _have_ to keep re-allocating.

Overall I suspect it would be a lot of changes and a non-negligible impact on user experience, for little gains. It's always possible to ignore this user data entirely and build your own highly-efficient single-type shared storage, for cases where the current situation is not appropriate.

**Comment by nothien** [comment]
Oh yeah, I didn't realise that it would affect _everything_.  Oh well.

In any case, thank you for maintaining such an awesome UI library!
