### ISSUE TITLE
Missing text with LinearLayout combos

### ISSUE THREAD

**Issue by ph0llux** [gyscos/cursive#504]
Okay, I think I found a bug. Unfortunately I can't do any debugging on it, but I created a simple minimal example and made a screenshot. 
If I execute the following code (both with termion backend and cross-term backend):
```
extern crate cursive;


use cursive::views::{Dialog, LinearLayout, TextView};
use cursive::Cursive;

fn main() {
    let mut cursive_root = cursive::default();
    menu_primary_level(&mut cursive_root);
    cursive_root.run();
}

fn menu_primary_level(cursive_root: &mut Cursive) {
    let mut primary_layer = LinearLayout::vertical();
    for i in 1..6 {
        let round = format!("Round number {}", i);
        primary_layer = primary_layer
        .child(Dialog::around(
            menu_2nd_level())
        .title(round));
    }
    cursive_root.add_layer(primary_layer);
}

fn menu_2nd_level() -> LinearLayout {
    LinearLayout::vertical()
    .child(Dialog::around(
        menu_3rd_level())
    .title("2nd level"))
}

fn menu_3rd_level() -> LinearLayout {
    LinearLayout::vertical()
    .child(Dialog::around(
        TextView::new("My example text"))
    .title("3rd level"))
}
```
then I get an output like in the screenshot. As you can see in the "last round", the text is missing. This is the case for any number of rounds, but always only for the last round.
![bugreport_cursive_01](https://user-images.githubusercontent.com/48868662/93902902-62ecda80-fcf8-11ea-91d7-3622168df8ab.png)

### Environment
Debian GNU/Linux testing/bullseye

**Comment by gyscos** [comment]
Hi! This is interesting - testing this code locally, I get the full test visible (as long as the terminal window is tall enough).

![Screenshot from 2020-09-22 09-28-56](https://user-images.githubusercontent.com/564903/93910524-0e287000-fcb6-11ea-9514-066d1fffbafe.png)

Could the terminal window be _just too short_? By default it will always try to keep 1 row on top and 1 row on the bottom - if that's a problem, we can find a way to skip that.

**Comment by ph0llux** [comment]
Phew, you're probably right.
If I zoom out of the window, I can see the text. I usually zoom in a little bit (or a "big" bit) on the terminal window, so I didn't even notice that.

Ok, then I have to find a solution for that.

Thanks for the hint and of course for this great library. :)

**Comment by gyscos** [comment]
> But it's kind of strange that only on the last round is something cut off, isn't it?

It depends on how much space is missing to show everything. If you shrink the terminal a bit more, you will see more and more text being cut off.

Here are examples with different terminal heights:

![Screenshot from 2020-09-22 12-14-16](https://user-images.githubusercontent.com/564903/93927060-31124e80-fccd-11ea-9bb9-73470be6173c.png)
![Screenshot from 2020-09-22 12-14-19](https://user-images.githubusercontent.com/564903/93927061-31aae500-fccd-11ea-8458-f5eb11005317.png)
![Screenshot from 2020-09-22 12-14-28](https://user-images.githubusercontent.com/564903/93927062-32437b80-fccd-11ea-8a44-4b7577a1c2f6.png)

**Comment by ph0llux** [comment]
Okay, then I just have to find a way to make sure that nothing gets cut off (i.e. to determine a kind of "min term size").
Is there already something?

**Comment by gyscos** [comment]
This is what the `required_size` methods from the `View` trait does. You can call it on the currently active screen `siv.screen_mut().required_size(constraings)`.

The value of `constraint` can be used to control how the view will strecth, if any:
* Giving a very small value (like `Vec2::zero()`) will try to get the smallest possible size. If any view is scrollable, it will try to shrink to the minimum size.
* Given a large value, it will expand to this value _if necessary_.

So ideally you would give as constraint either the maximum terminal size you can accept.

**Comment by ph0llux** [comment]
OK, thanks for all information.
I'll try this out tomorrow. 💪

**Comment by gyscos** [comment]
I'll close this for now, feel free to re-open if you have further questions!
