### ISSUE TITLE
quitting takes long

### ISSUE THREAD

**Issue by alx365** [gyscos/cursive#505]
# Problem description
In my current project, a sudo alternative in rust, with a optional tui, after prompting for a password, i immediately start a subprocess with the execve syscall. But the screen doesn't get cleared completely, leading to this: 
![image](https://user-images.githubusercontent.com/30902201/94849505-0b93ec00-0415-11eb-9ccc-11da8cbbb90e.png)

Snippet from the code:
```rust
Dialog::new()
            .title(format!("Enter password for user {}", user))
            .padding_lrtb(1, 1, 1, 0)
            .content(
                EditView::new().on_submit(move |s: &mut cursive::Cursive, password: &str| {
                    let is_match = match hash_struct.format {
                        1..=6 => decode(&hash_struct, password.to_string()),
                        _ => panic!("unknown encryption method (╯°□°）╯︵ ┻━┻"),
                    };
                    if is_match {
                        s.quit();
                       // [...]
                        crate::do_the_actual_thing(args.to_vec());
                    }
// Left out some brackets...
```
I have also tried to clear the screen before hand, refresh it and then quit. Didn't make a difference.

# Environment

* GNU/Linux
* backend: ncurses
  * ncurses version: 6.2
* Locale:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
* Latest cursive version

**Comment by gyscos** [comment]
Hi, and thanks for the report!
As you noticed, calling `Cursive::quit` does not quit instantly, but merely signals that the event loop should stop.
If you want to run code after Cursive has cleaned up, you'll want to run the actual thing _after_ `Cursive::run`.

Actually, I think on the crates.io version, you'll also need to `drop` the cursive instance (_that_ is what will clean the terminal). On the latest master it should clean up the terminal when returning from `Cursive::run`.

**Comment by alx365** [comment]
Issue is, i can't call any code after it, as i can't capture if the password was sucessful or not. I can't change any vars outside of the closure.

**Comment by gyscos** [comment]
You can "send" the parameters out of the closure in a few ways:
* Share a `Rc<Cell<T>>` (or `Rc<Cell<Option<T>>`) with the outside code and store the value there. Can also be a channel.
* Store the values you want to keep in cursive's user_data field and fetch it back afterwards.

**Comment by alx365** [comment]
The user data worked. Thanks!
