### ISSUE TITLE
Styling individual words in a textview

### ISSUE THREAD

**Issue by Exodus76** [gyscos/cursive#506]
First: is this a bug report? A suggestion? Or asking for help?
asking for help

# Problem description
I am trying to style individual words of a text in a textview whenever **on_edit** calls a function, Is there any way I can get them Individually and set style for just a word one by one.
I've looked at **IndexedSpan** but I cant figure out how to use it (if it's even the solution)

If possible code, or pseudo-code to reproduce the problem / present an idea.
```
let mut styled = StyledString::plain("Isn't ");
    styled.append(StyledString::styled("that ", Color::Dark(BaseColor::Red)));
    styled.append(StyledString::styled(
        "cool?",
        Style::from(Color::Light(BaseColor::Blue)).combine(Effect::Bold),
    ));

TextView::new(styled)

EditView::new().on_edit( function() );

function() {  //changes the effects/color of styled }

//how do i get and change the styling for the words from styled var individually 
```

# Environment
OS: windows
Backend: crossterm
cursive version: using the latest git version

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Right now unless you just want to append, there's no way to just "mutate" the content of a `TextView`; you need to set it again with `set_content`. This means you'll need to:
* Fetch the existing text content.
* Create a new content based on the existing one (and modify it in the process).
* Set the new content.

To build the new content (a `StyledString`, which is just an alias for `SpannedString<Style>`), we can iterate on the existing "spans" of the existing content, and either add it as-is to our new content, or change it. Here's a working example:

```rust
use cursive::{
    theme::{BaseColor, Color, Effect, Style},
    traits::*,
    utils::markup::StyledString,
    views,
};

fn main() {
    let mut siv = cursive::default();

    let mut styled = StyledString::plain("Isn't ");
    styled.append(StyledString::styled("that ", Color::Dark(BaseColor::Red)));
    styled.append(StyledString::styled(
        "cool?",
        Style::from(Color::Light(BaseColor::Blue)).combine(Effect::Bold),
    ));

    siv.add_layer(views::Dialog::around(
        views::LinearLayout::vertical()
            .child(views::TextView::new(styled).with_name("text"))
            .child(views::EditView::new().on_edit(on_edit)),
    ));

    siv.run();
}

fn on_edit(s: &mut cursive::Cursive, edit_text: &str, _cursor: usize) {
    s.call_on_name("text", |t: &mut views::TextView| {
        let mut new_content = StyledString::new();
        for span in t.get_content().spans() {
            let new_style = if edit_text == span.content {
                Style::from(Effect::Bold)
            } else {
                *span.attr
            };
            new_content.append_styled(span.content, new_style);
        }
        t.set_content(new_content);
    });
}
```

In this example every time you type an exact span, it becomes bold instead. Though it's very primitive and only works at the span level. You'll probably want something smarter where you can match subsets of a span, or across spans, or something else entirely.

**Comment by Exodus76** [comment]
Thank you! that is exactly what i wanted to know. Thanks for this cool library.
