### ISSUE TITLE
Dead links for source code in documentation

### ISSUE THREAD

**Issue by robinwils** [gyscos/cursive#507]
There is a bug inside the documentation, when trying to access the source code for most definitions

# Problem description

When going to: https://docs.rs/cursive/0.15.0/cursive/views/struct.TextView.html and trying to click on [src] links, an error page shows up. This happens for a lot of definitions.

# Environment
* Operating system: macOS
* Browser: Firefox Developer Edition 82.0b6

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I messed up the doc links for that release; it's  fixed on master, so the next release shouldn't have this problem. _Just got to release something..._

**Comment by robinwils** [comment]
Alright, thanks for the info !
Is there a way to see the master version of the doc online ?

**Comment by gyscos** [comment]
You can fetch the repo and open the doc locally?
```bash
git clone https://github.com/gyscos/cursive && cd cursive && cargo doc --open
```

I don't know of a service like docs.rs that builds doc from git repos, but if there's one I'd love to learn about it!

**Comment by gyscos** [comment]
With cursive 0.16 published, the source links should now work better.
