### ISSUE TITLE
Event::CtrlShift(char)?

### ISSUE THREAD

**Issue by TianyiShi2001** [gyscos/cursive#516]
Question: Currently (in the latest master branch) it seems that only `Event::Shift(char)` and `Event::CtrlShift(<non-character-key>)`, but not `Event::CtrlShift(char)`, can be processed. Is it going to be implemented in the future? Are there any workarounds for now?

This feature would be helpful to me because I'm implementing a sudoku game, and it is conventional to map `Ctrl + Z` to undo and `Ctrl + Shift + Z` to redo.

```
Event::CtrlChar('z') => self.undo(),
Event::CtrlChar('Z') => self.redo(), // tried this, doesn't work
Event::CtrlShift(Key::???) => self.redo(), // Key::Char?
```

BTW can #503 be merged? I was a bit late for the final comment, bit I think it's ready to be merged.

**Comment by gyscos** [comment]
Hi, and thanks for the PR!

Unfortunately I don't think terminal application can tell the difference between C-z and C-Z: in both cases the same input code is sent by the terminal emulator (this is why there is no `Event::CtrlShift(char)`, to prevent the confusion from this never happening). One of the limitations of terminals... :(

**Comment by TianyiShi2001** [comment]
Thank you!
