### ISSUE TITLE
Make scroll speed configurable

### ISSUE THREAD

**Issue by robinkrahl** [gyscos/cursive#517]
This is a feature request.

# Problem description

Currently, a `ScrollView` moves five lines on Page Up and Page Down (`cursive_core/src/view/scroll/core.rs`, lines 301 and 308).  This is a very slow scroll speed for a large view.  For comparison, in vim Page Up and Page Down scroll by *y* – 2 lines, where *y* is the height of the buffer.

This could be improved by making the scroll speed configurable via a callback that receives the current height of the view as an argument.

**Comment by gyscos** [comment]
Hi!
In the latest commit I added a few functions to the scroll core, which should make it easier to add this behaviour as an add-on - I updated the lorem example to do just that: https://github.com/gyscos/cursive/blob/8003fc177386e4f2706e86411417e08b1fc7a0a3/examples/src/bin/lorem.rs#L25

**Comment by robinkrahl** [comment]
Great, thank you!
