### ISSUE TITLE
Composable UI

### ISSUE THREAD

**Issue by matthiasbeyer** [gyscos/Cursive#52]
I watch development of this crate rather interested for some weeks now and I think this could be the crate I want to use to implement a ncurses-UI for my [imag](https://github.com/matthiasbeyer/imag) project. 

The point is: imag is a program (or rather collection of programs) that gets composed from components, and I want to continue it this way also when implementing a ncurses UI for it.

So for example if I implement a CUI for `imag-diary` I still want to be able to re-use the code I've written for this UI to integrate the UI into a more general UI.

Think of this:

* Each crate (`imag-diary`, `imag-notes`, `imag-wiki`, etc.) has its own ncurses UI, implemented in the respective `libimag*` crate
* I can reuse the code from the `libimag*` crates to write a all-in-one curses UI

Is this possible with Cursive? If yes, what has to be done, API wise on my side, to approach this?

---

My guesses:

* One has to create types which implement `cursive::View` (which are basically the UI for the respective crate. So one has one type and an implementation of `cursive::View` for it for `libimagentryview`, one for `libimagdiary`, one for `libimagfoobar` and so on)
* One can then use these to implement a per-crate UI or
* One can use these to integrate them into a more general UI

Am I right with this?

---

If the upper things are not possible or complicated to approach with the current API design of Cursive, you are welcome to use this as feature-request'ish issue! :smile:

**Comment by gyscos** [comment]
Views are indeed mostly self-contained (they include sizing, event management and drawing directives) so it's possible to define them in your modules/crates and reduce the code needed during usage. And if the "view" you need shared is just a stock view (a well-configured LinearLayout, etc...), it's also possible to publish a function that creates this view.
This is the easy way, and allows you to define "components" to integrate into a general UI. One of those components may well be an entire screen.

The question is how deep the integration would be in the UI.

If you need each "module" to add entries in the menubar, buttons to the main view, an extra tab somewhere, then you'll probably have to do these steps yourself.

**Comment by matthiasbeyer** [comment]
I guess it is pretty doable with the API this crate offers at the moment. I'm still collecting thoughts, though. I guess this issue can be closed, thanks for your answer!
