### ISSUE TITLE
Unable to get Ctrl-Z working on ncspot

### ISSUE THREAD

**Issue by ChaboCode** [gyscos/cursive#521]
# Problem description
Trying to addn a feature to play in background, find out that Ctrl-Z was ignored by the program. And manually sending SIGSTP and SIGCNT to the program breaks it.

# Environment

* Operating system: elementaryOS (Linux)
* Backend used: pancurses an termion
  * ncurses version 6.1
* Current locale:
```
LANG=es_MX.UTF-8
LANGUAGE=es_MX:es
LC_CTYPE="es_MX.UTF-8"
LC_NUMERIC="es_MX.UTF-8"
LC_TIME="es_MX.UTF-8"
LC_COLLATE="es_MX.UTF-8"
LC_MONETARY="es_MX.UTF-8"
LC_MESSAGES="es_MX.UTF-8"
LC_PAPER="es_MX.UTF-8"
LC_NAME="es_MX.UTF-8"
LC_ADDRESS="es_MX.UTF-8"
LC_TELEPHONE="es_MX.UTF-8"
LC_MEASUREMENT="es_MX.UTF-8"
LC_IDENTIFICATION="es_MX.UTF-8"
LC_ALL=
```.
* Cursive version: 0.15

**Comment by gyscos** [comment]
Hi, and thanks for the report!

First, regarding Ctrl-Z: as you noticed, it doesn't send a signal to the application but just regular input. Though you can totally raise the signal yourself in response:
```rust
fn main() {
    let mut siv = cursive::default();

    siv.add_layer(cursive::views::Dialog::text("foo"));

    siv.add_global_callback(cursive::event::Event::CtrlChar('z'), |_s| {
        unsafe { libc::raise(libc::SIGTSTP) };
    });

    siv.run();
}
```

Running with the ncurses backend, this will actually act like you'd expect, and you can then run `fg` to bring back the app, and it will keep working as expected.
This is actually mostly thanks to ncurses: when initialized, it sets a signal handler for `SIGTSP`, which resets back the terminal to default values before actually hanging. It also sets a signal handler for `SIGCONT` which brings back the ncurses interface.
This is what we want: we don't want to leave the terminal in a weird state when hanging, and similarly we don't know in what state it'll be when we resume.
For this to work on other backends, we'll need to apply the same logic in the backend initialization code.

**Comment by ChaboCode** [comment]
Thanks for the info. I think it's important to add this to the documentation for future issues like this.
