### ISSUE TITLE
RadioGroup's Clone implementation is unnecessarily bounded

### ISSUE THREAD

**Issue by alexiooo** [gyscos/cursive#523]
### Problem
RadioGroup<T> implements Clone trough a derive, this derive introduces a T: Clone bound on the implementation.
The only place T is stored, is behind an Rc; this Rc is perfectly cloneable for non-cloneable T, so there is no reason for the aforementioned bound.

### Solution
Implement Clone manually, as in
```
impl<T: 'static> Clone for RadioGroup<T> {
    fn clone(&self) -> Self {
        Self{
            state: self.state.clone()
        }
    }
}
```

**Comment by gyscos** [comment]
Ah indeed, that's one of the issues with derived traits.

**Comment by gyscos** [comment]
Deployed with cursive 0.16.0.
