### ISSUE TITLE
The rendered screen keeps flickering with termion-backend

### ISSUE THREAD

**Issue by htejun** [gyscos/cursive#525]
When I build resctl-demo with the default ncurses backend, everything works fine. However, if I switch to termion-backend, the rendered screen keeps flickering badly:

  https://drive.google.com/file/d/1-mZwZc6fbMpYCui3wIYbE3Zfy4Deb1xo/view?usp=sharing

The above recording is from a ssh session to a nearby machine through gnome-terminal + tmux (everything pretty much vanilla configuration) on arch linux. If I remove tmux in the chain, the flickers are less pronounced (the normal rendering recovers faster) but still there.

The resctl-demo branch is https://github.com/htejun/resctl-demo/tree/on-cursive-tip and is using the current cursive main branch.

Thanks.

**Comment by christoph-heiss** [comment]
Hi!

So I had the same issue, I could solve it pretty easily using the [cursive_buffered_backend](https://github.com/agavrilov/cursive_buffered_backend) crate, which was written to specifically address this issue with termion.
Hope that helps!

**Comment by htejun** [comment]
That worked perfectly. Thank you so much. Any chance this can be included by default or documented better?

**Comment by gyscos** [comment]
There is a plan to bring this kind of caching inside cursive, but we're not there yet.
