### ISSUE TITLE
Display a message while doing something in background

### ISSUE THREAD

**Issue by ph0llux** [gyscos/cursive#529]
I have a question.
I've written some example code to explain my problem/question. I want to "do something in the background" and while the things are running, I want to display a message "you have to wait 2 seconds":

```rust
use cursive::view::Nameable;
use cursive::views::{Dialog, TextView};
use cursive::Cursive;
use std::{thread, time};

fn main() {
    let mut siv = cursive::default();
    siv.add_layer(
    	Dialog::around(TextView::new("Text 1").with_name("text"))
    	.button("continue", display_text2)
    	);
    siv.run();
}

fn display_text2(siv: &mut Cursive) {
	siv.call_on_name("text", | view: &mut TextView | {
		let handle = thread::spawn(|| {
		let dur = time::Duration::from_millis(2000);
		thread::sleep(dur);
		});
		view.set_content("wait 2 seconds, then text 2 will be displayed");
		handle.join().unwrap();
	});
	siv.call_on_name("text", | view: &mut TextView | view.set_content("Text 2"));
}
```

But the message won't displayed - the Text 1 hangs for 2 seconds and then the content changed directly to Text 2.

Is there a solution to fix my problem?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The issue here is that callbacks run on the UI thread, so if you block here (with `handle.join()`), cursive won't have the opportunity to actually update the screen, process events, ...

If you want to run timed commands, you will need to do the waiting in a separate thread, and send callbacks to the main instance. You can use [`Cursive::cb_sink`](https://docs.rs/cursive/0.15.0/cursive/struct.Cursive.html#method.cb_sink) to get the Sender half of a channel, and use that to send callbacks from another thread.

So you would do:

```rust
let cb_sink = siv.cb_sink().clone();
thread::spawn(move || {
    cb_sink.send(Box::new(|s| {
        s.call_on_name("text", |view: &mut TextView| {
            view.set_content("Wait 2 seconds, then text 2 will be displayed.");
        });
    })).unwrap();

    thread::sleep(Duration::from_millis(2_000));

    cb_sink.send(Box::new(|s| {
        s.call_on_name("text", |view: &mut TextView| {
            view.set_content("Text 2");
        });
    })).unwrap();
});
```

**Comment by gyscos** [comment]
You can have a look at the [progress example](https://github.com/gyscos/cursive/blob/main/examples/src/bin/progress.rs) for a background task, or the [cursive-async-view](https://github.com/deinstapel/cursive-async-view) crate for a more fancy option.

**Comment by ph0llux** [comment]
> Hi, and thanks for the report!
> 
> The issue here is that callbacks run on the UI thread, so if you block here (with `handle.join()`), cursive won't have the opportunity to actually update the screen, process events, ...
> 
> If you want to run timed commands, you will need to do the waiting in a separate thread, and send callbacks to the main instance. You can use [`Cursive::cb_sink`](https://docs.rs/cursive/0.15.0/cursive/struct.Cursive.html#method.cb_sink) to get the Sender half of a channel, and use that to send callbacks from another thread.
> 
> So you would do:
> 
> ```rust
> let cb_sink = siv.cb_sink().clone();
> thread::spawn(move || {
>     cb_sink.send(Box::new(|s| {
>         s.call_on_name("text", |view: &mut TextView| {
>             view.set_content("Wait 2 seconds, then text 2 will be displayed.");
>         });
>     })).unwrap();
> 
>     thread::sleep(Duration::from_millis(2_000));
> 
>     cb_sink.send(Box::new(|s| {
>         s.call_on_name("text", |view: &mut TextView| {
>             view.set_content("Text 2");
>         });
>     })).unwrap();
> });
> ```

Thanks, that was the solution, I was looking for. :+1:
