### ISSUE TITLE
Mouse Input Hold and Painting

### ISSUE THREAD

**Issue by file-acomplaint** [gyscos/cursive#532]
Thanks for the great library, it looks cool! I'm very new around these parts, so please tell me all the things I did wrong in a nice way :^)

## The issue
I tried playing with the minesweeper example code to make it into a simple paint/ASCII-art tool and it's been fun! However, I can't figure out how to do something with "the cells the mouse went over while clicked" instead of "the cells the mouse clicked". So, in the Minesweeper situation: How can we reveal every cell hovered over with pressed mouse button? 
I was very happy to find the Mouse Event "Hold" in the Documentation, but didn't get it to work. What might be difficult here is that consoles interpret click, hold and move as text selection, right? (I read holding Shift changes the )

For reference, the relevant part of the demo starts at line 218 of this: https://github.com/gyscos/cursive/blob/main/examples/src/bin/mines/main.rs 

![Minesweeper_Paint](https://user-images.githubusercontent.com/42694673/103152239-658f1e00-4786-11eb-8e2b-458fd887a983.PNG)

## Environment
I tried to solve it on:
* Operating system: Arch Linux
* Backend used: termion
* Current locale: en_US.UTF-8 UTF-8
* Cursive version: crates.io v0.15.0
* Terminal: kitty and KDE Konsole

and 

* Operating system: Windows 10
* Backend used: pancurses
* Cursive version: crates.io v0.15.0
* Terminal: Hyper

**Comment by gyscos** [comment]
> What might be difficult here is that consoles interpret click, hold and move as text selection, right? (I read holding Shift changes the )

The console should _not_ treat it as text selection: we are enabling mouse mode, which disables the usual text selection. Though as you noted, pressing shift ignores the "mouse mode" and uses regular text selection (in that case the Cursive app will not receive the events).

Here's a simple example of a "paint" app - as you see, it just listens for Press and Hold of the left click (and uses right click to clear the screen):

```rust
#![feature(or_patterns)]   
                                                                            
use cursive::{                                                              
    event::{Event, EventResult, MouseButton, MouseEvent},   
    views::{Canvas, Dialog},                                                
    Vec2,                                                                   
};                                                                
                                                            
fn main() {   
    let mut siv = cursive::default();   
   
    siv.add_layer(Dialog::around(                                           
        Canvas::new([[false; 32]; 32])   
            .with_required_size(|s, _| Vec2::new(s[0].len(), s.len()))   
            .with_draw(|rows, printer| {   
                for (y, row) in rows.iter().enumerate() {                   
                    for (x, &cell) in row.iter().enumerate() {              
                        printer.print((x, y), if cell { "X" } else { " " });
                    }                                                       
                }                                                           
            })                                                              
            .with_on_event(|rows, event| match event {   
                Event::Mouse { 
                    event: MouseEvent::Press(MouseButton::Right),           
                    ..                                                      
                } => {                                                      
                    *rows = [[false; 32]; 32];   
                    EventResult::Consumed(None)   
                }   
                Event::Mouse {   
                    offset,                                                
                    position,                                               
                    event:                                                  
                        MouseEvent::Press(MouseButton::Left)      
                        | MouseEvent::Hold(MouseButton::Left),              
                } => {                                                      
                    if let Some(pos) = position.checked_sub(offset) {   
                        if pos.y < rows.len() && pos.x < rows[0].len() {    
                            rows[pos.y][pos.x] = true;                      
                            return EventResult::Consumed(None);             
                        }                                                   
                    }                                                       
                    EventResult::Ignored                                    
                }                                                           
                                                                            
                _ => EventResult::Ignored,   
            }),   
    ));   
   
    siv.run();   
}   
```

**Comment by file-acomplaint** [comment]
Thanks, that's interesting!
I could fix it on Arch/termion-backend with that! 

However the plot has thickened a bit on Windows:
On pancurses-backend, the Buttons are clickable with the mouse, but hold is interpreted like text selection - 
![pancurses_microsoft](https://user-images.githubusercontent.com/42694673/103171105-cf243080-4849-11eb-9518-56f4730064d1.PNG)

On crossterm and Microsoft's terminal, the mouse works as expected, awesome.  However, it's practically not usable due to an unrelated issue (?) of slow/jaggy drawing. It looks like this - 
![crossterm_microsoft](https://user-images.githubusercontent.com/42694673/103171162-3510b800-484a-11eb-8b2f-9f73b4c4a411.PNG)

(Let's not talk about third party terminals, haha :^)

Any ideas?

**Comment by gyscos** [comment]
Looks like pancurses is not properly initializing the mouse on windows - we could compare how crossterm and pancurses initialize the terminal, and maybe fix pancurses.

You can also try [`cursive_buffered_backend`](https://crates.io/crates/cursive_buffered_backend) - it buffers the backend output and may improve performance on termion and crossterm backends. Shouldn't affect ncurses much, which does its own buffering already.

**Comment by file-acomplaint** [comment]
Ah, that's great, thank you! Crossterm works beautifully now :^)

For anyone looking through here, I took absolute **ages** to get `cursive-buffered-backend` to work, it looks like the example snippet uses `cursive::backend` instead of `cursive::backends`, which seems to be a difference between cursive version 0.14 to 0.15. 

And I suppose that closes the issue? I'm not familiar with how wholesome the solution has to be to call it that, but thanks again!
