### ISSUE TITLE
ColorPalette

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#540]
Does ColorPalette provides the ability to have in a table view listings items in different colors, ie. scenario with file manager where in left pane you selecting couple of files/dirs to be copied to the right pane?

**Comment by gyscos** [comment]
The color palette just lists some colors to be re-used by components to achieve a uniform look - it would be up to the TableView to implement the selection logic and apply a different color to the desired parts.

**Comment by smallB007** [comment]
Thanks for the clarification
