### ISSUE TITLE
How to cancel the task 

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#543]
From ProgressBar:

 pub fn with_task<F: FnOnce(Counter) + Send + 'static>(
        self,
        task: F,
    ) -> Self

How to cancel this task?
Thank you

**Comment by gyscos** [comment]
Hi!
There is no builtin way to cancel the task. Instead, in the task itself, you could regularly check a `Arc<AtomicBool>` flag, and stop processing when it changes.

**Comment by smallB007** [comment]
Hi!
Can't ignore the running thread if that running thread is copying gigabytes of data...
One way to stop running thread is to return from it. It is just great pity that in your library there isn't easy way to set this up.
