### ISSUE TITLE
How to get content from Dialog on button press

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#547]
Hi, how do I get the content on button press (inside a closure), from let's say EditView, which in the below code example is called "cpy_from_edit_view"?
```
let cpy_dialog = Dialog::around(
        LinearLayout::vertical()
            .child(TextView::new("Copy from:"))
            .child(EditView::new().content(path_from).min_width(80).with_name("cpy_from_edit_view"))
            .child(TextView::new("Copy to:"))
            .child(EditView::new().content(path_to).min_width(80).with_name("cpy_to_edit_view"))
            .child(
                LinearLayout::horizontal()
                    .child(Checkbox::new_with_label("Recursive").with_name("recursive_chck_bx"))
                    .child(Checkbox::new_with_label("Overwrite").with_name("overwrite_chck_bx")),
            ),
    )
```
Thanks

**Comment by gyscos** [comment]
Hi!

You can check the [`edit` example](https://github.com/gyscos/cursive/blob/main/examples/src/bin/edit.rs) for how to retrieve the content of an `EditView`. The main trick is to give a name to the `EditView` itself, and not to any potential wrapper around it.

In your example, `.min_width(80)` wraps the `EditView` in a `ResizedView<EditView>`, and _that_ is what you assign a name to.
Instead, it may be easier to first give a name to the `EditView`, and then give _that_ a minimum width:
```rust
EditView::new().content(path_from).with_name("cpy_from_edit_view").min_width(80)
```

Then, when you want to fetch the content:

```rust
fn button_callback(siv: &mut Cursive) {
    let content: Rc<String> = siv.call_on_name("cpy_from_edit_view", |v: &mut EditView| {
        v.get_content()
    }).unwrap();
    // Do something with the content...
}
```

**Comment by smallB007** [comment]
Thank you.
