### ISSUE TITLE
Setting focus on buttons in Dialog doesn't work

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#549]
~~~
use cursive::views::{Dialog, TextView};
use cursive::*;

fn main() {
    let mut siv = cursive::default();
    
    let mut dlg = 
        Dialog::around(
                TextView::new("TextView"),
        ).button("Ok",|s|{}).button("Cancel",|s|{});
        
    dlg.set_focus(cursive::views::DialogFocus::Button(1));//Want to have focus on Cancel
    siv.add_layer(dlg
    );

    siv.run();
}
~~~

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, the focus for `Dialog` had a few issues, and (among other things) was getting reset to the first child at the beginning of the event loop. Should be fixed with the latest commit.

**Comment by smallB007** [comment]
Hi,
Indeed, it works now. Thank you.
Is it possible to "mark" button as "focused" during creation of a dialog?
