### ISSUE TITLE
Dialogs and setting Palette 

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#550]
Hi, is it possible to actually set different palette to a specific dialog?

Thank you

**Comment by gyscos** [comment]
Hi, and thanks for the report!

In the latest commit I added a `ThemedView`, which lets you assign a different theme to a child view.

You can check the [`themed_view` example](https://github.com/gyscos/cursive/blob/main/examples/src/bin/themed_view.rs) for how to create a dialog with a different palette.

(If you just want to apply a different palette to the entire application, it's easier to just change the current theme, like in the [`theme_manual` example](https://github.com/gyscos/cursive/blob/main/examples/src/bin/theme_manual.rs).)

**Comment by smallB007** [comment]
Hi and thank you for reply!
I will definitely check that. Basically, my needs with regards to themed dialog are that I should be able to apply different theme to any dialog independently from the "main" theme of the application.
I'm currently working on file manager which uses your library and for example I want to be able to show dialog which indicates error as a red, even though every other dialog is displayed with the current palette.
Once again, thank you for the reply and for your hard work. Really appreciate it.
