### ISSUE TITLE
HideableView when hidden should not block focus

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#558]
The scenario:
HideableView #Dialog#
If I create that^^^ and add siv.add_layer(dlg) and the hide that Dialog I will not be able to have any interaction with my application.
Surely hidden dialog should not block input?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

This is a deeper issue with the StackView; right now, all layers are "modal", meaning that they prevent input to reach any lower layer. This means that only the top-level layer is able to get any input, even if that layer is invisible.

Supporting non-modal layers is a long-term goal, I just haven't looked at it yet.

**Comment by gyscos** [comment]
The latest commits should bring a way to have non-modal layers.

One consequence is that if you:
* Add some regular layers
* Add a `HideableView` layer
* Make that `HideableView` invisible
* Make the layer non-modal (with `StackView::set_modal`)

Then it will no longer block input.

Note that non-modal (or "modeless") layers can be used in many other situations, for example to have non-interactive "overlay" layers, status bars, ...
It also opens the door for having several "movable" windows where you can grab another inactive window and bring it to the front, similar to a floating window manager.

**Comment by smallB007** [comment]
Great work! Thanks!
