### ISSUE TITLE
Unintentional termination of the complete program by a simple click.

### ISSUE THREAD

**Issue by ph0llux** [gyscos/cursive#561]
**Describe the bug**
When I run the program code below, the program counts up from 0 to 99 every second and displays that respectively. If you "click" in the window or press a key during the count-up, the program terminates itself directly.
I'm not sure, if this a bug or a feature...?

**To Reproduce**
```rust
use std::time::Duration;
use cursive::view::Nameable;
use cursive::views::{Dialog, TextView};
use cursive::Cursive;
use std::{thread};

fn main() {
    let mut siv = cursive::default();
    siv.add_layer(
    	Dialog::around(TextView::new("Text 1"))
		.button("continue", display_text)
    	.with_name("text")
    	);
    siv.run();
}

fn display_text(siv: &mut Cursive) {
	let cb_sink = siv.cb_sink().clone();
	thread::spawn(move || {
		for number in 0..100 {
			cb_sink.send(Box::new(move |s| {
				s.call_on_name("text", |view: &mut Dialog| {
					view.clear_buttons();
					view.set_content(TextView::new(number.to_string()))
				});
			})).unwrap();
			thread::sleep(Duration::from_millis(1_000));
		}
	});
}
```

**Expected behavior**
The program does not exit automatically when clicked.

**Environment**
* Operating system used: Gentoo Linux
* Backend used: termion
* Current locale: "de_DE.utf8"
* Cursive version: crates.io, 0.16.3

**Additional context**
nothing

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, the Dialog focus was not properly updated after removing the buttons, leading to a panic. Should be fixed with the latest commit.

Thanks again!

**Comment by ph0llux** [comment]
Works. Thank you.
