### ISSUE TITLE
ListView auto-scrolling to keep focused child in view assumes children are 1-high

### ISSUE THREAD

**Issue by namibj** [gyscos/cursive#562]
**Describe the bug**
`ListView`'s focus tracking is broken, visible in the `list_view` example. The focus-tracking calculations assume all children are `1` high, but that restriction has been liften in 56008db.

**To Reproduce**
Run the `list_view` example in a terminal where you don't see past 40 without scrolling down.
Select the last visible text field without scrolling down.
Observe that you need to press down-arrow 4 times until scrolling begins. This is 3 times too many, which matches the 3 extra lines in the "Presentation" `TextArea`.

This "lag" is reversed when focus movement triggers upwards scrolling. It scrolls 3 lines too-early.

**Expected behavior**
It should scroll when you press down-arrow just once.

**Screenshots**
Let me know if you need an asciinema recording.

**Environment**
* ArchLinux
* Backend used: default (I think that means `ncurses`)
* Current locale `en_US.UTF-8`
* Cursive version 7101c174f272581e2cedd9de41cb6678e71ee7b3

**Additional context**
I would fix this, but that iterator-heavy code is barely commented.
@gyscos wrote both the original focus-tracking auto-scroll code, and the fix for #133. They should be much better at it.

**Comment by gyscos** [comment]
Hi! Indeed, the `important_area` method assumed the height of items above was just the number of items. In the latest commit we should now properly sum the heights of previous items.

**Comment by namibj** [comment]
The `list_view` example now appears to be symptom-free.
This issue seems to have been fixed been fixed in db54045.
