### ISSUE TITLE
[FEATURE] Add a callback in the view first time it loads.

### ISSUE THREAD

**Issue by nico2sh** [gyscos/cursive#564]
Hi! Love this crate so far, so easy to compose the views. So, I have a request, or maybe a question for alternatives:

**Is your feature request related to a problem? Please describe.**
I need to fill a select view asynchronously, also on these select views, by default I have the first element selected and I would like to load asynchronously the data from that first element (like additional information for the selected element). I can use callbacks on events, but most events are either keypresses or `on_selection` in the case of the select view, which is not called for the first and default selection.

**Describe the solution you'd like**
Add a callback for once the view is loaded, there I could add asynchronously data and load it using the CBSink sender.

**Describe alternatives you've considered**
On refresh? I've read here that is not entirely reliable to be called unless autorefresh is set to true. I may have got that wrong though.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The current solution is to start/monitor this kind of background tasks in the call to `View::layout`. If you need access to the `Cursive` root (for example to trigger a re-draw when the content has been loaded), you would embed the callback sink (`Cursive::cb_sink`) when creating the view.

**Comment by nico2sh** [comment]
I see, I'll try that thanks!
