### ISSUE TITLE
[FEATURE] looping list in SelectView

### ISSUE THREAD

**Issue by s2terminal** [gyscos/cursive#567]
Hello.
I am developing an application using SelectView.

Is it possible for SelectView to loop? That is, if I move the cursor to the bottom of the list and then press the down key, it will loop to the top of the list.

Thanks.

**Comment by gyscos** [comment]
Hi! You should be able to use [CircularFocus](https://docs.rs/cursive/0.16.3/cursive/views/struct.CircularFocus.html) around the SelectView to achieve that.

**Comment by s2terminal** [comment]
Thanks for the advice.
But I could not figure out how to use CircularFocus. I want to loop through the SelectView. I wrote the following program based on the [sample code](https://github.com/gyscos/cursive/blob/f694e2ae25fdbe58f3f911e3895276f11f0f61b7/examples/src/bin/dialog.rs), but it didn't work.

```rust
use cursive::views::{CircularFocus, Dialog, SelectView};

fn main() {
    let mut siv = cursive::default();

    siv.add_layer(
        CircularFocus::wrap_arrows(
            Dialog::around(
                SelectView::new()
                    .item_str("one")
                    .item_str("two")
                    .item_str("three")
            )
        ),
    );

    siv.run();
}
```

Is there anything I should fix?

**Comment by chen244** [comment]
Oh, it is easy, all you need to do is add " .scrollable"

**Comment by gyscos** [comment]
Ah right it looks like `SelectView` does not reset its selection when it receives focus from the top or bottom.

I pushed a few commits which bring a few changes:
- It fixes SelectView so that it will now update the focus when the selection comes from the top/bottom (which is what `CircularFocus` does)
- It changes a bit the methods for `CircularFocus`, now you'll need to do `CircularFocus::new(Dialog::around(...)).wrap_arrows()`, or to keep it in order, `Dialog::around(...).wrap_with(CircularFocus::new).wrap_arrows()` (using `cursive::With`).

**Comment by s2terminal** [comment]
Thank you very much. I installed the "0.16.4-alpha.0" version of the main branch and modified the program as you suggested, and it seems to be working fine.

```rust
use cursive::views::{CircularFocus, Dialog, SelectView};

fn main() {
    let mut siv = cursive::default();

    siv.add_layer(
        CircularFocus::new(
            Dialog::around(
                SelectView::new()
                    .item_str("one")
                    .item_str("two")
                    .item_str("three")
            )
        ).wrap_arrows(),
    );

    siv.run();
}
```

I'm looking forward to the release.

**Comment by s2terminal** [comment]
I am glad to see that cursive version 0.17.0 has been released! 🎉
I have made sure that the following code does what I expect it to do. I am closing this issue.

```rust
use cursive::views::{CircularFocus, Dialog, SelectView};

fn main() {
    let mut siv = cursive::default();

    siv.add_layer(
        CircularFocus::new(
            Dialog::around(
                SelectView::new()
                    .item_str("one")
                    .item_str("two")
                    .item_str("three")
            )
        ).wrap_arrows(),
    );

    siv.run();
}
```
