### ISSUE TITLE
Issues with `'static` lifetime in `on_submit()`

### ISSUE THREAD

**Issue by Builditluc** [gyscos/cursive#573]
```
fn on_search(siv: &mut Cursive, search_query: &str, wiki: std::rc::Rc<wiki::Wiki>) {
  ...
  let mut results_view = SelectView::<structs::wiki::ArticleResultPreview>::new()
      .on_select(|s, item| {on_result_select(s, item)})
      .on_submit(|s, a| {on_article_submit(s, a, &wiki)});
  ...
}
```
Here, wiki is a `std::rc::Rc<wiki::wiki>`. I thought this should work, but it's giving me the error `explicit lifetime required in the type of wiki`.
The weird thing is, I'm calling `on_search()` out of another `on_submit()` function where I create `wiki` and there, it works:
```
 let rc_wiki: std::rc::Rc<wiki::Wiki> = std::rc::Rc::new(wiki);
      let search_bar = EditView::new()
          .on_submit(|s, q| {
              on_search(s, q, rc_wiki)
          })
          .with_name("search")
          .full_width();
```

**Comment by gyscos** [comment]
You may need to make the closure `move`? It might be trying to borrow `wiki`.

**Comment by Builditluc** [comment]
when I do `.on_submit(move |s, a| {on_article_submit(s, a, &wiki)});` I get the same error message
```
...
72 |         .on_submit(move |s, a| {on_article_submit(s, a, &wiki)});
   |          ^^^^^^^^^ lifetime `'static` required

error: aborting due to previous error; 1 warning emitted
```

**Comment by gyscos** [comment]
The problem is your `Wiki` structure: it has a lifetime parameter. It means it borrows some data from the parent scope, and we cannot depend on that from inside the callback.

I recommend having a "self-sufficient" `Wiki` structure if you need to pass it around. For example, embedding the `ApiConfig` instead of referencing it, or using a `Rc` for the config from within the `Wiki`.
Or, if you _really_ need to borrow it, consider some workarounds like [`owning_ref`](https://crates.io/crates/owning_ref) or [`rental`](http://crates.io/crates/rental) (there may be others) that let you define a standalone (`'static`) wrapper that embeds both the config and the wiki - you can then pass _that_ around.

**Comment by Builditluc** [comment]
Okay so you recommend the `Wiki` structure having the ownership of `ApiConfig` so I don't have to use lifetime parameters there? I mean I think I can do that because `ApiConfig` is only used by `Wiki` and doesn't change so Ownership could be given to it. And then I can use a `Rc` inside `on_submit()` to give `on_search()` a reference of `wiki`?
Did I understand this correctly?

**Comment by gyscos** [comment]
Yes:
* If the `Wiki` is the only thing that needs this `ApiConfig`, making it the owner would be much simpler.
* If other parts also need to access this `ApiConfig`, I would either clone it or store it in a `Rc<ApiConfig>`, and put _that_ in the `Wiki`.

After that, `Wiki` should no longer have a lifetime parameter: the type is now `'static`.

After that, you might not strictly _need_ a `Rc<Wiki>` if a single place (here the search bar callback) needs it. You can just `move` it in the closure for example. Or you can store it as [user_data](https://docs.rs/cursive/0.16.3/cursive/struct.Cursive.html#method.set_user_data) in the `Cursive` root (you can store one item there of any type, and retrieve it in most callbacks so you don't need to pass it around yourself).

**Comment by Builditluc** [comment]
I didn't know anything about `user_data`. That should fix my error. I will try it tomorrow. Anyway thanks for your help and for providing such a great tui library for rust :)
