### ISSUE TITLE
[BUG] Pancurses backend does not support mouse wheel down events with libncursesw5

### ISSUE THREAD

**Issue by rbuch** [gyscos/cursive#575]
**Describe the bug**

Scrolling down using the mouse wheel when using the pancurses backend with libncursesw5 produces a `cursive_core::event::MouseEvent::Hold(cursive_core::event::MouseButton::Left)` event rather than `cursive_core::event::MouseEvent::WheelDown`. Doing the same with the ncurses or termion backends works correctly. This was originally observed in ncspot: https://github.com/hrkfdn/ncspot/issues/442.

**To Reproduce**

Examine the event produced by scrolling down in a `ScrollView`.

**Expected behavior**

I expect scrolling down to produce a `cursive_core::event::MouseEvent::WheelDown` event.

**Environment**
* Operating system used: Ubuntu 18.04.5
* Backend used: pancurses
* Current locale: en_US.UTF-8
* Cursive version: 0.16.3 (via Cargo)

**Analysis**

I  believe this is caused by not special casing the legacy scroll behavior of ncurses with `NCURSES_MOUSE_VERSION = 1` in the pancurses backend. In particular, note the difference between the relevant parts of `parse_mouse_event` for the ncurses and pancurses backends:

`n.rs`:
```rust
if mevent.bstate == ncurses::REPORT_MOUSE_POSITION as mmask_t {
    // The event is either a mouse drag event,
    // or a weird double-release event. :S

    self.last_mouse_button
        .map(MouseEvent::Hold)
        .or_else(|| {
            // In legacy mode, some buttons overlap,
            // so we need to disambiguate.
            if mevent.bstate
                == ncurses::BUTTON5_DOUBLE_CLICKED as mmask_t
            {
                Some(MouseEvent::WheelDown)
            } else {
                None
            }
        })
        .map(&make_event)
        .unwrap_or_else(|| Event::Unknown(vec![]))
}
```
`pan.rs`:
```rust
if mevent.bstate == pancurses::REPORT_MOUSE_POSITION as mmask_t {
    // The event is either a mouse drag event,
    // or a weird double-release event. :S
    self.last_mouse_button
        .map(MouseEvent::Hold)
        .map(&make_event)
        .unwrap_or_else(|| {
            debug!("We got a mouse drag, but no last mouse pressed?");
            Event::Unknown(vec![])
        })
}
```

**Comment by gyscos** [comment]
Hi, and thanks for the report! Indeed, looks like we missed pancurses when fixing the ncurses backend.

I pushed a tentative fix, but I don't currently have a system with ncurses built in legacy mouse mode. Could you try and see if it fixes the issue for you?

**Comment by rbuch** [comment]
> Hi, and thanks for the report! Indeed, looks like we missed pancurses when fixing the ncurses backend.
> 
> I pushed a tentative fix, but I don't currently have a system with ncurses built in legacy mouse mode. Could you try and see if it fixes the issue for you?

Just tried it out, it works for me. Thanks for the quick fix!
