### ISSUE TITLE
Application get's slow when displaying a large amount of text

### ISSUE THREAD

**Issue by Builditluc** [gyscos/cursive#578]
When I display a large amount of text inside of an TextView, the Application gets slow. Is there any way to render only the portion of the text that get's displayed on the screen?

**Comment by FliegendeWurst** [comment]
I had the same issue and came up with this fix: https://github.com/FliegendeWurst/cursive/commit/8ec46107e13941b06861311ae672a5e62f78e4c8

**Comment by Builditluc** [comment]
Thanks @FliegendeWurst. Although it didn't work for me (I think it has something to do with my super large StyledString, that has many spans in different styles, that I'm displaying there) it is great for performance in many cases

**Comment by gyscos** [comment]
In theory the `Printer` should already ignore any attempt to print outside of the visible viewport.
Skipping the unnecessary lines earlier, in the TextView itself, still brings some improvements (no need to list and resolve the unused spans), but that shouldn't _usually_ be that slow.

The main expensive thing is usually computing rows of text (word wrapping). Ideally it should be cached once, and only re-computed on layout change, but not on regular events. In some cases the caching can be broken (LinearLayout is not currently super cache-friendly), so there's still some improvements to do there.

**Comment by Builditluc** [comment]
Okay so there is nothing I can do to make it run faster? I mean, besides implementing paging

**Comment by Builditluc** [comment]
![image](https://user-images.githubusercontent.com/37375448/118458727-55f38000-b6fb-11eb-9d92-762db567987c.png)
Every time `calculate_rows()` is called (after `self.rows = LinesIterator::new()`) the program logs the message "Calculating new lines" and as you can see the function is called multiple times a second.
@gyscos is that intended/normal?

**Comment by realtica** [comment]
I have the same issue here.  :(

**Comment by Builditluc** [comment]
@realtica I fixed this issue by creating multiple "historical" caches for the view (had to write a custom one :/). [This](https://github.com/Builditluc/wiki-tui/blob/094e28f0d371740a2bafe3c334be23bf4361ac94/src/ui/article/view.rs#L374) is the implementation for the caching, maybe it can help you
