### ISSUE TITLE
Add state to `Backend`

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#59]
`Backend` is currently a trait with only static methods. In this situation, any state is global (currently handled globally by ncurses).

With termion (and most other backends) being comparatively stateless, it'd make sense to move this part of the state into a proper structure, with the `Backend` trait taking `&self`/`&mut self` appropriately.

Some notes:
* This mean `Printer` would need a reference to the current `Backend` object. 
However, the backend types are currently not publicly exported.

  This means `Printer` can't expose any method using these traits, including a constructor. So how should `Cursive` build one?...
    * One possible solution would be the [`pub(restricted)`](https://github.com/rust-lang/rust/issues/32409) feature.
    * Alternatively, we could move the `Printer` struct into the root module, to bypass this visibility issue.
* To deal with nested `with_color` blocks, we want to be able to "push" and "pop" the current style.
    * This requires a way to get the current style.
        * This means the current state should be modified by the `with_color` block.
           However, views currently have access to a `&Printer`, which means no mutable access to the backend. 
            * This points to internal mutability in the `Backend`, unless we start using a `&mut Printer`?...
              (This would make sense ; views were only given an immutable `&Printer` because ncurses didn't require otherwise.)

**Comment by dmacvicar** [comment]
Had the same problem while toying a rustbox backend.

**Comment by gyscos** [comment]
I think the easiest short-term solution is a static variable (probably using `lazy_static`) with a (`Mutex`'ed) global state.

I'll probably end up making `Printer`'s method take a `&mut Self`, but it doesn't solve the visibility issue. I'd rather not make the `Backend` trait public, and since `pub(restricted)` won't be stable for a little while, I guess moving `Printer` to `src/lib.rs` is the only option. I'll probably `include!` the entire `printer.rs` file to avoid having a cluttered `lib.rs`, and at least it won't change the public API, so I suppose it could be worse.

**Comment by gyscos** [comment]
Actually, it's probably best not to have a `&mut B` in the printer: the mutability we need in the backend is mostly outside of printing (colors initialization, ...). Plus, it's illegal to have two `&mut B` pointing to the same backend (which would happen whenever we create a sub-printer).

Next step is have printing functions in the backend take a `&self` (they are currently static methods).

**Comment by gyscos** [comment]
Most `Backend` methods now take a `&self`. `Backend::clear()` is still static because it needs to be called on some re-layout. It's a bit of a dirty hack, so I'll see if it can do it properly through a `Printer` or something.

Anyway, `Backend` is now ready to have a proper inner state!
