### ISSUE TITLE
Keyboard events need improvement

### ISSUE THREAD

**Issue by snheath** [gyscos/Cursive#60]
Sorry.  :(

The way it appears set up, with an enum of different modifier combinations, is rather redundant and inflexible.  You can't capture a modifier keypress (such as just pressing alt to open a menu), you can't capture ctrl+alt+char because that enum just doesn't happen to exist, and capturing ctrl+c and ctrl+f1 are completely different event cases, so if I'm matching against events, I have to match CtrlChar(char) and Ctrl(Key) separately.

If I'm missing something obvious, I apologize.  But the obvious method appears to be something more along the lines of this: <https://wiki.libsdl.org/SDL_Keysym> (and <https://wiki.libsdl.org/SDL_Event> in general, though that's probably a bit overkill).  Each key press creates an event that contains three members: The raw key symbol, a character representation of the keypress (if any), and a collection of modifiers.  Then you have methods or such that make it easy to distinguish event types, modifier keys, etc. from each other in a much more flexible way.

**Comment by gyscos** [comment]
Terminals application don't have the same control on the input they receive as graphical applications that you'd build with sdl.
Many key combinations are simply not sent to the application, so there is no easy to listen to it. This includes a single `alt` key press, or ctrl-alt-char combinations. This is in part why chars and keys are handled differently.

Concerning the matching difference, do you have a code example where this is an issue? You can match `CtrlChar('c')` and `Ctrl(Key::F1)` in the same `match` block.

**Comment by snheath** [comment]
Fair enough, in that case I stand corrected.

I don't have an example, it's just a style quibble.  :)

**Comment by gyscos** [comment]
If you have specific key combinations in mind (like `c` or `F1`), it's easy to put them both in a match block:

```rust
fn on_event(&mut self, event: Event) -> EventResult {
    match event {
        Event::CtrlChar('c') |
        Event::Ctrl(Key::F1) => { /* F1 pressed... */ }
        Event::Char('q') => { /* Q pressed - quit ! */ }
        _ => return EventResult::Ignored;
    }
    EventResult::Consumed(None)
}
```
If you want to check it against your own list of chars / keys, directly check against the `Event`.

I've yet to see a case where this enum structure is actually inconvenient, but if you find one, I'd be happy to have a look.

**Comment by snheath** [comment]
All right.  I probably should have said from the beginning, this was sparked by a comment on #rust-beginners on IRC where someone was asking how to capture an alt keypress not attached to anything else using Cursive.  From the sound of it he's just out of luck.

**Comment by gyscos** [comment]
Thanks! I suppose I should spend some time more time on IRC, I had no idea people asked for help on cursive there.
I'll close this issue ; if the enum hierarchy happens to be an issue, it'll go through a separate issue with a specific problematic example.
