### ISSUE TITLE
[BUG] `SelectView` will not render correctly in a `ListView`

### ISSUE THREAD

**Issue by liushuyu** [gyscos/cursive#602]
**Describe the bug**
`SelectView` will not render correctly in a `ListView` when laying out after a `delimiter`.

**To Reproduce**
```rust
use cursive::traits::Nameable;
use cursive::view::Resizable;
use cursive::views::{EditView, ListView, SelectView};

fn main() {
    let mut siv = cursive::default();
    let config = ListView::new()
        .child("Edit", EditView::new().min_width(20).with_name("input"))
        .delimiter()
        .child(
            "Select",
            SelectView::new()
                .popup()
                .with_all_str(vec!["a", "b"])
                .min_width(20),
        );
    siv.add_layer(config);
    siv.run();
}
```

**Expected behavior**
The `SelectView` renders correctly and not blank.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/6829345/131455812-3bfa2e56-26fc-41f0-9f15-2da0fcba9d1d.png)

**Environment**
* Operating system used: AOSC OS 8 / Arch Linux / Ubuntu 20.04
* Backend used: ncurses
* Current locale: `zh_CN.UTF-8` / `en_US.UTF-8`
* Cursive version: 0.16 from crates.io / 0.17.0-alpha.0 from crates.io

(Multiple environments are used to test the situation and each of the combinations can reproduce the bug)

**Additional context**
The issue seems to be a regression, it did not happen in version 0.15. `git bisect` result: "56008db79608b05366138cfd9a2c65be1a5da8c6 is the first bad commit".

Commit information for the suspected regression:
```
commit 56008db79608b05366138cfd9a2c65be1a5da8c6
Author: Alexandre Bury <alexandre.bury@gmail.com>
Date:   Tue Jul 7 00:10:28 2020 -0700

    Enable multi-rows views in ListView

 cursive-core/src/direction.rs           |  6 +--
 cursive-core/src/views/linear_layout.rs |  6 +--
 cursive-core/src/views/list_view.rs     | 78 ++++++++++++++++++++++-----------
 examples/src/bin/list_view.rs           | 10 +++--
 4 files changed, 65 insertions(+), 35 deletions(-)
```

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, the handling of delimiters was broken in `ListView`, leading to some issues like zero-height children.

Should be fixed in the latest commit, tell me if it helps! :)

**Comment by liushuyu** [comment]
> Hi, and thanks for the report!
> 
> Indeed, the handling of delimiters was broken in `ListView`, leading to some issues like zero-height children.
> 
> Should be fixed in the latest commit, tell me if it helps! :)

Thanks! The latest commit fixed the issue.
