### ISSUE TITLE
[BUG] Error: linking with "cc" failed. Exit with code 1

### ISSUE THREAD

**Issue by flxinxout** [gyscos/cursive#603]
**Describe the bug**
Hi, I created a new rust project to use cursive. in my .toml file I just put the cursive dependency and then I compile with a main function with `let mut app = cursive::default();` and `app.run();`. When I compile I have this error:

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.15i8okh0cmi4haj.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.1im1ey75iqo4qm71.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.1z4rxao19qhr53oe.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.2glivzzv0tbnr66m.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.2h39mvvnp1bssp5x.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.4whh9iy40sfaeez3.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.551bx4qva66pabtt.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.5awx4ynslg93x2i7.rcgu.o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca.3yfe1wpn8wba3ca3.rcgu.o" "-Wl,--as-needed" "-L" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps" "-L" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libcursive-896d49aca475ce38.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libncurses-a5d405e12c74da2c.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libmaplit-21d5ff4807e27e80.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libsignal_hook-2fe410fa8acce0db.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libsignal_hook_registry-afbdeab36892eb6a.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libcursive_core-6e7dce041c98efcd.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libahash-d44a8f9b09819316.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libgetrandom-db8fb917aeee51ae.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libonce_cell-7ed3e5e1d98df1ef.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libchrono-4253ac035c6feb1f.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libtime-b622af9a9e06a5dc.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/liblibc-7085dace614ae946.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libcrossbeam_channel-e438bdb8af58133e.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libcrossbeam_utils-3e626c1dc709f8d2.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libnum-c1dd9ad03284018a.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libnum_iter-ba07647cfd4bd98c.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libnum_rational-c7e48476d600464d.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libnum_integer-abb97986d4ce939e.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libnum_complex-6cd9ff75641bd640.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libenum_map-0784901cfe1c4eeb.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libarray_macro-54f8a474ec4453ab.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/liblazy_static-df981c5871754530.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libowning_ref-5b211ee349bf8dec.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libstable_deref_trait-f73fe2c5117eebce.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/liblog-5adcf922eb1fa2ac.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libcfg_if-dece450273084492.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libxi_unicode-b75f3b7af6af5136.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libunicode_width-05a4b639dec6224c.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libunicode_segmentation-6c95ab588f06b03b.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libwasmer_enumset-0ccbfa49d5351eed.rlib" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libnum_traits-41fda7c684ad088a.rlib" "-Wl,--start-group" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-008055cc7d873802.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-06f01ac2578bda94.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-f9a3c3274a1835e0.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-d4cbb754ee9f4daa.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-95c14e1c1e3ebcc4.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-d489f0ca872880cc.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-75f07df0b18fea39.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-0c35b278736219a2.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e530649c9a06e3c6.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-6b148909d375a785.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-cd15fa647f4775d1.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-74be3a703f788ba2.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-8f2c5b445c28b2e3.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-8480e85e0be96197.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ac23a75f6f42004e.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-557ba8776e04d182.rlib" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4beb03d03503c439.rlib" "-Wl,--end-group" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-dd7db1bec6909f24.rlib" "-Wl,-Bdynamic" "-lncursesw" "-ltinfo" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/test_cursive-42589fe4bea464ca" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libncurses-a5d405e12c74da2c.rlib(ncurses-a5d405e12c74da2c.ncurses.d8929387-cgu.9.rcgu.o): in function `ncurses::constants::stdscr':
          /home/flxinxout/.cargo/registry/src/github.com-1ecc6299db9ec823/ncurses-5.101.0/src/constants.rs:44: undefined reference to `stdscr'
          /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libncurses-a5d405e12c74da2c.rlib(ncurses-a5d405e12c74da2c.ncurses.d8929387-cgu.9.rcgu.o): in function `ncurses::constants::COLORS':
          /home/flxinxout/.cargo/registry/src/github.com-1ecc6299db9ec823/ncurses-5.101.0/src/constants.rs:44: undefined reference to `COLORS'
          /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /home/flxinxout/Documents/Development/Rust/test_cursive/target/debug/deps/libncurses-a5d405e12c74da2c.rlib(ncurses-a5d405e12c74da2c.ncurses.d8929387-cgu.9.rcgu.o): in function `ncurses::constants::COLOR_PAIRS':
          /home/flxinxout/.cargo/registry/src/github.com-1ecc6299db9ec823/ncurses-5.101.0/src/constants.rs:44: undefined reference to `COLOR_PAIRS'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `test_cursive` due to previous error

**To Reproduce**
explain previously

**Expected behavior**
I just want to compile and start creating tui

**Screenshots**
http://image.noelshack.com/fichiers/2021/37/2/1631635154-screenshot-20210914-175307.png (the previous image)
http://image.noelshack.com/fichiers/2021/37/2/1631635471-screenshot-20210914-180355.png

**Environment**
* Operating system used: openSUSE Leap 15.3
* Backend used: ncurses (second screenshot)
* Current locale: uft-8 fr
* Cursive version: 0.16

**Additional context**
-

**Comment by gyscos** [comment]
Hi, and thanks for the report!

This looks like some issues linking to `ncurses`.
* Do you have the ncurses library installed? On openSUSE I suppose you may need `ncurses-libs`, and maybe `libncurses6`.
* If you can't get ncurses to work, [you can also try an alternative backend](https://github.com/gyscos/cursive/wiki/Backends).

**Comment by nikhil-prabhu** [comment]
Can confirm; this is the case with SLES15 SP3, Leap 15.3, and also with Tumbleweed. Even with all available `ncurses` packages installed from the default repos.

![installed-ncurses](https://user-images.githubusercontent.com/39860598/133444520-1ee69ae3-be73-4067-a69b-99f3d30e1b29.png)

**Comment by nikhil-prabhu** [comment]
I seem to have found a workaround (tested on openSUSE Tumbleweed).

1. Install the `ncurses5-devel` package.
2. Run `export NCURSES_RS_RUSTC_FLAGS="-L /usr/lib64/ncurses5"` in the shell.
3. Build the project (Run `cargo clean` first to make sure it's a clean build. It didn't work for me until I performed a clean build).

With these steps, I'm able to successfully build my project against the the `ncurses` backend.

Additionally, using the `pancurses` backend doesn't require this workaround. It works normally.

From what I could see online, this seems to be a packaging issue on openSUSE.

I found the workaround here: https://github.com/jeaye/ncurses-rs/issues/191

**Comment by nikhil-prabhu** [comment]
I seem to have found a workaround (tested on openSUSE Tumbleweed).

1. Install the `ncurses5-devel` package.
2. Run export NCURSES_RS_RUSTC_FLAGS="-L /usr/lib64/ncurses5" in the shell.
3. Build the project (Run cargo clean first to make sure it's a clean build. It didn't work for me until I performed a clean build).

With these steps, I'm able to successfully build my project against the the ncurses backend.

Additionally, using the pancurses backend doesn't require this workaround. It works normally.

I found the workaround here: jeaye/ncurses-rs#191

**Comment by nikhil-prabhu** [comment]
Installing the `ncurses5-devel` package solved this issue for me.

**Comment by flxinxout** [comment]
> Hi, and thanks for the report!
> 
> This looks like some issues linking to `ncurses`.
> 
> * Do you have the ncurses library installed? On openSUSE I suppose you may need `ncurses-libs`, and maybe `libncurses6` or `libncurses6-dev` (I think? I don't use openSUSE, so not sure which packages include the headers and compiled libraries).
> * If you can't get ncurses to work, [you can also try an alternative backend](https://github.com/gyscos/cursive/wiki/Backends).

Hello, thanks for the reply. Here is the list of all packages for ncurses. Where there is the i+ it's installed.

S  | Name                          | Summary                                                          | Type
---+-------------------------------+------------------------------------------------------------------+--------------
   | gambas3-gb-ncurses            | The ncurses component for Gambas                                 | paquet
i+ | libncurses5                   | Terminal control library                                         | paquet
   | libncurses5-32bit             | Terminal control library                                         | paquet
i+ | libncurses6                   | Terminal control library                                         | paquet
   | libncurses6-32bit             | Terminal control library                                         | paquet
   | libyui-ncurses                | Libyui - NCurses (text based) user interface                     | paquet source
   | libyui-ncurses-devel          | Libyui - Header fles for the NCurses (text based) user interface | paquet
   | libyui-ncurses-doc            | Libyui-ncurses documentation                                     | paquet
   | libyui-ncurses-pkg            | Libyui - yast2 package selector widget for the NCurses UI        | paquet source
   | libyui-ncurses-pkg-devel      | Libyui-ncurses-pkg header files                                  | paquet
   | libyui-ncurses-pkg-doc        | Libyui-ncurses-pkg documentation                                 | paquet
   | libyui-ncurses-pkg11          | Libyui - yast2 package selector widget for the ncurses UI        | paquet
i+ | libyui-ncurses-pkg15          | Libyui - yast2 package selector widget for the NCurses UI        | paquet
   | libyui-ncurses-pkg8           | Libyui - yast2 package selector widget for the ncurses UI        | paquet
   | libyui-ncurses-pkg9           | Libyui - yast2 package selector widget for the ncurses UI        | paquet
   | libyui-ncurses-rest-api       | Libyui - REST API plugin for the Ncurses frontend                | paquet source
   | libyui-ncurses-rest-api-devel | Libyui - Header files for the NCurses REST API plugin            | paquet
   | libyui-ncurses-rest-api11     | Libyui - The REST API plugin for the Ncurses frontend            | paquet
   | libyui-ncurses-rest-api15     | Libyui - REST API plugin for the Ncurses frontend                | paquet
   | libyui-ncurses-tools          | Libyui - tools for the NCurses (text based) user interface       | paquet
   | libyui-ncurses11              | Libyui - Character Based User Interface                          | paquet
i+ | libyui-ncurses15              | Libyui - NCurses (text based) user interface                     | paquet
   | libyui-ncurses8               | Libyui - Character Based User Interface                          | paquet
   | libyui-ncurses9               | Libyui - Character Based User Interface                          | paquet
i  | ncurses-devel                 | Development files for the ncurses6 terminal control library      | paquet
   | ncurses-devel-32bit           | Development files for the ncurses6 terminal control library      | paquet
i+ | ncurses-utils                 | Tools using the new curses libraries                             | paquet
   | ncurses5-devel                | Development files for the ncurses5 terminal control library      | paquet
   | ncurses5-devel-32bit          | Development files for the ncurses5 terminal control library      | paquet

**Comment by flxinxout** [comment]
> Installing the `ncurses5-devel` package solved this issue for me.
> 
> EDIT:
> 
> Installing the `ncurses5-devel` package was sufficient to fix this issue for me on openSUSE Tumbleweed. On openSUSE Leap 15.3, an additional step is required after installing the package:
> 
> * Run `export NCURSES_RS_RUSTC_FLAGS="-L /usr/lib64/ncurses5"` in your shell.
> 
> After this, you should be able to build your project using both the `ncurses` and the `pancurses` backends.
> 
> **NOTE**: You may need to run `cargo clean` before finally building the project for it to work.
> 
> Reference: [jeaye/ncurses-rs#191](https://github.com/jeaye/ncurses-rs/issues/191)

**It works !!** Thank you very much
