### ISSUE TITLE
[FEATURE] Change view content if it is focused

### ISSUE THREAD

**Issue by robinkrahl** [gyscos/cursive#611]
**Is your feature request related to a problem? Please describe.**
I’d like to have a view that changes its content if it is focused.  Per default, it only shows one view, typically a heading, but if it is focused, it shows two views, the heading and some additional content.  Currently, I can only detect if the view takes focus (via `View::take_focus`) and if it is focused during the draw phase (via `Printer::focused`).  But as far as I see, it is not possible to check if the view is focused when calculating the minimum size or during the layout.

**Describe the solution you'd like**
I’d like to be able to query the focus state of the current view or receive an event if the focus of a view changes.

**Describe alternatives you've considered**
I don’t see any viable alternative that solves the problem.

**Additional context**
Currently, I have this partially working implementation that still uses the expanded size after the item loses focus:

<details>
<summary><code>DetailsView</code></summary>

```rust

pub struct DetailsView {
    collapsed: cursive::views::TextView,
    expanded: cursive::views::LinearLayout,
    is_focused: std::sync::atomic::AtomicBool,
}

impl DetailsView {
    pub fn new(header: impl Into<String>, details: impl Into<String>) -> Self {
        let header = header.into();
        let details = details.into();
        Self {
            collapsed: cursive::views::TextView::new(&header),
            expanded: cursive::views::LinearLayout::vertical()
                .child(cursive::views::TextView::new(&header))
                .child(cursive::views::TextView::new(&details)),
            is_focused: false.into(),
        }
    }
}

impl cursive::View for DetailsView {
    fn draw(&self, printer: &cursive::Printer) {
        self.is_focused.store(printer.focused, std::sync::atomic::Ordering::Relaxed);
        let mut style = theme::Style::from(theme::Effect::Underline);
        let view: &dyn cursive::View = if printer.focused {
            style = style.combine(theme::PaletteColor::Highlight);
            &self.expanded
        } else {
            &self.collapsed
        };
        printer.with_style(style, |printer| {
            view.draw(printer);
        });
    }

    fn take_focus(&mut self, _direction: cursive::direction::Direction) -> bool {
        self.is_focused.store(true, std::sync::atomic::Ordering::Relaxed);
        true
    }

    fn layout(&mut self, size: cursive::XY<usize>) {
        self.collapsed.layout(size);
        self.expanded.layout(size);
    }

    fn needs_relayout(&self) -> bool {
        self.collapsed.needs_relayout() || self.expanded.needs_relayout()
    }

    fn required_size(&mut self, constraint: cursive::XY<usize>) -> cursive::XY<usize> {
        if self.is_focused.load(std::sync::atomic::Ordering::Relaxed) {
            self.expanded.required_size(constraint)
        } else {
            self.collapsed.required_size(constraint)
        }
    }
}
```
</details>

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, the concept of "being in focus" in not currently present in the layout phase. While it didn't seem necessary at first, you make a great example use-case.

The only workaround I see currently (and it's really just an approximation) is to manually maintain a shared "currently selected view" index (something like `Rc<Cell<u64>>`, and update that index using wrapper around each view that can be selected. Whenever such a wrapper accepts focus, sets the shared selection index.

Clearly this is inconvenient, and I agree a better solution is needed, but it looks like it's going to be a breaking change on the layout interface.

I've been wanting to pass some "context" in most view calls for a while (to give information such as the position in the view tree, and now the focus state), so it may be time to gather all these ideas and find a good design.

**Comment by gyscos** [comment]
Note though that if a popup shows up, all other views would lose focus (or at least they should; right now `StackView` doesn't correctly handle that). Would you want to update the view content in this case?

Or are you more interested in a list of views, and only the last selected one should be "expanded", but where external focus events such as a popup grabbing the focus should not affect the layout? In that case, you're more interested in the focus of the `LinearLayout` (or whatever parent view you're using) specifically, rather than really knowing if a view is "in focus".

**Comment by robinkrahl** [comment]
Thanks for your replies!  `Event::FocusLost` seems useful indeed.

> Or are you more interested in a list of views, and only the last selected one should be "expanded", but where external focus events such as a popup grabbing the focus should not affect the layout?

That’s a good point, I did not consider that.  I was able to implement this by wrapping `ListView`, but that leads to another issue if there are multiple lists in one view and I only want one of them to be active.  But that should be solvable.

**Comment by robinkrahl** [comment]
Would it be possible to also have an `Event::FocusGained`?  There is `take_focus`, but it does not have access to the current `Cursive` instance.
