### ISSUE TITLE
[FEATURE] Line wrapping for ListView

### ISSUE THREAD

**Issue by caio-ishikawa** [gyscos/cursive#621]
Been working with cursive for the past week or so and the ability to wrap lines would be wonderful! Some of my list items can get quite long and as far as I know, there's not much I can do about it except enlarge the terminal window.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Do you mean line wrapping for the labels? Or for the "content" view?

**Comment by caio-ishikawa** [comment]
Hey! Thanks for the prompt reply. I actually just realized I have been using the ListView sort of wrong the whole time. I was placing the content in the label area.

I think adding wrapping for the labels would be good, but you actually solved my problem with the way you phrased the question! Apologies for any inconvenience, I'll close this thread!
