### ISSUE TITLE
[BUG] Crossterm crash when dragging mouse in Windows Terminal

### ISSUE THREAD

**Issue by luryus** [gyscos/cursive#630]
**Describe the bug**
When clicking and dragging the mouse inside a Crossterm-backend Cursive app in Windows Terminal, the process immediately panics. This is caused by this crossterm bug: https://github.com/crossterm-rs/crossterm/issues/588.

Updating cursive to use crossterm 0.22.1 fixes this.

**To Reproduce**
In Windows Terminal, run `cargo run --example hello_world --features crossterm-backend --no-default-features` and drag the mouse anywhere.

**Environment**
* Windows 10
* Backend used: crossterm
* Both Cursive 0.16.3 and current main branch have this issue

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Latest commit should bump the crossterm version to 0.22.1.

**Comment by luryus** [comment]
Thanks for the quick fix! It works with Cursive 0.17 now.
