### ISSUE TITLE
[BUG] SelectView updates focus index during remove_item(), but not during insert_item()

### ISSUE THREAD

**Issue by compenguy** [gyscos/cursive#634]
**Describe the bug**
These otherwise-symmetric methods on SelectView don't behave symmetrically, as `remove_item()` is focus-aware, and will correctly adjust the focus index if it was higher than the remove point, but `insert_item()` ignores focus, causing it to shift by one if the focus index was higher than the insertion point.

**To Reproduce**
Found by inspection while looking for solutions to a related task - preserving entry focus across a sort (documented as not being supported, so I'm handling that on my own).

**Expected behavior**
Duplicate the focus update logic from `remove_item()`, but without the `Callback` logic.

I'm also suspicious of the `remove_item()` Callback behavior - while the focus index may change, the focus should only actually change if the focused item is the one being deleted, so it seems like it should return `Some(Callback)` if `focus == id`, otherwise `None`.  On the other hand, I wouldn't expect `insert_item()` to return a `Callback` because after fixing the issue in this bug report, focus is retained across inserts, with no case resulting in a change of focus.

**Screenshots**
N/A

**Environment**
* cursive-core 0.3.1

**Additional context**
I'm not (yet) directly affected by this. Instead of sorting my list after each insertion (and losing item focus, with a semi-painful process to try to capture and restore across sorts), I'm looking at inserting new items in the correctly sorted position, in which case I will be affected (albeit with an easier-to-handle workaround for capturing and restoring focus position across inserts).

**Comment by gyscos** [comment]
Hi, and thanks for the report!

> **Describe the bug** These otherwise-symmetric methods on SelectView don't behave symmetrically, as `remove_item()` is focus-aware, and will correctly adjust the focus index if it was higher than the remove point, but `insert_item()` ignores focus, causing it to shift by one if the focus index was higher than the insertion point.

Indeed, `insert_item` should bump the focus if it's higher then the given `index`.

> it seems like it should return `Some(Callback)` if `focus == id`, otherwise `None`.

Right - currently, it returns the callback even if the focus did not change, which may not be desired.

**Comment by compenguy** [comment]
Looks great. I have code that would technically be fixed with this change, but the previous failure case is very unlikely, so I'm going to go ahead and mark the issue as resolved, and open a new issue if I happen to run into anything.
