### ISSUE TITLE
Prints garbages instead of nice borders

### ISSUE THREAD

**Issue by trojczak** [gyscos/Cursive#64]
I was following the tutorial, part 2, and got the following:
![cursive_tut2_error](https://cloud.githubusercontent.com/assets/1974491/18815492/792002ca-8333-11e6-9147-c2aedf140607.jpg)
I use:
`$ rustc --version`
`rustc 1.11.0 (9b21dcd6a 2016-08-15)`
`$ gnome-terminal --version`
`GNOME Terminal 3.18.3`
`$ echo $LANG`
`en_US.UTF-8`

Any ideas why I got these garbages?

**Comment by gyscos** [comment]
That's weird indeed, I can't seem to reproduce locally, though I'm running a slightly more up-to-date (3.20.2) gnome-terminal... :S
What happens when you run it from a TTY?

If you copy & paste this in your terminal, does it render properly?
`print '┌──────┤ Important survey ├───────┐'`

Can you try running it over ssh from another computer? Otherwise, I'll try to set up a minimal VM or docker image to do that.

**Comment by trojczak** [comment]
> In gnome-terminal, right-click, then Profile > Profile preferences, Compatibility tab, is the encoding UTF-8?

Yes, it is.

> If you copy & paste this in your terminal, does it render properly?
> `print '┌──────┤ Important survey ├───────┐'`

Yes, it renders properly.

> Can you try running it over ssh from another computer?

Unfortunately, the same garbage.

I tried it also on a VM machine with Fedora and gnome-terminal 3.20.2 and the result was the same.

**Comment by gyscos** [comment]
Interesting...
Can you run `cargo run --quiet > output.txt`, then press "Ctrl-C" when the program is running (make sure it's compiled first), and send me the resulting file?
What is your `ncurses` version? (`grep NCURSES_VERSION /usr/include/ncurses.h`)

**Comment by trojczak** [comment]
`ncurses` version:
```
#define NCURSES_VERSION_MAJOR 6
#define NCURSES_VERSION_MINOR 0
#define NCURSES_VERSION_PATCH 20160213
#undef  NCURSES_VERSION
#define NCURSES_VERSION "6.0"
#define curses_version() NCURSES_VERSION
```

`locale`:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

[output.txt](https://github.com/gyscos/Cursive/files/493985/output.txt) (I hope this is what you wanted.)

**Comment by gyscos** [comment]
So the output from the binary is wrong.
Can you run `ldd` on the binary to check if it's linking to ncursesw?
For instance :
```
$ ldd target/debug/tuto_2 
	linux-vdso.so.1 (0x00007ffee4716000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f3cd3ba1000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3cd399d000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3cd3780000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3cd3569000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3cd31cb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3cd3e0e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f3cd2ec7000)
```

**Comment by trojczak** [comment]
I see that I have `libncurses.so.5` and in your output it's `libncursesw.so.6`. Is it a problem?
```
	linux-vdso.so.1 =>  (0x00007ffe6c460000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f7f17fed000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f7f17dc4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7f17bbf000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f179a2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7f1778c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f173c2000)
	/lib64/ld-linux-x86-64.so.2 (0x000055ff4d8d7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f170b9000)
```

**Comment by gyscos** [comment]
That's probably the problem. Apparently `ncurses-rs` recently removed `wide` from the default features, but for some reasons on my computer it still links to `ncursesw`... Not sure why.
I'll try manually adding `wide` to the features in the dependencies (pushed to the git master).
Can you try using the git version of cursive to see if it fixes it?
```
[dependencies]
cursive = { git = "https://github.com/gyscos/Cursive" }
```

**Comment by gyscos** [comment]
So it appears you don't have `ncursesw`, the "wide" version of ncurses.
I'm not sure what package you should install to get that. What system are you running this on?
On fedora, I would have thought `ncurses-devel` included that.

**Comment by trojczak** [comment]
I'm running Ubuntu GNOME 16.04. I've installed `libncursesw5-dev` and now the example works. I don't know what lesson we can learn from that. Nevertheless, thanks for your help.

**Comment by gyscos** [comment]
I see.
TIL:
* ncursesw is required for Unicode (and so for almost any cursive app), ncurses is not enough
* At least on Ubuntu, ncursesw is not included in the basic ncurses package

I suppose I should update the readme to mention that.

**Comment by gyscos** [comment]
One last thing: with ncursesw installed, could you please try the crates.io dependency once again? I'm curious about the results.

**Comment by trojczak** [comment]
I switched back to `cursive = "0.2"` and wrong output is back.

**Comment by gyscos** [comment]
Alright, so the wide feature really is necessary (still not sure why my computer is linking to ncursesw no matter what). Thanks for your time!
