### ISSUE TITLE
[FEATURE] Support accurate colors

### ISSUE THREAD

**Issue by Builditluc** [gyscos/cursive#641]
**Is your feature request related to a problem? Please describe.**
When supplying a hex color value to the Theme the colors are not accurate and change from terminal to terminal (I know there is a note in the docs)

**Describe the solution you'd like**
It would be nice if there would be an option in the Theme to enable displaying accurate colors (I don't know if its the right term but something like the truecolor option for vim)

**Describe alternatives you've considered**
I don't really know any other alternative solution (except changing the colors in my terminal configuration)

**Additional context**
I'm writing an application with cursive and a user requested this feature. Link to the Issue: https://github.com/Builditluc/wiki-tui/issues/22

**Comment by gyscos** [comment]
Hi!

Cursive _tries_ to specify "true colors" (which is the full RGB color with 255 values per channel). However, not all backends properly support that.

In particular ncurses (the default backend) does not properly support true colors.

You can try the `colors` example with different backends to see the difference:
With BearLibTerminal (supports true colors)
![Screenshot from 2022-03-09 09-27-59](https://user-images.githubusercontent.com/564903/157461850-3508e56b-b927-4e33-91c9-a535957b7ce2.png)

With termion or crossterm (both support true colors):
![Screenshot from 2022-03-09 09-27-39](https://user-images.githubusercontent.com/564903/157461922-6fde67e0-9cc3-4025-b5c7-0f95f298f666.png)

With ncurses or pancurses (neither support true color):
![Screenshot from 2022-03-09 09-27-48](https://user-images.githubusercontent.com/564903/157461952-234ee468-6f35-4058-9ec1-1b743bfcae75.png)

In addition to that, cursive also supports "terminal palette" colors. There are 255 such colors, and these change depending on your terminal theme. If you look at [the `Color` enum](https://docs.rs/cursive/latest/cursive/theme/enum.Color.html), the `Rgb` variant is "true color", and everything else depends on the terminal configuration.

**Comment by Builditluc** [comment]
Thank you for the information! I switched to the crossterm backend and the colors are now accurate.
