### ISSUE TITLE
No way to spread views so they fit another view

### ISSUE THREAD

**Issue by acz2022** [gyscos/cursive#645]
Hi, is there a way to have number of items in row spread evenly so they cover other view from begin to the end, not just part of it?
Please see the screenshot, I'm talking about the bottom panel, where there is the red button selected. How to make it so the row of buttons covers the entire view it is on, not just the part?
Thank you

Link to the screenshot:
https://postimg.cc/zV7ffXK0

**Comment by gyscos** [comment]
Hi, and thanks for the report!

One way to do that is to add "padding" views. You can use [DummyView](https://docs.rs/cursive/latest/cursive/views/struct.DummyView.html) for that. You give each dummy view full width; the linear layout should share all available space between these.

**Comment by acz2022** [comment]
Hi,
Thank you for your reply. That helped!
