### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by DJDuque** [gyscos/cursive#654]
I am having a lot of trouble implementing something. I don't know if this is an appropriate place to ask for help.

I have a program that loops through some iterators, and I am trying to extract that logic into a "next" button. I am using the memmap2 and midasio crates. The program without Cursive loops through `bank_view` objects as:
```
use memmap2::Mmap;
use midasio::read::file::FileView;
use std::env;
use std::fs::File;

fn main() {
    let args: Vec<String> = env::args().collect();

    for file in &args[1..] {
        let file = File::open(&file).unwrap();
        let mmap = unsafe { Mmap::map(&file).unwrap() };
        let file_view = FileView::try_from(&mmap[..]).unwrap();

        for event_view in &file_view {
            for bank_view in &event_view {
                // Do something with each bank_view
            }
        }
    }
}
```
I want to loop through each `bank_view` with a "next" button. Every time I click the button I want to move to the next `bank_view` and I am having a lot of trouble extracting the logic of the loop above into an external "next" function.
```
fn main() {
    let args: Vec<String> = env::args().collect();

    let mut siv = cursive::default();

    siv.add_layer(
        Dialog::text("...")
            .title("...")
            .button("Quit", |s| s.quit())
            .button("Next", next_bank_view)
    );

    siv.run();
}

fn next_bank_view(_: &mut Cursive) {
    // I want this to get me the next `bank_view`
}
```
Does anybody have an example of a program that does something similar I can look at?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I know you closed the issue, but just in case you didn't find a solution, and/or to help future readers of this issue:
You have a few ways to do something like this:
* Include the iterator in the callback. Either by moving it into the callback closure, or using cursive's user data to store some state in the cursive application. This state could include your iterator, for example a `Box<Iterator<Item = BankView>>`.
* Use a separate thread to read the items one by one, and use a channel (or some other primitive) for synchronization.
  For example using an unbuffered channel, the sending thread would block until the "Next" callback tries to receive from the channel.

**Comment by DJDuque** [comment]
Hi @gyscos,

Thanks for the reply. I closed the issue because I was having a problem with the internal library of the iterators, so I wanted to fix that before trying the `Cursive` app. I have now fixed my problem, but I am still having some trouble implementing the "next" function to advance the iterator with the button. Could you please have a look at my minimal toy example below?

```
use cursive::views::Dialog;
use cursive::Cursive;

fn main() {
    let slice = [1, 2, 3, 4, 5, 6];
    let mut chunks = slice.chunks_exact(2);

    let mut siv = cursive::default();
    siv.add_layer(
        Dialog::text("...")
            .button("Quit", |s| s.quit())
            .button("Next", |s| next_thing(s, &mut chunks)),
    );
    siv.run();
}

fn next_thing<'a, I>(_: &mut Cursive, things: &mut I)
where
    I: Iterator<Item = &'a [u8]>,
{
    // I want to call things.next() and to something with the slice.
}
```

My iterator references an external slice, and I am struggling a bit to get this to work (both with the closure or the `user_data`). If you have time, could you show me how to solve my toy example above?

Thanks again,

Daniel

**Comment by gyscos** [comment]
One question is why you have to work from a slice, and what is the lifetime of that slice going to be, and whether you can "package" it so it doesn't have a lifetime.

For example, a `Vec<T>` can be turned into basically a ` impl Iterator<Item=T>` without lifetime. Most containers can be "embedded" into an iterator just like that. This allows the iterator to be moved around. If you can do that, then you can, for example, store this iterator in cursive's user data:

```rust
fn prepare_iterator() -> Box<dyn Iterator<Item = String>> {
    let some_data = vec![1, 2, 3];

    // We are embedding some `Vec` into an iterator, and adding some map/filters on top.
    let my_iterator = some_data
        .into_iter()
        .map(|i| i * 2)
        .filter(|&i| i > 3)
        .map(|i| format!("Number {i}"));

    Box::new(my_iterator)
}

fn main() {
    let mut siv = cursive::default();

    let my_iterator = prepare_iterator();

    // We can store pretty much any type without a lifetime as user data.
    siv.set_user_data(my_iterator);

    siv.add_layer(cursive::views::Button::new("Next", |s| {
        // We can then retrieve the user data, as long as we specify the exact same type.
        let iterator: &mut Box<dyn Iterator<Item = String>> =
            s.user_data().unwrap();

        if let Some(next) = iterator.next() {
            s.add_layer(cursive::views::Dialog::info(next));
        }
    }));

    siv.run();
}
```

Sometimes, there is no nice "embedded" API, for example for "chunks". In that case, there are a few alternative solutions:
* _Make_ the missing API. It's totally possible to write a chunks iterator that owns the vector, it just isn't in the standard library (that I know of). You _could_ write one, and use that.
* Use some semi-hacky workarounds like one of the various self-referential crates (for example [ouroboros](https://github.com/joshua-maros/ouroboros)). This will let you write a struct that holds the main `Vec`, _as well_ as a chunks iterator that borrows the slice.
* Finally, you can externalize the iterator into a thread, where you keep all borrows as usual. It's the least intrusive _to the looping itself_, but adds more constraints/complexity elsewhere:
    * Instead, you now need to communicate with this separate thread. 
    * While the _iterator_ can borrow anything you want, the _values_ you send have to be owned (and not be references), so you would need to copy and box anything you send.

This last solution could look like:

```rust
use std::sync::mpsc;

fn worker(sender: mpsc::SyncSender<Vec<u8>>) {
    let slice = [1, 2, 3, 4, 5, 6];
    let chunks = slice.chunks_exact(2);

    for chunk in chunks {
        // Each send will block until we actually read from it.
        sender.send(chunk.to_owned()).unwrap();
    }
}

fn main() {
    let mut siv = cursive::default();

    // Create an unbuffered channel.
    let (sender, receiver) = mpsc::sync_channel(0);

    std::thread::spawn(move || worker(sender));

    // We can store pretty much any type without a lifetime as user data.
    siv.set_user_data(receiver);

    siv.add_layer(cursive::views::Button::new("Next", |s| {
        // We can then retrieve the user data, as long as we specify the exact same type.
        let receiver: &mut mpsc::Receiver<Vec<u8>> = s.user_data().unwrap();

        if let Ok(next) = receiver.try_recv() {
            let text = format!("Received {next:?}");
            s.add_layer(cursive::views::Dialog::info(text));
        }
    }));

    siv.run();
}
```
