### ISSUE TITLE
Multi-Buffer support?

### ISSUE THREAD

**Issue by matthiasbeyer** [gyscos/Cursive#67]
I'm not sure whether this is possible already or, if not, a thing that can be implemented with Cursive, so take a grain of salt when reading this.

It would be nice if Cursive could support multi-buffer setups. User-Store-like-example:

> I opened this text file in my cursive app. Now I want to open the settings and they should appear _next to the already opened view_, so I can have them side-by-side

Basically like you do vim split views and so on... if you get what I mean.

Maybe not only this, but also "windowing" where one "window" (view) opens above another one.

Would such a thing be possible with Cursive? If not, would you take this as feature request?

---

As I already said somewhere, I would love to use Cursive as framework to build an user interface for [imag](https://github.com/matthiasbeyer/imag) - and such a thing would be awesome! Though it is a _long_ way for imag and lots of things must be done before we should start a non-cli-interface.

Anyways, I'm following development closely here! :smile:

**Comment by gyscos** [comment]
* It's possible to have views side-by-side with a LinearLayout for instance. May need to add some methods to change focus programatically.
* Adding a view on top of the rest (like a popup) is supported, it's what StackView does. Cursive starts with a StackView by default, but I suppose you could also include one somewhere within another view (not really tested yet).
