### ISSUE TITLE
Styling text in TextView

### ISSUE THREAD

**Issue by haydenflinner** [gyscos/cursive#674]
Hi, first off, thank you for the library with all of the documentation, and for answering other newb questions in prior issues. I started with Rust doing Rustlings on Saturday and here I am Monday with the start to a working custom pager 😄 

I am trying to build effectively a log-viewer, along the lines of `less` or `more` in terms of resource-lightness but with more features. The problem that I'm currently running into is how to display the text that I have buffered up to show the user. I assumed that I could just build a buffer of text out-of-band (with enough bytes contained to be sure it would fill the screen) and then `TextView::set_content` it. This is true as long as I don't throw any colors into that buffer.

If I put ANSI Color codes in the TextView content, I am seeing some escaped form of them printed instead, not actually seeing color. I am guessing this is some magic that curses is doing, based on #637 (although I don't know that my character color escape codes are really that closely related to control codes), and the fact that ncurses is allegedly trying to abstract us away from the terminal. I may try with another backend to see if that helps, but for now wondering if this is something expected.

![Screen Shot 2022-09-05 at 3 51 05 PM](https://user-images.githubusercontent.com/14845292/188511447-7d7be752-7c1d-418a-ac9b-507e6288078e.png)

Similarly, I was wondering about custom styles of text in the TextView in general. It looks to me like the two choices are to style the whole TextView with one style, or to go use the Printer object, which gives up the TextView convenience of wrapping and probably other things (though I'm not personally using the vertical scrolling, I will eventually hook those into my own modification of .content).

----------
In case it helps, here is the code I'm using to see the above behavior:
```
    use ansi_term::Colour::Red;
    let mut siv = cursive::default();

    // We can quit by pressing q
    siv.add_global_callback('q', |s| s.quit());

    let state: String = Red.paint("hello").to_string();
    siv.add_fullscreen_layer(
        Canvas::new(state)
            .with_draw(|text: &String, printer| {
                eprintln!("Printing: {}", text);
                printer.print((0, 0), &Red.paint(text).to_string());
            })
            .with_required_size(|text, _constraints| (text.width(), 1).into()),
    );

    siv.run();
```

**Comment by gyscos** [comment]
Hi, and thanks for the report!

ANSI codes are indeed not forwarded as-is to the terminal. In general, printing text expects text-only (no ANSI or control code, but also a lot of other non-text codes).

> Similarly, I was wondering about custom styles of text in the TextView in general.

`TextView` works with a [`StyledString`](https://docs.rs/cursive/latest/cursive/utils/markup/type.StyledString.html), which can have more than one style at a time. It's actually a sequence of "spans" of text, each with its own style.

Such a `StyledString` can be built in a few different ways: you can start with a single span of text with [`StyledString::styled`](https://docs.rs/cursive/latest/cursive/utils/span/struct.SpannedString.html#method.styled), and manually concatenate other styles with [`append_styled`](https://docs.rs/cursive/latest/cursive/utils/span/struct.SpannedString.html#method.append_styled). 

A more manual way is to start from the entire "source" string, and define the spans yourself, using [`StyledString::with_spans`](https://docs.rs/cursive/latest/cursive/utils/span/struct.SpannedString.html#method.with_spans).

For some markup languages (currently only [`markdown`](https://docs.rs/cursive/latest/cursive/utils/markup/markdown/index.html)), a parser already exists to prepare such a `StyledString` from a source `String` (see [`markdown::parse`](https://docs.rs/cursive/latest/cursive/utils/markup/markdown/fn.parse.html)).

It looks like we could totally add such a method to parse ANSI codes. This way, you would first parse the content into a `StyledString`, and give _that_ to the `TextView`.

If you want to skip `TextView`, the main thing it does is [line-wrapping](https://github.com/gyscos/cursive/blob/main/cursive-core/src/views/text_view.rs#L383-L384) (and caching thereof). From there, [it's not _too_ complicated to feed that to the printer](https://github.com/gyscos/cursive/blob/main/cursive-core/src/views/text_view.rs#L405-L423).

**Comment by gyscos** [comment]
I just pushed a commit adding an ANSI parser, please tell me if that solves your issue!

To use it:

```rust
// Make sure you include the `ansi` feature in cursive.

let content = std::fs::read_to_string("some_file_with_ansi_codes").unwrap();
let styled = cursive::utils::markup::ansi::parse(content);
let text_view = cursive::views::TextView::new(styled);
```

**Comment by gyscos** [comment]
Note however that the parser above assumes you have access to the entire file content.

If you want to work with a sliding buffer, only keeping part of the file in memory, it may be more tricky to properly handle any color that would carry over.

It's really not an easy thing to properly support that, and many applications just ignore any markup before the currently-shown text.

If you really do want to only load part of the file _and_ properly handle any markup, it's possible but most likely more complex. Here's an idea: load the file content into "blocks", such that blocks do not end within an ANSI escape sequence.

At any point, your application would keep in memory:
* The starting index and length of all blocks loaded so far into the source file
* The starting style of all blocks loaded so far
* The content of some _active_ blocks.

When the user gets near the end of the current active blocks, you need to prepare a new block. To do that, fill some blocks up to the desired block size. Starting from the end of the block, look back a couple bytes to see if there's the beginning of an escape sequence. If so, trim the block until the start of the sequence.

For this to work, we need to way to parse some text with a starting style, which I did not include in the initial API. Shouldn't be too hard though, so I'll add that now.

**Comment by haydenflinner** [comment]
That worked, thank you!! Quickest question to patch I've ever seen! 

So from the source it looks like what I'm doing here is: I'm hand-writing an ANSI string (`Red.paint()`), then ansi parser is decoding those to Styles, then the Styles are being used to command the back-end (in this case by default ncurses), to generate whatever it needs to to color the terminal, which is probably the same ansi codes. At least we're not running Electron, I bet this is still too fast to be visible to naked eye 😆 a few extra bytes never hurt anybody in a cmdline display.

The logs I'm reading from file aren't actually colored, I planned on coloring based on runtime rules from a config file, but now maybe I'll generate StyledStrings instead of ansi strings directly, don't think it'll matter too much which I go with. Thanks again for the assistance in using the library! Hopefully will have something cool to try in the next few weeks 😄 

<img width="575" alt="Screen Shot 2022-09-07 at 8 11 04 PM" src="https://user-images.githubusercontent.com/14845292/189011748-a7dbde82-9cb2-4da0-97d0-89dee5751ef6.png">

**Comment by gyscos** [comment]
Glad I could help! You might not end up needing the ANSI parser in the end, but it's probably not wasted anyway, and you could even take it as inspiration (along with the markdown parser) to build your own "rule-based" parser. You should be able to keep the input text String as-is, and define styled spans indexing into it. That's the main advantage compared to rewriting the content with ansi codes: you don't have to copy too much data around.

**Comment by gyscos** [comment]
After writing this ansi parser I tried to write one that uses syntect, a common syntax highlighting crate.

The result is `cursive-syntect`, with [an example](https://github.com/gyscos/cursive/blob/main/cursive-syntect/examples/parse.rs) showing how to use it: the example loads itself and highlights it as rust code, with one of the default themes.

Though it might still not be quite what you need, as your coloring configuration might not be an actual syntax that syntect could recognize...
