### ISSUE TITLE
[BUG] ncurses.h is required for compilation even though termion backend is used

### ISSUE THREAD

**Issue by eliabieri** [gyscos/cursive#683]
**Describe the bug**
`ncurses.h` is required for compilation even though the termion backend is used.  
I used the [cross](https://github.com/cross-rs/cross) crate to cross compile my project where I don't have the ncurses header available.

**To Reproduce**
Take any cursive project, install `cross` and run: 
`cross build --release --target armv7-unknown-linux-gnueabihf`

**Expected behavior**
It compiles without having the ncurses header available

**Screenshots**
<img width="980" alt="CleanShot 2022-10-07 at 08 53 50@2x" src="https://user-images.githubusercontent.com/7094813/194486131-2ca887ad-c3f7-4453-87ce-6139c7b6ce07.png">

**Environment**
- MacOs 12.6
- `cursive = { version = "0.20", features = ["termion-backend"] }`

```❯ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

**Comment by gyscos** [comment]
Related to https://github.com/gyscos/cursive/discussions/684#discussion-4456532

The conclusion was that default features were still enabled, which currently includes the ncurses backend. Removing default features allowed them to properly cross-compile using the termion backend.

**Comment by gyscos** [comment]
I'll close this ticket, but feel free to re-open if you think there's more to it.
