### ISSUE TITLE
pancurses back-end?

### ISSUE THREAD

**Issue by nabijaczleweli** [gyscos/Cursive#69]
[`pancurses`](https://crates.io/crates/pancurses) uses either ncurses or pdcurses as back-end depending on the platform.

Since `ncurses-rs` doesn't work on Windowsx86_64 (https://github.com/jeaye/ncurses-rs/issues/78) this could make `cursive` actually build :P

I've had a cursory look at how the back-end system is implemented and am pretty sure this can be just simply feature-enabled if not completely switched out.

I can make a PR for this, just need a green light on one of the options.

**Comment by nabijaczleweli** [comment]
Alternatively, we could set up a different `pdcurses` back-end but that's twice the work for no much return tbh

**Comment by gyscos** [comment]
Having multiple backends activated by features is also what I had in mind. Termion is a prime candidate for a new backend, but we can of course provide pancurses as an alternative.

Please tell me if you have troubles writing the corresponding backend; it was recently updated to allow for internal state, but may still lack features needed for some backend libraries.

**Comment by nabijaczleweli** [comment]
@gyscos I need `Backend::clear()` to be statesome (have a `&self` arg), but there's a couple of `::B::clear()`s, how can I go about doing that?

**Comment by nabijaczleweli** [comment]
Well, that and https://github.com/ihalila/pancurses/issues/3

**Comment by gyscos** [comment]
Yeah, I didn't update `Backend::clear` because of that. I'll see if I can find a way to make them all take `&self`.
* For `Menubar::hide()`, we'll clear the view outside of this method. Since this method is only called from the event handler when reacting to the `Esc` key, it could instead return an event callback `|s| s.clear` or something like that.
* For `StackView::pop_layer` and `StackView::layout`, I'm still undecided:
    * If it's the top-level stack view, it could instead clear the view before the next draw.
    * It it's not the top-level stack view, its own space will be cleared by its parent anyway, and it won't need it.

The ultimate solution would be to add a method to views to recursively check if a child requires a clear, but I'd rather avoid further complicating the `View` trait.

**Comment by nabijaczleweli** [comment]
I'm gonna make a PR in the current state and then we'll be able to think on live code, eh?

**Comment by gyscos** [comment]
Commit 44dbd5826eb12f0b7e7ae3e2e78410aa761f7188 should update `Backend::clear` to take a `&self`.

**Comment by gyscos** [comment]
Also ad7606ca5571f229411b5726276e4bf8dda419e5 now adds feature-based backend selection.

**Comment by gyscos** [comment]
Though it seems I broke the shadows in the process - investigating.

**Comment by nabijaczleweli** [comment]
How long would it take for a release with this in would be feasible?

**Comment by gyscos** [comment]
As soon as the pancurses backend works properly. I'll add issues to address specific problems.
