### ISSUE TITLE
[BUG] `scroll_to_bottom()` scrolls to one line above the bottom with default scroll strategy

### ISSUE THREAD

**Issue by jwodder** [gyscos/cursive#695]
Consider the following code:

```rust
use cursive::traits::{Nameable, Resizable, Scrollable};
use cursive::views::{EditView, LinearLayout, ScrollView, TextView};
use cursive::Cursive;

fn main() {
    let mut siv = cursive::default();
    siv.add_fullscreen_layer(
        LinearLayout::vertical()
            .child(
                LinearLayout::vertical()
                    .scrollable()
                    .with_name("chatbox")
                    .full_height(),
            )
            .child(
                EditView::new()
                    .on_submit(sendtext)
                    .with_name("input")
                    .full_width(),
            ),
    );
    siv.run();
}

fn sendtext(s: &mut Cursive, line: &str) {
    s.call_on_name("chatbox", |view: &mut ScrollView<LinearLayout>| {
        view.get_inner_mut().add_child(TextView::new(line));
        view.scroll_to_bottom()
    });
    s.call_on_name("input", |view: &mut EditView| view.set_content(""));
}
```

My expectation is that, once enough lines have been submitted to fill up "chatbox", submitting another line will lead to that new line being visible on the row immediately above "input" due to the call to `view.scroll_to_bottom()`.  In actuality, once "chatbox" is full, like so:

<img width="617" alt="Screen Shot 2022-11-18 at 18 45 38" src="https://user-images.githubusercontent.com/98207/202821395-13daf0b1-ec10-4c7d-8bed-e9e8428a3730.png">

entering another line ("Line 24") will result in that new line being below the current-displayed portion of the ScrollView:

<img width="617" alt="Screen Shot 2022-11-18 at 18 45 46" src="https://user-images.githubusercontent.com/98207/202821451-40720dcb-c0ac-41a5-9ac8-988fe404e030.png">

If another line ("Line 25") after that is entered, Line 24 will become visible, but Line 25 will remain unshown:

<img width="617" alt="Screen Shot 2022-11-18 at 18 45 56" src="https://user-images.githubusercontent.com/98207/202821539-c0a941ca-aba7-4bb0-bf15-6fb70bf1baf2.png">

And likewise after entering Line 26:

<img width="617" alt="Screen Shot 2022-11-18 at 18 46 10" src="https://user-images.githubusercontent.com/98207/202821606-e8490922-c56e-4de2-ac18-4c6384322eec.png">

If "chatbox" is then manually scrolled to the bottom (producing the visual result I expected in the first place):

<img width="617" alt="Screen Shot 2022-11-18 at 18 46 23" src="https://user-images.githubusercontent.com/98207/202821634-2032e8f7-5c42-4d07-a623-e270a0db9aa2.png">

Entering another line will return it to the old behavior:

<img width="617" alt="Screen Shot 2022-11-18 at 18 46 31" src="https://user-images.githubusercontent.com/98207/202821664-7cc44847-fc63-4c64-8fae-392e43c30906.png">

Unlike #651, `scroll_to_bottom()` is indeed doing something, as removing that line results in the `ScrollView` never scrolling down no matter how many new lines are added.

**Environment**
* Operating system used: macOS 11.6.8, using GNU screen 4.09.00 (`TERM=screen-256color`) inside Terminal.app (`TERM=xterm-256color`)
* Backend used: ncurses
* Current locale:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

* Cursive version: 0.20.0 from crates.io

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I suspect this happens because scroll_to_bottom relies on the last "known size" of the content, which might only update during calls to layout. Here it is called right after adding an item, and it might not be properly updated yet.
I'll work on a fix to properly update these caches as needed.

**Comment by gyscos** [comment]
The latest commit should bring a fix for that.

Note that for this, you can also use [`scroll_strategy`](https://docs.rs/cursive/latest/cursive/views/struct.ScrollView.html#method.scroll_strategy), which may be currently less cpu-intensive.

**Comment by gyscos** [comment]
Should have been released by now. I'll close the ticket, but feel free to re-open if needed.
