### ISSUE TITLE
[BUG] Focusing/Clicking on ListChild has offset if it follows a delimiter

### ISSUE THREAD

**Issue by WeirdConstructor** [gyscos/cursive#697]
**Describe the bug**
I have a ListView, with some buttons. If there is a delimiter in the ListView, clicking on the children that come after that
has an offset. That means: Not the child I click on is focused, but the child following it.

I think I found the bug too:

in `views/list_view.rs` in the `layout` implementation there is this code that recomputes the child heights:

```rust
        self.children_heights.resize(self.children.len(), 0);
        for (child, height) in self
            .children
            .iter_mut()
            .zip(&mut self.children_heights)
            .filter_map(|(v, h)| v.view().map(|v| (v, h)))
        {
            // TODO: Find the child height?
            *height = child.required_size(size).y;
            child.layout(Vec2::new(available, *height));
        }
```
The problem is this line:
```rust
            .filter_map(|(v, h)| v.view().map(|v| (v, h)))
```

That line skips the delimiter ListChild enums, because the `view()` method does not return anything for a delimiter:
```rust
impl ListChild {
    fn view(&mut self) -> Option<&mut dyn View> {
        match *self {
            ListChild::Row(_, ref mut view) => Some(view.as_mut()),
            _ => None,
        }
    }
}
```

**To Reproduce**
1. Make a ListView, add 2 childs (eg. Buttons).
2. Add a delimiter
3. Add some more button as child

**Expected behavior**
The clicked on child gets the focus/is activated/recieves the event. not the child following it.

**Screenshots**
Here is a little screencast:

http://m8geil.de/data/push/kazam_sc_00003_up.mp4

**Environment**
* Operating system used: Linux Ubuntu 22
* Backend used: crossterm
* Current locale:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```
* Cursive version: from crates.io 0.20.0

**Additional context**

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, the way height was computed and used for delimiters was not ideal. Should be fixed now!

**Comment by WeirdConstructor** [comment]
@gyscos Confirmed, thanks a lot for the fix and for Cursive in general! :-)
