### ISSUE TITLE
Support themes

### ISSUE THREAD

**Issue by gyscos** [gyscos/Cursive#7]
Define at runtime some colors and characters used for special effects (border, highlight, shadow, ...).
Probably provide a default theme that looks like the blue interface used by classic ncurses dialog applications.

**Comment by Gyscos** [comment]
Initial theme support. Using non-standard colors breaks compatibility with TTY terminals, so we may want to check for support before doing that (and fallback to default colors when we have to).

Better theme support would enable to:
* Disable shadows
* Change default padding
* (maybe) Change layout for default views

**Comment by Gyscos** [comment]
A dummy theme example file shows what the options could be. No parser exist for it yet, though.

**Comment by Gyscos** [comment]
Latest commit rework how themes work, and correctly parse the example theme file.
Still left to do: shadows and borders.

**Comment by gyscos** [comment]
Themes are currently properly applied and affect the way views are drawn.
They don't currently affect their layout though. This means disabling shadows or borders doesn't actually make the views smaller.
Changing that would require either:
* Modifying the `get_min_size` and `layout` methods to accept a theme as parameter
* Add a global variable with the current theme

I'm not a big fan of either... :(
We'll probably go with the first solution, unless I find something better.

**Comment by gyscos** [comment]
With "real" full-screen views now available (independantly of the shadow style), having the theme affect the layout is not as important anymore.

The other candidate for styled layout would be a `Dialog` with horizontal/vertical buttons, but dealing with this at the `Dialog` level looks easier.

So I think themes are complete for now.
