### ISSUE TITLE
[FEATURE] `set_visible(false)` to hide a view and show it programatically later?

### ISSUE THREAD

**Issue by eminfedar** [gyscos/cursive#707]
**Is your feature request related to a problem? Please describe.**
Example use case: I need to show/hide a child in a LinearLayout when a button clicked. I mean for example I have 3 columns and when I pressed a button it should hide the first one and I can see 2 columns. If I press again I should see 3 columns again. Not removing it from memory but just hide it.

**Describe the solution you'd like**
`panel.set_visible(false)` <- something like this can be used for the purpose.

**Describe alternatives you've considered**
Maybe LinearLayout may have a function like `hide_child(index)` or `show_child(index)` then the child's visibility stored in LinearLayout not in the child. You decide :)

Have a nice day!

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Would something like [`HideableView`](https://docs.rs/cursive/latest/cursive/views/struct.HideableView.html) work for you? It would wrap the required child, and you'd be able to hide/show it on demand.

**Comment by eminfedar** [comment]
That is exactly what I am looking for!

Thanks a lot!
