### ISSUE TITLE
[BUG] `cursive_core::views::menu_popup::MenuPopup::scroll_down` loops infinitely if all children are disabled

### ISSUE THREAD

**Issue by stIncMale** [gyscos/cursive#708]
**Describe the bug**
If all items in a subtree in a menubar are disabled, this subtree can hang the thread executing `CursiveExt::run`. 

**To Reproduce**
The reproducer:

```rust
use cursive::{
    event::{Event, Key},
    menu::{Item, Tree},
    Cursive, CursiveExt,
};

fn main() {
    let mut tui = Cursive::new();
    tui.menubar().add_subtree("Subtree", {
        let mut menu_subtree = Tree::new().leaf("Leaf", |_| ());
        // if this line is commented out, the application works fine
        menu_subtree.children.iter_mut().for_each(Item::disable);
        menu_subtree
    });
    tui.set_autohide_menu(false);
    tui.add_global_callback(Event::Key(Key::Esc), Cursive::select_menubar);
    tui.add_global_callback(Event::Char('q'), Cursive::quit);
    tui.run();
}
```

To reproduce, start the application and press `Esc` (puts focus on the `Subtree` element), then `Down arrow` (causes the subtree to pop up), then `Down arrow` (`MenuPopup::scroll_down` tries to put focus on an enabled child of a subtree, but loops forever as there are no enabled elements). The application stops responding to user input and starts consuming a noticeable amount of CPU time.

Note that `MenuPopup::scroll_up` appears to have the same issue.

**Expected behavior**
Instead of hanging, the application does not focus on any subtree element and allows one to continue using the menubar.

**Environment**

* Operating system used:
  * Windows 10;
  * Ubuntu 22 on WSL 2 on Windows 10.
* Backend used: crossterm 0.25.0.
* Current locale: C.UTF-8.
* Cursive version: 0.20.0 (cursive_core 0.3.6).

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, we were carelessly looping endlessly in this situation. Should be fixed in the latest commit.

**Comment by stIncMale** [comment]
Thanks for the quick fix! Now I need to wait for the next release:)

**Comment by stIncMale** [comment]
Works like a charm.
