### ISSUE TITLE
[BUG] GitHub dependabot warnings from cursive-core dependencies

### ISSUE THREAD

**Issue by mhvelplund** [gyscos/cursive#724]
**Describe the bug**
`cursive-core` uses a crate, `owning_ref`, with known issues which causes GitHub dependabot to show an alert in projects that use `cursive-0.20.0`.

**To Reproduce**
I created a project and added Cursive as a dependency:

```toml
cursive={ version="0.20.0", default-features=false, features=[
    "crossterm-backend",
] }
```

**Expected behavior**
No warnings.

**Screenshots**
[![Screenshot-2023-03-26-084308.png](https://i.postimg.cc/D0NHY2kh/Screenshot-2023-03-26-084308.png)](https://postimg.cc/Mfy9nJp3)

**Environment**
* Operating system used: Windows 11
* Backend used: crossterm ...
* Current locale (run `locale` in a terminal): en_US.UTF-8
* Cursive version (from crates.io, from git, ...): 0.20.0

**Comment by gyscos** [comment]
Thanks for the report.

This looks related to #678 . We're not directly affected by the vulnerability, but I agree it would be nice to eventually move to something that's not causing this warning.

**Comment by gyscos** [comment]
`owning_ref` is no longer a dependency.
