### ISSUE TITLE
[BUG] menubar example background doesn't refresh if not focussed

### ISSUE THREAD

**Issue by lesleyrs** [gyscos/cursive#727]
**Describe the bug**
When pressing `esc` to focus the menubar the bg doesn't refresh after resizing screen.

**To Reproduce**
crossterm backend

**Expected behavior**
Expected it to refresh when resizing the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/19632758/230686325-064753df-b5af-4947-b120-a2cee8453e24.png)

**Environment**
* Windows 10
* Crossterm backend
[30046dc563b3041092f0f0475ddf87a84eef25f9](https://github.com/gyscos/cursive/commit/30046dc563b3041092f0f0475ddf87a84eef25f9)

**Additional context**
This might be an inherent limitation? Only tried the examples.

**Comment by unclev** [comment]
The same with

**Environment**

- Linux (OpenSUSE Tumbelweed)
- ncurses backend

**Additional context**
Alacritty terminal. (Reproduced not in the example, but in my app being developed).
