### ISSUE TITLE
[FEATURE] Support for transparent Palette color

### ISSUE THREAD

**Issue by aadi58002** [gyscos/cursive#738]
**Is your feature request related to a problem? Please describe.**
Most terminal these days either have transparent or blur background
Would it be possible to make the background transparent ?

**Describe the solution you'd like**
Add a transparent color options to colors.
Or adding support for `rgba` color format can also work.

**Comment by gyscos** [comment]
Hi!

From what I've seen, terminals usually support transparency for the background only.
In these case, you can use the color [`TerminalDefault`](https://docs.rs/cursive/latest/cursive/theme/enum.Color.html#variant.TerminalDefault), and it'll be match your terminal settings.

I do not know of a way to use transparent colors apart from that, but I'd be interested if you found something!

**Comment by aadi58002** [comment]
> Hi!
> 
> From what I've seen, terminals usually support transparency for the background only. In these case, you can use the color [`TerminalDefault`](https://docs.rs/cursive/latest/cursive/theme/enum.Color.html#variant.TerminalDefault), and it'll be match your terminal settings.
> 
> I do not know of a way to use transparent colors apart from that, but I'd be interested if you found something!

Sorry for the late reply
when using the `TerminalDefault` it picks
I am trying to look into how tools like neovim enable transparent bg from terminal scheme when some themes.

![1688967197_grim](https://github.com/gyscos/cursive/assets/96418027/cfdc9fe3-2065-4139-8c18-7756ac26be09)
![1688967204_grim](https://github.com/gyscos/cursive/assets/96418027/c21fc342-87c2-40bb-9777-ef5b554cc146)
![1688967217_grim](https://github.com/gyscos/cursive/assets/96418027/0947a38b-c643-49e4-8ff8-d5249368220a)
