### ISSUE TITLE
Documentation issue about textarea set_cursor

### ISSUE THREAD

**Issue by massimo79m** [gyscos/cursive#753]
the documentation says : This method panics if cursor is not the beginning of a character in the content string.
it should report "bytes" in place of "characters".

**Comment by massimo79m** [comment]
Please remove the bug label. thank you

**Comment by gyscos** [comment]
Thanks for the report!

The doc now states:

```
    /// Moves the cursor to the given byte position.
    ///
    /// # Panics
    ///
    /// This method panics if `cursor` is not the starting byte of a character in
    /// the content string.

```
