### ISSUE TITLE
[FEATURE] Multiline EditView

### ISSUE THREAD

**Issue by Cg1340** [gyscos/cursive#769]
How to get a multiline editview? I tried using the function `fixed_size()` but it didn't work.

**Comment by yuki0iq** [comment]
You can use [`TextArea`](https://docs.rs/cursive/latest/cursive/views/struct.TextArea.html). There is also an [example](https://github.com/gyscos/cursive/blob/main/cursive/examples/text_area.rs) which shows how to use it.

EditView was probably designed to be single-line edit control, so if you have to be able to input multiple lines, you may consider using TextArea.

If, however, you want to have a "one line" edit with word wrapping, you can wrap TextArea with OnEventView and silence 'Enter' key and sanitize paste data (but it probably wouldn't be needed).

**Comment by Cg1340** [comment]
It worked. Thank you very much.
