### ISSUE TITLE
[FEATURE] Menubar to render StyledStrings

### ISSUE THREAD

**Issue by svfat** [gyscos/cursive#781]
**Is your feature request related to a problem? Please describe.**
I'm frustrated because the [menubar](https://docs.rs/cursive/latest/cursive/views/struct.Menubar.html)  doesn't render colours from [StyledString](https://docs.rs/cursive/latest/cursive/utils/markup/type.StyledString.html). Basically, I would like to have ability to highlight keyboard shortcuts (e.g. "F" in "File")

**Describe the solution you'd like**
I would like the [menubar](https://docs.rs/cursive/latest/cursive/views/struct.Menubar.html) to render the colours specified in the [StyledString](https://docs.rs/cursive/latest/cursive/utils/markup/type.StyledString.html). For example, when passing a [StyledString](https://docs.rs/cursive/latest/cursive/utils/markup/type.StyledString.html) with specific colours, those colours should appear on the menubar.

**Describe alternatives you've considered**
I considered using plain strings instead, but this doesn't allow for the use of colours or styles, which limits the visual customisation options.

**Additional context**
Here is a minimal example demonstrating the issue:
```rust
use cursive;
use cursive::utils::markup::StyledString;
use cursive::theme::BaseColor;
use cursive::theme::Color;
use cursive::theme::Style;
use cursive::theme::Effect;

fn main() {
    let mut siv = cursive::default();
    let mut styled = StyledString::plain("Isn't ");
    styled.append(StyledString::styled("that ", Color::Dark(BaseColor::Red)));
    styled.append(StyledString::styled(
        "cool?",
        Style::from(Color::Light(BaseColor::Blue)).combine(Effect::Bold),
    ));
    siv.menubar()
        .add_leaf(styled, |s| s.quit());
    siv.set_autohide_menu(false);
    siv.add_global_callback('q', |s| s.quit());
    siv.run();
}
```

![screenshot](https://github.com/gyscos/cursive/assets/2899800/8ab919ed-bc2d-4511-bc58-37cc3c1e6642)

**Comment by gyscos** [comment]
Sure!

There's two parts to the menubar:

* The backend menu tree representation, in [menu.rs](https://github.com/gyscos/cursive/blob/main/cursive-core/src/menu.rs). Looks like I already updated that to support `StyledStrings` - yay!
* The UI parts. There's 2 views used in the menu: the menubar itself, and the popups that open when a category is selected.
    * The [menu popups](https://github.com/gyscos/cursive/blob/main/cursive-core/src/views/menu_popup.rs). Here too, it has already been updated to support styled strings.
    * The [menubar](https://github.com/gyscos/cursive/blob/main/cursive-core/src/views/menubar.rs). Here too apparently I updated that to support StyledString, _but_ I did not properly update the [`draw` implementation](https://github.com/gyscos/cursive/blob/main/cursive-core/src/views/menubar.rs#L271): first we call [`item.label()`](https://github.com/gyscos/cursive/blob/main/cursive-core/src/menu.rs#L88) which ignores the style, and [here](https://github.com/gyscos/cursive/blob/main/cursive-core/src/views/menubar.rs#L298) we only call `printer.print((offset, 0), &format!(" {label} "));`, which is not style-aware.

So to fix this last point, I would recommend making 2 changes:
* Adding a `menu::Item::styled_label(&self) -> SpannedStr<Style>`, which returns either the styled string stored from the item, or an unstyled `"|"` if it's a delimiter.
* Updating the `Menubar::draw` implementation to call this new `styled_label()` method to get the label, and use `Printer::print_styled` to print it.
    * Right now we use `format!(" {label} ")` to add spaces around the label. It may be a better idea to instead make 3 print calls: one (regular `Printer::print`) for each space, and one (`Printer::print_styled`) for the styled label.

**Comment by svfat** [comment]
Wow, thanks for the thorough instructions. The fix seems to work, I will test it and prepare a proper PR soon


<img width="324" alt="cool" src="https://github.com/gyscos/cursive/assets/2899800/4fafe2d0-9930-4406-92ba-111a3d2c9275">

**Comment by svfat** [comment]
merged https://github.com/gyscos/cursive/pull/784
