### ISSUE TITLE
Pancurses backend doesn't handle backspace properly

### ISSUE THREAD

**Issue by nabijaczleweli** [gyscos/Cursive#81]
Test by putting down a `TextEdit` with some default text and press Backspace on your keyboard.

**Comment by gyscos** [comment]
I get a correct `Key(Backspace)` when pressing the backspace key.
Maybe it depends on the OS/terminal used? Can you try the `key_codes` example?
```
cargo run --example edit --no-default-features --features pancurses
```

I tried the `edit` example, and it seems to work fine. Maybe the issue is with default text in the `EditView`?... What's the exact code you tried?

**Comment by nabijaczleweli** [comment]
OS: Win10x86_64
Terminal: `cmd`

`edit` example doesn't work. `key_codes` example yields ![image](https://cloud.githubusercontent.com/assets/6709544/19411294/3d951778-92ff-11e6-9466-ca94721e0236.png), so I'm guessing handling that would fix it?

[Exact code](https://github.com/nabijaczleweli/poke-a-mango/blob/edaf5fab0075bcf95eb2b770b66f5304daa1db2a/src/main-tui.rs#L126-L129).

**Comment by gyscos** [comment]
Indeed, it seems ASCII `8` is backspace, but since linux uses an escape code instead I never noticed it.

**Comment by nabijaczleweli** [comment]
PR fix submitted, confirmed works.

**Comment by gyscos** [comment]
Actually, can you try the Del key? Does it send `Key(Del)`, or `Key(Backspace)`?

**Comment by nabijaczleweli** [comment]
Del works
