### ISSUE TITLE
`on_select` for ListView

### ISSUE THREAD

**Issue by Ameobea** [gyscos/Cursive#94]
In my application, I'd like to have some explanatory text be displayed depending on the selected element in a` ListView`.  However, it seems that no functionality exists to register a callback for this or even access the focused element of a given `ListView` (`focus` is private).

I'd be happy to implement this myself and create a PR.  I'd add `on_select` and `set_on_select` methods to `ListView` (similar to that of `SelectView`) and perhaps expose a `get_focused(&self) -> usize` to get the currently focused element.

Would this be something that you'd be willing to accept?

**Comment by gyscos** [comment]
Absolutely, I'm not sure why I didn't include one already.

**Comment by Ameobea** [comment]
Resolved in 9894dd97153571d9a545c9b5f101c2fa65aeaa48
