### ISSUE TITLE
Can content be appended to the bottom of a scrollable TextView?

### ISSUE THREAD

**Issue by jgallagher** [gyscos/Cursive#97]
Is it possible to append to the bottom of a `TextView` and have the view immediately scroll down so the new content is visible (like a chat room or scrolling log file)? I tried this:

```rust
let s = "content to append";
let tv = cursive.find_id::<TextView>("text").unwrap();
let content = format!("{}\n{}", tv.get_content(), s);
tv.set_content(content);
tv.on_event(Event::Key(Key::End));
```

which nearly works - it scrolls down to the end of what `get_content()` returned, but stops just before the newly-appended content (maybe the height is being reused before recalculating due to the new content?), but that would be a pretty hacky workaround even if it was fine.

**Comment by jgallagher** [comment]
I was able to get a workaround going by wrapping the text view in a `SizedView` and forcing a layout after setting the content:

```rust
let s = "content to append";
let stv = cursive.find_id::<SizedView<TextView>>("text_sized").unwrap();
let content = format!("{}\n{}", stv.view.get_content(), s);
stv.view.set_content(content);
stv.view.layout(stv.size);
stv.view.on_event(Event::Key(Key::End));
```

Another I tried (unsuccessfully) was setting the vertical alignment to bottom. Should scrolling to the bottom be the default if valign is bottom?

**Comment by gyscos** [comment]
Dynamic content was indeed not thoroughly planned in the current `TextView` design...
The vertical alignment has no effect when the view is scrolling.

I could add a flag to keep the scrollbar to the bottom of the view, even after content/size changes.
I'm trying to think of another strategy to move the scrollbar on such changes, but maybe keeping the current row ID (current behaviour) and sticking to the bottom are the two main interesting behaviours.

Beyond that, it'd be nice to allow more customisation of the TextView, possibly allowing arbitrary "scrolling adjustments"...

**Comment by jgallagher** [comment]
"Go back to the top" is a third reasonable strategy. If I have 1000 lines and and am currently looking at row 500, but then I replace all 1000 lines with completely new content that's > 500 lines long, staying at row 500 probably isn't desirable.

**Comment by gyscos** [comment]
I added a `ScrollStrategy` enum, with currently 3 variants: `KeepRow` (the current behaviour), `StickToBottom` and `StickToTop` which are pretty self-explanatory.
`TextView` now has such a strategy, which defaults to `KeepRow` and resets to it when the user scrolls manually.
You could for instance set the strategy to `StickToBottom` every time you change the content.

**Comment by jgallagher** [comment]
Awesome, thanks!

**Comment by gyscos** [comment]
Note: there is now a `TextView::append_content` method.
It's still not easy to behave like a circular buffer and drop the first few lines though.
